// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Treasury.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  TreasuryErrors,
  TreasurySpec,
} from "@/contracts/treasury/constants.ts";
import type {
  TreasuryCall,
  TreasuryConstructorArgs,
  TreasuryEvents,
  TreasuryInvocation,
  TreasuryInvocationResult,
  TreasuryMethod,
  TreasuryMethodMap,
  TreasuryOutputs,
} from "@/contracts/treasury/types.ts";

export * from "@/contracts/treasury/constants.ts";
export * from "@/contracts/treasury/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Treasury extends Contract {
  /**
   * Pauses new fee collection, commitments, and investment, not mature exits.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `operator` - Authorized RBAC Admin.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or invalid pause transitions.
   */
  readonly pause: TreasuryMethod<"pause"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Pause, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Pause,
      }),
  };

  /**
   * Burns mature VNTY and transfers dfTokens without market valuation.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Authorized commitment owner.
   *
   * # Returns
   * The VNTY burned, dfTokens transferred, and timestamps.
   *
   * # Errors
   * Rejects missing or immature commitments, zero output, invalid share
   * administration, or token transfer failure.
   */
  readonly redeem: TreasuryMethod<"redeem"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Redeem, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Redeem,
      }),
  };

  /**
   * Resumes new fee collection, commitments, and investment.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `operator` - Authorized RBAC Admin.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or invalid pause transitions.
   */
  readonly unpause: TreasuryMethod<"unpause"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Unpause, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Unpause,
      }),
  };

  /**
   * Replaces Treasury code; migrating legacy direct-asset storage is not
   * supported.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed compatible replacement Wasm.
   * * `operator` - Authorized RBAC Upgrader.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unavailable Wasm.
   */
  readonly upgrade: TreasuryMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Invests live idle USDC toward existing whole-vault strategy shortfalls.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `amount` - Maximum USDC base units; zero uses all execution-time idle
   * cash.
   * * `operator` - Authorized RBAC Rebalancer.
   *
   * # Returns
   * Executed USDC budget and per-strategy investment instructions.
   *
   * # Errors
   * Rejects negative budgets, pause, unhealthy NAV, paused targets, or any
   * underlying investment failure; the whole batch rolls back.
   */
  readonly rebalance: TreasuryMethod<"rebalance"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Rebalance, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Rebalance,
      }),
  };

  /**
   * Reads the Treasury's vault and distribution configuration.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The stored configuration.
   *
   * # Errors
   * Fails when configuration is absent or incompatible.
   */
  readonly getConfig: TreasuryMethod<"get_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetConfig,
      }),
  };

  /**
   * Reads whether new fees, commitments, and investment are paused.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The current pause flag.
   *
   * # Errors
   * Storage decoding errors propagate.
   */
  readonly getPaused: TreasuryMethod<"get_paused"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPaused, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPaused,
      }),
  };

  /**
   * Deposits a cash fee idle in DeFindex and issues VNTY rewards.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `payer` - Authorized payer.
   * * `amount` - Positive fee in USDC base units.
   *
   * # Returns
   * The actual retained value, dfTokens received, and VNTY issued.
   *
   * # Errors
   * Fails while paused, on unavailable net NAV, invalid deposit output, zero
   * share mint, transfer, or authorization failure.
   */
  readonly collectFee: TreasuryMethod<"collect_fee"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CollectFee, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CollectFee,
      }),
  };

  /**
   * Values only Treasury's dfToken position, including idle USDC inside
   * DeFindex.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * A single dfToken position, net USDC NAV, issued VNTY, and virtual share
   * price.
   *
   * # Errors
   * Fails if guarded DeFindex valuation is unavailable or accounting
   * overflows.
   */
  readonly getSnapshot: TreasuryMethod<"get_snapshot"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetSnapshot, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetSnapshot,
      }),
  };

  /**
   * Reads the configured USDC Stellar Asset Contract address.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The fee asset address.
   *
   * # Errors
   * Fails when configuration is unavailable.
   */
  readonly getFeeAsset: TreasuryMethod<"get_fee_asset"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetFeeAsset, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetFeeAsset,
      }),
  };

  /**
   * Changes all VNTY distribution portions atomically.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `beneficiary_bps` - Beneficiary portion.
   * * `cashback_bps` - Payer reward portion.
   * * `appreciation_bps` - Non-minting portion.
   * * `operator` - Authorized RBAC Admin.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects portions not summing to 10000 or unauthorized callers.
   */
  readonly setFeeSplit: TreasuryMethod<"set_fee_split"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetFeeSplit, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetFeeSplit,
      }),
  };

  /**
   * Reads a holder's optional redemption commitment.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Holder to inspect.
   *
   * # Returns
   * The commitment, if present.
   *
   * # Errors
   * Storage decoding errors propagate.
   */
  readonly getRedemption: TreasuryMethod<"get_redemption"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetRedemption, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetRedemption,
      }),
  };

  /**
   * Pauses one configured strategy through the DeFindex vault.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates DeFindex
   * failures.
   */
  readonly pauseStrategy: TreasuryMethod<"pause_strategy"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.PauseStrategy, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.PauseStrategy,
      }),
  };

  /**
   * Estimates cashback VNTY using current guarded net position value.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `amount` - Positive cash fee in USDC base units.
   *
   * # Returns
   * Estimated cashback shares; actual deposit rounding can reduce issuance.
   *
   * # Errors
   * Rejects unavailable net NAV, invalid amounts, or zero positive share
   * issuance.
   */
  readonly previewShares: TreasuryMethod<"preview_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.PreviewShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.PreviewShares,
      }),
  };

  /**
   * Refreshes reports for the configured DeFindex vault.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers and propagates DeFindex reporting failures.
   */
  readonly reportDefindex: TreasuryMethod<"report_defindex"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReportDefindex, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReportDefindex,
      }),
  };

  /**
   * Rescues one configured strategy into the DeFindex vault.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates DeFindex
   * failures.
   */
  readonly rescueStrategy: TreasuryMethod<"rescue_strategy"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.RescueStrategy, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.RescueStrategy,
      }),
  };

  /**
   * Changes the VNTY beneficiary without changing DeFindex's fee receiver.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `beneficiary` - New VNTY recipient, authorizing any missing trustline.
   * * `operator` - Authorized RBAC Admin.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unavailable recipient trust.
   */
  readonly setBeneficiary: TreasuryMethod<"set_beneficiary"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetBeneficiary, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetBeneficiary,
      }),
  };

  /**
   * Reads accounted VNTY supply, including committed shares.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The current VNTY base-unit supply.
   *
   * # Errors
   * Storage decoding errors propagate.
   */
  readonly getTotalShares: TreasuryMethod<"get_total_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetTotalShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetTotalShares,
      }),
  };

  /**
   * Unpauses one configured strategy through the DeFindex vault.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates DeFindex
   * failures.
   */
  readonly unpauseStrategy: TreasuryMethod<"unpause_strategy"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.UnpauseStrategy, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.UnpauseStrategy,
      }),
  };

  /**
   * Upgrades the configured DeFindex vault, not this Treasury contract.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed replacement DeFindex Wasm hash.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers and propagates the vault's upgrade failures.
   */
  readonly upgradeDefindex: TreasuryMethod<"upgrade_defindex"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.UpgradeDefindex, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.UpgradeDefindex,
      }),
  };

  /**
   * Returns committed VNTY even while paused or markets are unavailable.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Authorized commitment owner.
   *
   * # Returns
   * The cancelled commitment.
   *
   * # Errors
   * Rejects missing commitments, authorization failure, or VNTY
   * transfer/trustline failure.
   */
  readonly cancelRedemption: TreasuryMethod<"cancel_redemption"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CancelRedemption, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CancelRedemption,
      }),
  };

  /**
   * Escrows VNTY for a fixed thirty-day redemption cooldown.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Authorized VNTY holder.
   * * `shares` - Positive VNTY base units to escrow.
   *
   * # Returns
   * The commitment and maturity timestamps.
   *
   * # Errors
   * Rejects a pause, existing commitment, insufficient shares, or zero dfToken
   * output.
   * Fails with `TreasuryError::InvalidShareTransfer` unless existing VNTY
   * moves into escrow.
   */
  readonly commitRedemption: TreasuryMethod<"commit_redemption"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CommitRedemption, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CommitRedemption,
      }),
  };

  /**
   * Reports guarded net-valuation availability, not an amount-specific swap
   * guarantee.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * Healthy or DefindexUnavailable; direct oracle metadata is unset.
   *
   * # Errors
   * Missing Treasury configuration fails; external valuation failures become
   * status.
   */
  readonly getMarketHealth: TreasuryMethod<"get_market_health"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetMarketHealth, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetMarketHealth,
      }),
  };

  /**
   * Locks accrued fees before optionally changing the future DeFindex fee
   * rate.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `new_fee_bps` - Optional future fee rate in basis points.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or rates above 10000 and propagates DeFindex
   * failures.
   */
  readonly lockDefindexFees: TreasuryMethod<"lock_defindex_fees"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.LockDefindexFees, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.LockDefindexFees,
      }),
  };

  /**
   * Previews a balance-only dfToken exit, without promising cash liquidity.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `shares` - Positive VNTY base units.
   *
   * # Returns
   * A single dfToken amount, using current balances.
   *
   * # Errors
   * Rejects invalid share supply or invalid token balances.
   */
  readonly previewRedemption: TreasuryMethod<"preview_redemption"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.PreviewRedemption, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.PreviewRedemption,
      }),
  };

  /**
   * Quotes the minimum VNTY needed for an exact fee credit at current guarded
   * NAV.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `fee_credit` - Positive fee-asset credit to purchase with VNTY.
   *
   * # Returns
   * Minimum VNTY in atomic units, rounded upward.
   *
   * # Errors
   * Rejects invalid credit, unavailable NAV, overflow, or a burn exhausting
   * supply.
   */
  readonly getFeeSharesQuote: TreasuryMethod<"get_fee_shares_quote"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetFeeSharesQuote, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetFeeSharesQuote,
      }),
  };

  /**
   * Changes one configured StableBond strategy's pricing safety parameters.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `max_spread_bps` - Maximum oracle-to-market spread in basis points.
   * * `quote_ttl_seconds` - Maximum quote age in seconds.
   * * `slippage_bps` - Maximum execution slippage in basis points.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * validation failures.
   */
  readonly setStrategyPricing: TreasuryMethod<"set_strategy_pricing"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetStrategyPricing, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetStrategyPricing,
      }),
  };

  /**
   * Changes one configured StableBond strategy's total-value cap.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `amount` - Nonnegative cap in fee-asset base units.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers, unknown strategies, or negative amounts and
   * propagates strategy failures.
   */
  readonly setStrategyTvlCap: TreasuryMethod<"set_strategy_tvl_cap"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetStrategyTvlCap, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetStrategyTvlCap,
      }),
  };

  /**
   * Accepts keeper authority for one configured StableBond strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `operator` - Authorized RBAC Treasurer; the previous keeper must also
   * authorize.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates
   * keeper-handover failures.
   */
  readonly claimStrategyKeeper: TreasuryMethod<"claim_strategy_keeper"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ClaimStrategyKeeper, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ClaimStrategyKeeper,
      }),
  };

  /**
   * Releases locked DeFindex fees for one configured strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `amount` - Nonnegative amount of locked fees to release.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers, unknown strategies, or negative amounts and
   * propagates DeFindex failures.
   */
  readonly releaseDefindexFees: TreasuryMethod<"release_defindex_fees"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReleaseDefindexFees, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReleaseDefindexFees,
      }),
  };

  /**
   * Allows one depositor on a configured StableBond strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `depositor` - Address to allow.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * failures.
   */
  readonly addStrategyDepositor: TreasuryMethod<"add_strategy_depositor"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.AddStrategyDepositor, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.AddStrategyDepositor,
      }),
  };

  /**
   * Collects a protocol fee with bounded VNTY spending and atomic change.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `payer` - Authorizes the fee, maximum VNTY transfer, and fixed cash
   * remainder.
   * * `amount` - Complete protocol fee in fee-asset atomic units.
   * * `payment` - Expected fee, exact VNTY fee credit, maximum shares, and
   * exclusive Unix deadline.
   *
   * # Returns
   * Actual shares burned, exact fee credit, cash collected, and reward
   * accounting.
   *
   * # Errors
   * Rejects expired payments, changed fees, invalid coverage, exceeded share
   * limits,
   * unavailable NAV, final-share burns, issuer-created shares, pause, or
   * missing authorization.
   * Propagates token, strategy deposit, reward issuance, and accounting
   * errors.
   */
  readonly collectFeeWithLimit: TreasuryMethod<"collect_fee_with_limit"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CollectFeeWithLimit, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CollectFeeWithLimit,
      }),
  };

  /**
   * Moves all Treasury backing into an empty replacement vault while paused.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `new_vault` - Empty single-USDC vault managed by this Treasury.
   * * `allocations` - Complete target strategy set and buy-only weights.
   * * `min_usdc` - Minimum measured USDC received from the old position.
   * * `min_new_shares` - Minimum new dfTokens after deposit and initialization
   * rounding.
   * * `operator` - Current RBAC Treasurer authorizing the one-time backing
   * movement.
   *
   * # Returns
   * Actual old shares redeemed, USDC moved, and new shares received.
   *
   * # Errors
   * Requires pause, zero escrowed VNTY, valid empty managed target, valid
   * allocations,
   * sufficient measured output, and successful dependency execution. Failure
   * is atomic.
   */
  readonly migrateDefindexVault: TreasuryMethod<"migrate_defindex_vault"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.MigrateDefindexVault, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.MigrateDefindexVault,
      }),
  };

  /**
   * Burns VNTY toward a fee and deposits only its uncovered cash remainder.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `payer` - Authorized payer.
   * * `amount` - Positive nominal USDC fee.
   * * `fee_shares` - Nonnegative VNTY base units to burn.
   *
   * # Returns
   * The cash, burn, deposit, and reward accounting receipt.
   *
   * # Errors
   * Rejects overpayment, unavailable guarded NAV even for share-only fees, or
   * any error from collect_fee.
   */
  readonly collectFeeWithShares: TreasuryMethod<"collect_fee_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CollectFeeWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CollectFeeWithShares,
      }),
  };

  /**
   * Distributes locked fees under the configured DeFindex fee policy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers and propagates DeFindex distribution
   * failures.
   */
  readonly distributeDefindexFees: TreasuryMethod<"distribute_defindex_fees"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.DistributeDefindexFees,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.DistributeDefindexFees,
        }),
    };

  /**
   * Changes investment targets without buying, selling, or replacing the
   * vault.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `allocations` - Exact configured vault strategies with weights totaling
   * 10000.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects mismatched, duplicate, excessive, or invalid targets and
   * unauthorized callers.
   */
  readonly setStrategyAllocations: TreasuryMethod<"set_strategy_allocations"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.SetStrategyAllocations,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.SetStrategyAllocations,
        }),
    };

  /**
   * Changes one configured StableBond strategy's per-deposit cap.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `amount` - Nonnegative cap in fee-asset base units.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers, unknown strategies, or negative amounts and
   * propagates strategy failures.
   */
  readonly setStrategyDepositCap: TreasuryMethod<"set_strategy_deposit_cap"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetStrategyDepositCap, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetStrategyDepositCap,
      }),
  };

  /**
   * Allows one depositor Wasm hash on a configured StableBond strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `hash` - Wasm hash to allow.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * failures.
   */
  readonly addStrategyAllowedHash: TreasuryMethod<"add_strategy_allowed_hash"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.AddStrategyAllowedHash,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.AddStrategyAllowedHash,
        }),
    };

  /**
   * Reads the immutable virtual offsets used by this Treasury instance.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * USDC and VNTY offsets in their respective base units, including legacy
   * defaults.
   *
   * # Errors
   * Propagates storage or TTL renewal failures.
   */
  readonly getAccountingParameters: TreasuryMethod<
    "get_accounting_parameters"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.GetAccountingParameters,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetAccountingParameters,
      }),
  };

  /**
   * Removes one depositor from a configured StableBond strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `depositor` - Address to remove.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * failures.
   */
  readonly removeStrategyDepositor: TreasuryMethod<
    "remove_strategy_depositor"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.RemoveStrategyDepositor,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.RemoveStrategyDepositor,
      }),
  };

  /**
   * Changes the configured DeFindex vault's performance-fee receiver.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `receiver` - New fee receiver.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers and propagates DeFindex configuration
   * failures.
   */
  readonly setDefindexFeeReceiver: TreasuryMethod<"set_defindex_fee_receiver"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.SetDefindexFeeReceiver,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.SetDefindexFeeReceiver,
        }),
    };

  /**
   * Replaces Testnet settlement and vault backing at an exact one-for-one
   * exchange.
   *
   * Requires the Testnet network, Treasurer authorization, pause, zero claim
   * escrow,
   * an empty Treasury-managed vault and measured minimum proceeds/shares. The
   * operator supplies the new SAC currency and receives the old currency.
   * Existing
   * VNTY supply, offsets and direct Treasury donations retain their
   * denomination.
   *
   * # Arguments
   * * `e` - Contract environment.
   * * `new_vault` - Empty Treasury-managed replacement vault.
   * * `allocations` - Complete replacement strategy weights.
   * * `min_usdc` - Minimum measured old vault proceeds.
   * * `min_new_shares` - Minimum measured new vault shares.
   * * `operator` - Authorized Treasurer supplying the replacement currency.
   * * `new_asset` - New seven-decimal Stellar Asset Contract.
   *
   * # Returns
   * Measured old and new vault backing amounts.
   *
   * # Errors
   * Rejects other networks, missing authorization, unpaused state, pending
   * escrow,
   * incompatible vaults/assets, insufficient exchange funds and unmet minima.
   */
  readonly migrateTestnetSettlement: TreasuryMethod<
    "migrate_testnet_settlement"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.MigrateTestnetSettlement,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.MigrateTestnetSettlement,
      }),
  };

  /**
   * Removes one depositor Wasm hash from a configured StableBond strategy.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `hash` - Wasm hash to remove.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * failures.
   */
  readonly removeStrategyAllowedHash: TreasuryMethod<
    "remove_strategy_allowed_hash"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.RemoveStrategyAllowedHash,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.RemoveStrategyAllowedHash,
      }),
  };

  /**
   * Changes whether one configured StableBond strategy accepts deposits.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `strategy` - Configured strategy address.
   * * `paused` - New deposit-pause state.
   * * `operator` - Authorized RBAC Treasurer.
   *
   * # Returns
   * Nothing.
   *
   * # Errors
   * Rejects unauthorized callers or unknown strategies and propagates strategy
   * failures.
   */
  readonly setStrategyDepositsPaused: TreasuryMethod<
    "set_strategy_deposits_paused"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.SetStrategyDepositsPaused,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetStrategyDepositsPaused,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = TreasuryErrors, ...args }: TreasuryConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(
          TreasurySpec.entries.map((entry) => entry.toXdr("base64")),
        ),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): TreasuryEvents {
    return super.events as TreasuryEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof TreasuryMethodMap>(
    args: TreasuryCall<Method>,
  ): Promise<TreasuryOutputs[Method]> {
    return await super.read(args) as TreasuryOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof TreasuryMethodMap>(
    args: TreasuryCall<Method> & TreasuryInvocation,
  ): Promise<TreasuryInvocationResult<TreasuryOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<TreasuryOutputs[Method]>(
      args.method,
      result,
    );
  }
}
