// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Treasury contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { TreasurySpec } from "@/contracts/treasury/constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Pauses new fee collection, commitments, and investment, not mature exits.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `operator` - Authorized RBAC Admin.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or invalid pause transitions.
 */
export type PauseInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of pause. */
export type PauseOutput = null;

/**
 * Burns mature VNTY and transfers dfTokens without market valuation.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Authorized commitment owner.
 *
 * # Returns
 * The VNTY burned, dfTokens transferred, and timestamps.
 *
 * # Errors
 * Rejects missing or immature commitments, zero output, invalid share
 * administration, or token transfer failure.
 */
export type RedeemInput = {
  owner: SorobanType.Input.Address;
};

/** Decoded return value of redeem. */
export type RedeemOutput = RedemptionReceipt;

/**
 * Resumes new fee collection, commitments, and investment.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `operator` - Authorized RBAC Admin.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or invalid pause transitions.
 */
export type UnpauseInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of unpause. */
export type UnpauseOutput = null;

/**
 * Replaces Treasury code; migrating legacy direct-asset storage is not
 * supported.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed compatible replacement Wasm.
 * * `operator` - Authorized RBAC Upgrader.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unavailable Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Invests live idle USDC toward existing whole-vault strategy shortfalls.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `amount` - Maximum USDC base units; zero uses all execution-time idle
 * cash.
 * * `operator` - Authorized RBAC Rebalancer.
 *
 * # Returns
 * Executed USDC budget and per-strategy investment instructions.
 *
 * # Errors
 * Rejects negative budgets, pause, unhealthy NAV, paused targets, or any
 * underlying investment failure; the whole batch rolls back.
 */
export type RebalanceInput = {
  amount: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of rebalance. */
export type RebalanceOutput = RebalanceReceipt;

/**
 * Reads the Treasury's vault and distribution configuration.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The stored configuration.
 *
 * # Errors
 * Fails when configuration is absent or incompatible.
 */
export type GetConfigInput = Record<string, never>;

/** Decoded return value of get_config. */
export type GetConfigOutput = TreasuryConfig;

/**
 * Reads whether new fees, commitments, and investment are paused.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The current pause flag.
 *
 * # Errors
 * Storage decoding errors propagate.
 */
export type GetPausedInput = Record<string, never>;

/** Decoded return value of get_paused. */
export type GetPausedOutput = SorobanType.Bool;

/**
 * Deposits a cash fee idle in DeFindex and issues VNTY rewards.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `payer` - Authorized payer.
 * * `amount` - Positive fee in USDC base units.
 *
 * # Returns
 * The actual retained value, dfTokens received, and VNTY issued.
 *
 * # Errors
 * Fails while paused, on unavailable net NAV, invalid deposit output, zero
 * share mint, transfer, or authorization failure.
 */
export type CollectFeeInput = {
  payer: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
};

/** Decoded return value of collect_fee. */
export type CollectFeeOutput = FeeReceipt;

/**
 * Values only Treasury's dfToken position, including idle USDC inside
 * DeFindex.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * A single dfToken position, net USDC NAV, issued VNTY, and virtual share
 * price.
 *
 * # Errors
 * Fails if guarded DeFindex valuation is unavailable or accounting
 * overflows.
 */
export type GetSnapshotInput = Record<string, never>;

/** Decoded return value of get_snapshot. */
export type GetSnapshotOutput = TreasurySnapshot;

/**
 * Initializes a dedicated single-USDC DeFindex Treasury.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `config` - Vault, strategies, VNTY asset, RBAC and distribution
 * settings.
 * * `operator` - Authorized RBAC Admin.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects invalid assets, vault strategy membership, fee splits, or
 * unauthorized setup. Share SAC administration is transferred separately.
 */
export type ConstructorInput = {
  config: TreasuryConfigArgs;
  operator: SorobanType.Input.Address;
};

/**
 * Reads the configured USDC Stellar Asset Contract address.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The fee asset address.
 *
 * # Errors
 * Fails when configuration is unavailable.
 */
export type GetFeeAssetInput = Record<string, never>;

/** Decoded return value of get_fee_asset. */
export type GetFeeAssetOutput = SorobanType.Address;

/**
 * Changes all VNTY distribution portions atomically.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `beneficiary_bps` - Beneficiary portion.
 * * `cashback_bps` - Payer reward portion.
 * * `appreciation_bps` - Non-minting portion.
 * * `operator` - Authorized RBAC Admin.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects portions not summing to 10000 or unauthorized callers.
 */
export type SetFeeSplitInput = {
  beneficiary_bps: SorobanType.Input.U32;
  cashback_bps: SorobanType.Input.U32;
  appreciation_bps: SorobanType.Input.U32;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_fee_split. */
export type SetFeeSplitOutput = null;

/**
 * Reads a holder's optional redemption commitment.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Holder to inspect.
 *
 * # Returns
 * The commitment, if present.
 *
 * # Errors
 * Storage decoding errors propagate.
 */
export type GetRedemptionInput = {
  owner: SorobanType.Input.Address;
};

/** Decoded return value of get_redemption. */
export type GetRedemptionOutput = SorobanType.Option<RedemptionRequest>;

/**
 * Pauses one configured strategy through the DeFindex vault.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates DeFindex
 * failures.
 */
export type PauseStrategyInput = {
  strategy: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of pause_strategy. */
export type PauseStrategyOutput = null;

/**
 * Estimates cashback VNTY using current guarded net position value.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `amount` - Positive cash fee in USDC base units.
 *
 * # Returns
 * Estimated cashback shares; actual deposit rounding can reduce issuance.
 *
 * # Errors
 * Rejects unavailable net NAV, invalid amounts, or zero positive share
 * issuance.
 */
export type PreviewSharesInput = {
  amount: SorobanType.Input.I128;
};

/** Decoded return value of preview_shares. */
export type PreviewSharesOutput = SorobanType.I128;

/**
 * Refreshes reports for the configured DeFindex vault.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers and propagates DeFindex reporting failures.
 */
export type ReportDefindexInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of report_defindex. */
export type ReportDefindexOutput = null;

/**
 * Rescues one configured strategy into the DeFindex vault.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates DeFindex
 * failures.
 */
export type RescueStrategyInput = {
  strategy: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of rescue_strategy. */
export type RescueStrategyOutput = null;

/**
 * Changes the VNTY beneficiary without changing DeFindex's fee receiver.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `beneficiary` - New VNTY recipient, authorizing any missing trustline.
 * * `operator` - Authorized RBAC Admin.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unavailable recipient trust.
 */
export type SetBeneficiaryInput = {
  beneficiary: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_beneficiary. */
export type SetBeneficiaryOutput = null;

/**
 * Reads accounted VNTY supply, including committed shares.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The current VNTY base-unit supply.
 *
 * # Errors
 * Storage decoding errors propagate.
 */
export type GetTotalSharesInput = Record<string, never>;

/** Decoded return value of get_total_shares. */
export type GetTotalSharesOutput = SorobanType.I128;

/**
 * Unpauses one configured strategy through the DeFindex vault.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates DeFindex
 * failures.
 */
export type UnpauseStrategyInput = {
  strategy: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of unpause_strategy. */
export type UnpauseStrategyOutput = null;

/**
 * Upgrades the configured DeFindex vault, not this Treasury contract.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed replacement DeFindex Wasm hash.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers and propagates the vault's upgrade failures.
 */
export type UpgradeDefindexInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade_defindex. */
export type UpgradeDefindexOutput = null;

/**
 * Returns committed VNTY even while paused or markets are unavailable.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Authorized commitment owner.
 *
 * # Returns
 * The cancelled commitment.
 *
 * # Errors
 * Rejects missing commitments, authorization failure, or VNTY
 * transfer/trustline failure.
 */
export type CancelRedemptionInput = {
  owner: SorobanType.Input.Address;
};

/** Decoded return value of cancel_redemption. */
export type CancelRedemptionOutput = RedemptionRequest;

/**
 * Escrows VNTY for a fixed thirty-day redemption cooldown.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Authorized VNTY holder.
 * * `shares` - Positive VNTY base units to escrow.
 *
 * # Returns
 * The commitment and maturity timestamps.
 *
 * # Errors
 * Rejects a pause, existing commitment, insufficient shares, or zero dfToken
 * output.
 * Fails with `TreasuryError::InvalidShareTransfer` unless existing VNTY
 * moves into escrow.
 */
export type CommitRedemptionInput = {
  owner: SorobanType.Input.Address;
  shares: SorobanType.Input.I128;
};

/** Decoded return value of commit_redemption. */
export type CommitRedemptionOutput = RedemptionRequest;

/**
 * Reports guarded net-valuation availability, not an amount-specific swap
 * guarantee.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * Healthy or DefindexUnavailable; direct oracle metadata is unset.
 *
 * # Errors
 * Missing Treasury configuration fails; external valuation failures become
 * status.
 */
export type GetMarketHealthInput = Record<string, never>;

/** Decoded return value of get_market_health. */
export type GetMarketHealthOutput = MarketHealth;

/**
 * Locks accrued fees before optionally changing the future DeFindex fee
 * rate.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `new_fee_bps` - Optional future fee rate in basis points.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or rates above 10000 and propagates DeFindex
 * failures.
 */
export type LockDefindexFeesInput = {
  new_fee_bps: SorobanType.Input.Option<SorobanType.Input.U32, SorobanType.U32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of lock_defindex_fees. */
export type LockDefindexFeesOutput = null;

/**
 * Previews a balance-only dfToken exit, without promising cash liquidity.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `shares` - Positive VNTY base units.
 *
 * # Returns
 * A single dfToken amount, using current balances.
 *
 * # Errors
 * Rejects invalid share supply or invalid token balances.
 */
export type PreviewRedemptionInput = {
  shares: SorobanType.Input.I128;
};

/** Decoded return value of preview_redemption. */
export type PreviewRedemptionOutput = SorobanType.Vec<StrategyRedemption>;

/**
 * Quotes the minimum VNTY needed for an exact fee credit at current guarded
 * NAV.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `fee_credit` - Positive fee-asset credit to purchase with VNTY.
 *
 * # Returns
 * Minimum VNTY in atomic units, rounded upward.
 *
 * # Errors
 * Rejects invalid credit, unavailable NAV, overflow, or a burn exhausting
 * supply.
 */
export type GetFeeSharesQuoteInput = {
  fee_credit: SorobanType.Input.I128;
};

/** Decoded return value of get_fee_shares_quote. */
export type GetFeeSharesQuoteOutput = SorobanType.I128;

/**
 * Changes one configured DeFindex strategy's pricing safety parameters.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `max_spread_bps` - Maximum oracle-to-market spread in basis points.
 * * `quote_ttl_seconds` - Maximum quote age in seconds.
 * * `slippage_bps` - Maximum execution slippage in basis points.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * validation failures.
 */
export type SetStrategyPricingInput = {
  strategy: SorobanType.Input.Address;
  max_spread_bps: SorobanType.Input.U32;
  quote_ttl_seconds: SorobanType.Input.U64;
  slippage_bps: SorobanType.Input.U32;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_strategy_pricing. */
export type SetStrategyPricingOutput = null;

/**
 * Changes one configured DeFindex strategy's total-value cap.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `amount` - Nonnegative cap in fee-asset base units.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers, unknown strategies, or negative amounts and
 * propagates strategy failures.
 */
export type SetStrategyTvlCapInput = {
  strategy: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_strategy_tvl_cap. */
export type SetStrategyTvlCapOutput = null;

/**
 * Accepts keeper authority for one configured DeFindex strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `operator` - Authorized RBAC Treasurer; the previous keeper must also
 * authorize.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates
 * keeper-handover failures.
 */
export type ClaimStrategyKeeperInput = {
  strategy: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of claim_strategy_keeper. */
export type ClaimStrategyKeeperOutput = null;

/**
 * Releases locked DeFindex fees for one configured strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `amount` - Nonnegative amount of locked fees to release.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers, unknown strategies, or negative amounts and
 * propagates DeFindex failures.
 */
export type ReleaseDefindexFeesInput = {
  strategy: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of release_defindex_fees. */
export type ReleaseDefindexFeesOutput = null;

/**
 * Allows one depositor on a configured DeFindex strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `depositor` - Address to allow.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * failures.
 */
export type AddStrategyDepositorInput = {
  strategy: SorobanType.Input.Address;
  depositor: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of add_strategy_depositor. */
export type AddStrategyDepositorOutput = null;

/**
 * Collects a protocol fee with bounded VNTY spending and atomic change.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `payer` - Authorizes the fee, maximum VNTY transfer, and fixed cash
 * remainder.
 * * `amount` - Complete protocol fee in fee-asset atomic units.
 * * `payment` - Expected fee, exact VNTY fee credit, maximum shares, and
 * exclusive Unix deadline.
 *
 * # Returns
 * Actual shares burned, exact fee credit, cash collected, and reward
 * accounting.
 *
 * # Errors
 * Rejects expired payments, changed fees, invalid coverage, exceeded share
 * limits,
 * unavailable NAV, final-share burns, issuer-created shares, pause, or
 * missing authorization.
 * Propagates token, strategy deposit, reward issuance, and accounting
 * errors.
 */
export type CollectFeeWithLimitInput = {
  payer: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
  payment: VntyPaymentLimitArgs;
};

/** Decoded return value of collect_fee_with_limit. */
export type CollectFeeWithLimitOutput = FeeReceipt;

/**
 * Moves all Treasury backing into an empty replacement vault while paused.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `new_vault` - Empty single-USDC vault managed by this Treasury.
 * * `allocations` - Complete target strategy set and buy-only weights.
 * * `min_usdc` - Minimum measured USDC received from the old position.
 * * `min_new_shares` - Minimum new dfTokens after deposit and initialization
 * rounding.
 * * `operator` - Current RBAC Treasurer authorizing the one-time backing
 * movement.
 *
 * # Returns
 * Actual old shares redeemed, USDC moved, and new shares received.
 *
 * # Errors
 * Requires pause, zero pending redemption liabilities, a valid empty managed
 * target and allocations,
 * sufficient measured output, and successful dependency execution. Failure
 * is atomic.
 */
export type MigrateDefindexVaultInput = {
  new_vault: SorobanType.Input.Address;
  allocations: SorobanType.Input.Vec<
    StrategyAllocationArgs,
    StrategyAllocation
  >;
  min_usdc: SorobanType.Input.I128;
  min_new_shares: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of migrate_defindex_vault. */
export type MigrateDefindexVaultOutput = VaultMigrationReceipt;

/**
 * Burns VNTY toward a fee and deposits only its uncovered cash remainder.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `payer` - Authorized payer.
 * * `amount` - Positive nominal USDC fee.
 * * `fee_shares` - Nonnegative VNTY base units to burn.
 *
 * # Returns
 * The cash, burn, deposit, and reward accounting receipt.
 *
 * # Errors
 * Rejects overpayment, unavailable guarded NAV even for share-only fees, or
 * any error from collect_fee.
 */
export type CollectFeeWithSharesInput = {
  payer: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of collect_fee_with_shares. */
export type CollectFeeWithSharesOutput = FeeReceipt;

/**
 * Distributes locked fees under the configured DeFindex fee policy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers and propagates DeFindex distribution
 * failures.
 */
export type DistributeDefindexFeesInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of distribute_defindex_fees. */
export type DistributeDefindexFeesOutput = null;

/**
 * Changes investment targets without buying, selling, or replacing the
 * vault.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `allocations` - Exact configured vault strategies with weights totaling
 * 10000.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects mismatched, duplicate, excessive, or invalid targets and
 * unauthorized callers.
 */
export type SetStrategyAllocationsInput = {
  allocations: SorobanType.Input.Vec<
    StrategyAllocationArgs,
    StrategyAllocation
  >;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_strategy_allocations. */
export type SetStrategyAllocationsOutput = null;

/**
 * Changes one configured DeFindex strategy's per-deposit cap.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `amount` - Nonnegative cap in fee-asset base units.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers, unknown strategies, or negative amounts and
 * propagates strategy failures.
 */
export type SetStrategyDepositCapInput = {
  strategy: SorobanType.Input.Address;
  amount: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_strategy_deposit_cap. */
export type SetStrategyDepositCapOutput = null;

/**
 * Allows one depositor Wasm hash on a configured DeFindex strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `hash` - Wasm hash to allow.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * failures.
 */
export type AddStrategyAllowedHashInput = {
  strategy: SorobanType.Input.Address;
  hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of add_strategy_allowed_hash. */
export type AddStrategyAllowedHashOutput = null;

/**
 * Reads the immutable virtual offsets used by this Treasury instance.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * USDC and VNTY offsets in their respective base units, including legacy
 * defaults.
 *
 * # Errors
 * Propagates storage or TTL renewal failures.
 */
export type GetAccountingParametersInput = Record<string, never>;

/** Decoded return value of get_accounting_parameters. */
export type GetAccountingParametersOutput = AccountingParameters;

/**
 * Removes one depositor from a configured DeFindex strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `depositor` - Address to remove.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * failures.
 */
export type RemoveStrategyDepositorInput = {
  strategy: SorobanType.Input.Address;
  depositor: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of remove_strategy_depositor. */
export type RemoveStrategyDepositorOutput = null;

/**
 * Changes the configured DeFindex vault's performance-fee receiver.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `receiver` - New fee receiver.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers and propagates DeFindex configuration
 * failures.
 */
export type SetDefindexFeeReceiverInput = {
  receiver: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_defindex_fee_receiver. */
export type SetDefindexFeeReceiverOutput = null;

/**
 * Removes one depositor Wasm hash from a configured DeFindex strategy.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `hash` - Wasm hash to remove.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * failures.
 */
export type RemoveStrategyAllowedHashInput = {
  strategy: SorobanType.Input.Address;
  hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of remove_strategy_allowed_hash. */
export type RemoveStrategyAllowedHashOutput = null;

/**
 * Changes whether one configured DeFindex strategy accepts deposits.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `strategy` - Configured strategy address.
 * * `paused` - New deposit-pause state.
 * * `operator` - Authorized RBAC Treasurer.
 *
 * # Returns
 * Nothing.
 *
 * # Errors
 * Rejects unauthorized callers or unknown strategies and propagates strategy
 * failures.
 */
export type SetStrategyDepositsPausedInput = {
  strategy: SorobanType.Input.Address;
  paused: SorobanType.Input.Bool;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_strategy_deposits_paused. */
export type SetStrategyDepositsPausedOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type TreasuryMethodMap = {
  pause: {
    input: PauseInput;
    output: PauseOutput;
  };
  redeem: {
    input: RedeemInput;
    output: RedeemOutput;
  };
  unpause: {
    input: UnpauseInput;
    output: UnpauseOutput;
  };
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  rebalance: {
    input: RebalanceInput;
    output: RebalanceOutput;
  };
  get_config: {
    input: GetConfigInput;
    output: GetConfigOutput;
  };
  get_paused: {
    input: GetPausedInput;
    output: GetPausedOutput;
  };
  collect_fee: {
    input: CollectFeeInput;
    output: CollectFeeOutput;
  };
  get_snapshot: {
    input: GetSnapshotInput;
    output: GetSnapshotOutput;
  };
  get_fee_asset: {
    input: GetFeeAssetInput;
    output: GetFeeAssetOutput;
  };
  set_fee_split: {
    input: SetFeeSplitInput;
    output: SetFeeSplitOutput;
  };
  get_redemption: {
    input: GetRedemptionInput;
    output: GetRedemptionOutput;
  };
  pause_strategy: {
    input: PauseStrategyInput;
    output: PauseStrategyOutput;
  };
  preview_shares: {
    input: PreviewSharesInput;
    output: PreviewSharesOutput;
  };
  report_defindex: {
    input: ReportDefindexInput;
    output: ReportDefindexOutput;
  };
  rescue_strategy: {
    input: RescueStrategyInput;
    output: RescueStrategyOutput;
  };
  set_beneficiary: {
    input: SetBeneficiaryInput;
    output: SetBeneficiaryOutput;
  };
  get_total_shares: {
    input: GetTotalSharesInput;
    output: GetTotalSharesOutput;
  };
  unpause_strategy: {
    input: UnpauseStrategyInput;
    output: UnpauseStrategyOutput;
  };
  upgrade_defindex: {
    input: UpgradeDefindexInput;
    output: UpgradeDefindexOutput;
  };
  cancel_redemption: {
    input: CancelRedemptionInput;
    output: CancelRedemptionOutput;
  };
  commit_redemption: {
    input: CommitRedemptionInput;
    output: CommitRedemptionOutput;
  };
  get_market_health: {
    input: GetMarketHealthInput;
    output: GetMarketHealthOutput;
  };
  lock_defindex_fees: {
    input: LockDefindexFeesInput;
    output: LockDefindexFeesOutput;
  };
  preview_redemption: {
    input: PreviewRedemptionInput;
    output: PreviewRedemptionOutput;
  };
  get_fee_shares_quote: {
    input: GetFeeSharesQuoteInput;
    output: GetFeeSharesQuoteOutput;
  };
  set_strategy_pricing: {
    input: SetStrategyPricingInput;
    output: SetStrategyPricingOutput;
  };
  set_strategy_tvl_cap: {
    input: SetStrategyTvlCapInput;
    output: SetStrategyTvlCapOutput;
  };
  claim_strategy_keeper: {
    input: ClaimStrategyKeeperInput;
    output: ClaimStrategyKeeperOutput;
  };
  release_defindex_fees: {
    input: ReleaseDefindexFeesInput;
    output: ReleaseDefindexFeesOutput;
  };
  add_strategy_depositor: {
    input: AddStrategyDepositorInput;
    output: AddStrategyDepositorOutput;
  };
  collect_fee_with_limit: {
    input: CollectFeeWithLimitInput;
    output: CollectFeeWithLimitOutput;
  };
  migrate_defindex_vault: {
    input: MigrateDefindexVaultInput;
    output: MigrateDefindexVaultOutput;
  };
  collect_fee_with_shares: {
    input: CollectFeeWithSharesInput;
    output: CollectFeeWithSharesOutput;
  };
  distribute_defindex_fees: {
    input: DistributeDefindexFeesInput;
    output: DistributeDefindexFeesOutput;
  };
  set_strategy_allocations: {
    input: SetStrategyAllocationsInput;
    output: SetStrategyAllocationsOutput;
  };
  set_strategy_deposit_cap: {
    input: SetStrategyDepositCapInput;
    output: SetStrategyDepositCapOutput;
  };
  add_strategy_allowed_hash: {
    input: AddStrategyAllowedHashInput;
    output: AddStrategyAllowedHashOutput;
  };
  get_accounting_parameters: {
    input: GetAccountingParametersInput;
    output: GetAccountingParametersOutput;
  };
  remove_strategy_depositor: {
    input: RemoveStrategyDepositorInput;
    output: RemoveStrategyDepositorOutput;
  };
  set_defindex_fee_receiver: {
    input: SetDefindexFeeReceiverInput;
    output: SetDefindexFeeReceiverOutput;
  };
  remove_strategy_allowed_hash: {
    input: RemoveStrategyAllowedHashInput;
    output: RemoveStrategyAllowedHashOutput;
  };
  set_strategy_deposits_paused: {
    input: SetStrategyDepositsPausedInput;
    output: SetStrategyDepositsPausedOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type TreasuryInputs = {
  [Method in keyof TreasuryMethodMap]: TreasuryMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type TreasuryOutputs = {
  [Method in keyof TreasuryMethodMap]: TreasuryMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type TreasuryCall<Method extends keyof TreasuryMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      TreasuryInputs[Name] extends Record<string, never>
        ? { methodArgs?: TreasuryInputs[Name] }
        : { methodArgs: TreasuryInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type TreasuryInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type TreasuryInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type TreasuryMethod<Method extends keyof TreasuryMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: TreasuryInputs[Method] extends Record<string, never>
      ? [methodArgs?: TreasuryInputs[Method]]
      : [methodArgs: TreasuryInputs[Method]]
  ) => Promise<TreasuryOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<TreasuryCall<Method>, "method"> & TreasuryInvocation,
  ) => Promise<TreasuryInvocationResult<TreasuryOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** The FeeReceipt type declared by the contract. */
export type FeeReceipt = SorobanType.Custom<{
  kind: "struct";
  fields: {
    appreciation_amount: SorobanType.I128;
    beneficiary_amount: SorobanType.I128;
    beneficiary_shares_minted: SorobanType.I128;
    cashback_amount: SorobanType.I128;
    cashback_shares_minted: SorobanType.I128;
    fee_amount: SorobanType.I128;
    fee_asset_collected: SorobanType.I128;
    fee_shares_burned: SorobanType.I128;
    fee_shares_value: SorobanType.I128;
    invested_amount: SorobanType.I128;
    payer: SorobanType.Address;
    realized_value: SorobanType.I128;
    strategy_investments: SorobanType.Vec<StrategyInvestment>;
    total_shares_minted: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the FeeReceipt factory. */
export type FeeReceiptArgs = SorobanType.Input.Custom<FeeReceipt>;

/** Validate, encode and decode FeeReceipt using its contract declaration. */
export const FeeReceipt: SorobanType.Factory<FeeReceipt> = SorobanType
  .Custom.fromSpec<FeeReceipt>(
    () => TreasurySpec,
    "FeeReceipt",
  );

/** The RouteHealth type declared by the contract. */
export type RouteHealth = SorobanType.Custom<{
  kind: "struct";
  fields: {
    amount_in: SorobanType.I128;
    deviation_bps: SorobanType.Option<SorobanType.U32>;
    input_asset: SorobanType.Address;
    oracle_amount_out: SorobanType.Option<SorobanType.I128>;
    output_asset: SorobanType.Address;
    router_amount_out: SorobanType.Option<SorobanType.I128>;
    slippage_bps: SorobanType.Option<SorobanType.U32>;
    status: MarketHealthStatus;
  };
}>;

/** Raw or validated values accepted by the RouteHealth factory. */
export type RouteHealthArgs = SorobanType.Input.Custom<RouteHealth>;

/** Validate, encode and decode RouteHealth using its contract declaration. */
export const RouteHealth: SorobanType.Factory<RouteHealth> = SorobanType
  .Custom.fromSpec<RouteHealth>(
    () => TreasurySpec,
    "RouteHealth",
  );

/** The MarketHealth type declared by the contract. */
export type MarketHealth = SorobanType.Custom<{
  kind: "struct";
  fields: {
    checked_at: SorobanType.U64;
    max_oracle_age_seconds: SorobanType.U64;
    oldest_price_timestamp: SorobanType.Option<SorobanType.U64>;
    probe_amount: SorobanType.I128;
    routes: SorobanType.Vec<RouteHealth>;
    status: MarketHealthStatus;
  };
}>;

/** Raw or validated values accepted by the MarketHealth factory. */
export type MarketHealthArgs = SorobanType.Input.Custom<MarketHealth>;

/** Validate, encode and decode MarketHealth using its contract declaration. */
export const MarketHealth: SorobanType.Factory<MarketHealth> = SorobanType
  .Custom.fromSpec<MarketHealth>(
    () => TreasurySpec,
    "MarketHealth",
  );

/** The TreasuryConfig type declared by the contract. */
export type TreasuryConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    appreciation_bps: SorobanType.U32;
    beneficiary: SorobanType.Address;
    beneficiary_bps: SorobanType.U32;
    cashback_bps: SorobanType.U32;
    defindex_vault: SorobanType.Address;
    fee_asset: SorobanType.Address;
    rbac: SorobanType.Address;
    share_asset: SorobanType.Address;
    strategies: SorobanType.Vec<StrategyAllocation>;
  };
}>;

/** Raw or validated values accepted by the TreasuryConfig factory. */
export type TreasuryConfigArgs = SorobanType.Input.Custom<TreasuryConfig>;

/** Validate, encode and decode TreasuryConfig using its contract declaration. */
export const TreasuryConfig: SorobanType.Factory<TreasuryConfig> = SorobanType
  .Custom.fromSpec<TreasuryConfig>(
    () => TreasurySpec,
    "TreasuryConfig",
  );

/** The RebalanceReceipt type declared by the contract. */
export type RebalanceReceipt = SorobanType.Custom<{
  kind: "struct";
  fields: {
    invested_amount: SorobanType.I128;
    investments: SorobanType.Vec<RebalanceInvestment>;
    requested_amount: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the RebalanceReceipt factory. */
export type RebalanceReceiptArgs = SorobanType.Input.Custom<RebalanceReceipt>;

/** Validate, encode and decode RebalanceReceipt using its contract declaration. */
export const RebalanceReceipt: SorobanType.Factory<RebalanceReceipt> =
  SorobanType
    .Custom.fromSpec<RebalanceReceipt>(
      () => TreasurySpec,
      "RebalanceReceipt",
    );

/** The StrategyPosition type declared by the contract. */
export type StrategyPosition = SorobanType.Custom<{
  kind: "struct";
  fields: {
    allocation_bps: SorobanType.U32;
    asset: SorobanType.Address;
    balance: SorobanType.I128;
    fee_value: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the StrategyPosition factory. */
export type StrategyPositionArgs = SorobanType.Input.Custom<StrategyPosition>;

/** Validate, encode and decode StrategyPosition using its contract declaration. */
export const StrategyPosition: SorobanType.Factory<StrategyPosition> =
  SorobanType
    .Custom.fromSpec<StrategyPosition>(
      () => TreasurySpec,
      "StrategyPosition",
    );

/** The TreasurySnapshot type declared by the contract. */
export type TreasurySnapshot = SorobanType.Custom<{
  kind: "struct";
  fields: {
    idle_fee_assets: SorobanType.I128;
    share_price: SorobanType.Option<SorobanType.I128>;
    strategy_positions: SorobanType.Vec<StrategyPosition>;
    strategy_value: SorobanType.I128;
    total_assets: SorobanType.I128;
    total_shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the TreasurySnapshot factory. */
export type TreasurySnapshotArgs = SorobanType.Input.Custom<TreasurySnapshot>;

/** Validate, encode and decode TreasurySnapshot using its contract declaration. */
export const TreasurySnapshot: SorobanType.Factory<TreasurySnapshot> =
  SorobanType
    .Custom.fromSpec<TreasurySnapshot>(
      () => TreasurySpec,
      "TreasurySnapshot",
    );

/** The RedemptionReceipt type declared by the contract. */
export type RedemptionReceipt = SorobanType.Custom<{
  kind: "struct";
  fields: {
    committed_at: SorobanType.U64;
    owner: SorobanType.Address;
    redeemable_at: SorobanType.U64;
    redeemed_at: SorobanType.U64;
    shares_burned: SorobanType.I128;
    strategy_redemptions: SorobanType.Vec<StrategyRedemption>;
  };
}>;

/** Raw or validated values accepted by the RedemptionReceipt factory. */
export type RedemptionReceiptArgs = SorobanType.Input.Custom<RedemptionReceipt>;

/** Validate, encode and decode RedemptionReceipt using its contract declaration. */
export const RedemptionReceipt: SorobanType.Factory<RedemptionReceipt> =
  SorobanType
    .Custom.fromSpec<RedemptionReceipt>(
      () => TreasurySpec,
      "RedemptionReceipt",
    );

/** The RedemptionRequest type declared by the contract. */
export type RedemptionRequest = SorobanType.Custom<{
  kind: "struct";
  fields: {
    committed_at: SorobanType.U64;
    owner: SorobanType.Address;
    redeemable_at: SorobanType.U64;
    shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the RedemptionRequest factory. */
export type RedemptionRequestArgs = SorobanType.Input.Custom<RedemptionRequest>;

/** Validate, encode and decode RedemptionRequest using its contract declaration. */
export const RedemptionRequest: SorobanType.Factory<RedemptionRequest> =
  SorobanType
    .Custom.fromSpec<RedemptionRequest>(
      () => TreasurySpec,
      "RedemptionRequest",
    );

/** The MarketHealthStatus type declared by the contract. */
export type MarketHealthStatus = SorobanType.Custom<{
  kind: "enum";
  encoding: "tagged";
  variants: {
    Healthy: SorobanType.Void;
    DefindexUnavailable: SorobanType.Void;
    OracleUnavailable: SorobanType.Void;
    OracleStale: SorobanType.Void;
    RouterUnavailable: SorobanType.Void;
    InvalidPrice: SorobanType.Void;
    DeviationExceeded: SorobanType.Void;
    SlippageExceeded: SorobanType.Void;
  };
}>;

/** Raw or validated values accepted by the MarketHealthStatus factory. */
export type MarketHealthStatusArgs = SorobanType.Input.Custom<
  MarketHealthStatus
>;

/** Validate, encode and decode MarketHealthStatus using its contract declaration. */
export const MarketHealthStatus: SorobanType.Factory<MarketHealthStatus> =
  SorobanType
    .Custom.fromSpec<MarketHealthStatus>(
      () => TreasurySpec,
      "MarketHealthStatus",
    );

/** The StrategyAllocation type declared by the contract. */
export type StrategyAllocation = SorobanType.Custom<{
  kind: "struct";
  fields: {
    asset: SorobanType.Address;
    bps: SorobanType.U32;
    strategy: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the StrategyAllocation factory. */
export type StrategyAllocationArgs = SorobanType.Input.Custom<
  StrategyAllocation
>;

/** Validate, encode and decode StrategyAllocation using its contract declaration. */
export const StrategyAllocation: SorobanType.Factory<StrategyAllocation> =
  SorobanType
    .Custom.fromSpec<StrategyAllocation>(
      () => TreasurySpec,
      "StrategyAllocation",
    );

/** The StrategyInvestment type declared by the contract. */
export type StrategyInvestment = SorobanType.Custom<{
  kind: "struct";
  fields: {
    amount_in: SorobanType.I128;
    amount_out: SorobanType.I128;
    asset: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the StrategyInvestment factory. */
export type StrategyInvestmentArgs = SorobanType.Input.Custom<
  StrategyInvestment
>;

/** Validate, encode and decode StrategyInvestment using its contract declaration. */
export const StrategyInvestment: SorobanType.Factory<StrategyInvestment> =
  SorobanType
    .Custom.fromSpec<StrategyInvestment>(
      () => TreasurySpec,
      "StrategyInvestment",
    );

/** The StrategyRedemption type declared by the contract. */
export type StrategyRedemption = SorobanType.Custom<{
  kind: "struct";
  fields: {
    amount: SorobanType.I128;
    asset: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the StrategyRedemption factory. */
export type StrategyRedemptionArgs = SorobanType.Input.Custom<
  StrategyRedemption
>;

/** Validate, encode and decode StrategyRedemption using its contract declaration. */
export const StrategyRedemption: SorobanType.Factory<StrategyRedemption> =
  SorobanType
    .Custom.fromSpec<StrategyRedemption>(
      () => TreasurySpec,
      "StrategyRedemption",
    );

/** The RebalanceInvestment type declared by the contract. */
export type RebalanceInvestment = SorobanType.Custom<{
  kind: "struct";
  fields: {
    amount: SorobanType.I128;
    strategy: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the RebalanceInvestment factory. */
export type RebalanceInvestmentArgs = SorobanType.Input.Custom<
  RebalanceInvestment
>;

/** Validate, encode and decode RebalanceInvestment using its contract declaration. */
export const RebalanceInvestment: SorobanType.Factory<RebalanceInvestment> =
  SorobanType
    .Custom.fromSpec<RebalanceInvestment>(
      () => TreasurySpec,
      "RebalanceInvestment",
    );

/** The AccountingParameters type declared by the contract. */
export type AccountingParameters = SorobanType.Custom<{
  kind: "struct";
  fields: {
    virtual_assets: SorobanType.I128;
    virtual_shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the AccountingParameters factory. */
export type AccountingParametersArgs = SorobanType.Input.Custom<
  AccountingParameters
>;

/** Validate, encode and decode AccountingParameters using its contract declaration. */
export const AccountingParameters: SorobanType.Factory<AccountingParameters> =
  SorobanType
    .Custom.fromSpec<AccountingParameters>(
      () => TreasurySpec,
      "AccountingParameters",
    );

/**
 * Measured backing movement; VNTY supply and accounting denomination remain
 * unchanged.
 */
export type VaultMigrationReceipt = SorobanType.Custom<{
  kind: "struct";
  fields: {
    new_vault: SorobanType.Address;
    new_vault_shares: SorobanType.I128;
    previous_vault: SorobanType.Address;
    previous_vault_shares: SorobanType.I128;
    usdc_moved: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the VaultMigrationReceipt factory. */
export type VaultMigrationReceiptArgs = SorobanType.Input.Custom<
  VaultMigrationReceipt
>;

/** Validate, encode and decode VaultMigrationReceipt using its contract declaration. */
export const VaultMigrationReceipt: SorobanType.Factory<VaultMigrationReceipt> =
  SorobanType
    .Custom.fromSpec<VaultMigrationReceipt>(
      () => TreasurySpec,
      "VaultMigrationReceipt",
    );

/**
 * Signed fee coverage intent. All amounts use their token's atomic units.
 */
export type VntyPaymentLimit = SorobanType.Custom<{
  kind: "struct";
  fields: {
    /** Exclusive execution deadline in Unix seconds. */
    deadline: SorobanType.U64;
    /** Expected complete protocol fee; prevents an unapproved cash increase. */
    fee_amount: SorobanType.I128;
    /** Exact fee-asset credit purchased by burning VNTY. */
    fee_credit: SorobanType.I128;
    /**
     * Maximum VNTY transferred temporarily, with unused shares refunded
     * atomically.
     */
    max_shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the VntyPaymentLimit factory. */
export type VntyPaymentLimitArgs = SorobanType.Input.Custom<VntyPaymentLimit>;

/** Validate, encode and decode VntyPaymentLimit using its contract declaration. */
export const VntyPaymentLimit: SorobanType.Factory<VntyPaymentLimit> =
  SorobanType
    .Custom.fromSpec<VntyPaymentLimit>(
      () => TreasurySpec,
      "VntyPaymentLimit",
    );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by Rebalanced. */
export type Rebalanced = {
  operator: SorobanType.Address;
  receipt: RebalanceReceipt;
};

/** Indexed fields accepted by the Rebalanced event filters. */
export type RebalancedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by SharesBurned. */
export type SharesBurned = {
  owner: SorobanType.Address;
  shares_burned: SorobanType.I128;
  value_covered: SorobanType.I128;
};

/** Indexed fields accepted by the SharesBurned event filters. */
export type SharesBurnedTopics = {
  owner: SorobanType.Input.Address;
};

/** Fields emitted by SharesMinted. */
export type SharesMinted = {
  payer: SorobanType.Address;
  beneficiary: SorobanType.Address;
  beneficiary_amount: SorobanType.I128;
  cashback_amount: SorobanType.I128;
  appreciation_amount: SorobanType.I128;
  beneficiary_shares_minted: SorobanType.I128;
  cashback_shares_minted: SorobanType.I128;
  total_shares_minted: SorobanType.I128;
};

/** Indexed fields accepted by the SharesMinted event filters. */
export type SharesMintedTopics = {
  payer: SorobanType.Input.Address;
  beneficiary: SorobanType.Input.Address;
};

/** Fields emitted by VaultMigrated. */
export type VaultMigrated = {
  operator: SorobanType.Address;
  receipt: VaultMigrationReceipt;
};

/** Indexed fields accepted by the VaultMigrated event filters. */
export type VaultMigratedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by FeeSplitChanged. */
export type FeeSplitChanged = {
  operator: SorobanType.Address;
  previous_beneficiary_bps: SorobanType.U32;
  previous_cashback_bps: SorobanType.U32;
  previous_appreciation_bps: SorobanType.U32;
  new_beneficiary_bps: SorobanType.U32;
  new_cashback_bps: SorobanType.U32;
  new_appreciation_bps: SorobanType.U32;
};

/** Indexed fields accepted by the FeeSplitChanged event filters. */
export type FeeSplitChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by StrategyRescued. */
export type StrategyRescued = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
};

/** Indexed fields accepted by the StrategyRescued event filters. */
export type StrategyRescuedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by DefindexReported. */
export type DefindexReported = {
  operator: SorobanType.Address;
};

/** Indexed fields accepted by the DefindexReported event filters. */
export type DefindexReportedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by BeneficiaryChanged. */
export type BeneficiaryChanged = {
  operator: SorobanType.Address;
  previous_beneficiary: SorobanType.Address;
  new_beneficiary: SorobanType.Address;
};

/** Indexed fields accepted by the BeneficiaryChanged event filters. */
export type BeneficiaryChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by DefindexFeesLocked. */
export type DefindexFeesLocked = {
  operator: SorobanType.Address;
  new_fee_bps: SorobanType.Option<SorobanType.U32>;
};

/** Indexed fields accepted by the DefindexFeesLocked event filters. */
export type DefindexFeesLockedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by CollateralDeposited. */
export type CollateralDeposited = {
  payer: SorobanType.Address;
  nominal_fee: SorobanType.I128;
  fee_asset_collected: SorobanType.I128;
  realized_value: SorobanType.I128;
  strategy_investments: SorobanType.Vec<StrategyInvestment>;
};

/** Indexed fields accepted by the CollateralDeposited event filters. */
export type CollateralDepositedTopics = {
  payer: SorobanType.Input.Address;
};

/** Fields emitted by RedemptionCancelled. */
export type RedemptionCancelled = {
  owner: SorobanType.Address;
  shares_returned: SorobanType.I128;
  committed_at: SorobanType.U64;
  cancelled_at: SorobanType.U64;
};

/** Indexed fields accepted by the RedemptionCancelled event filters. */
export type RedemptionCancelledTopics = {
  owner: SorobanType.Input.Address;
};

/** Fields emitted by RedemptionCommitted. */
export type RedemptionCommitted = {
  owner: SorobanType.Address;
  shares: SorobanType.I128;
  committed_at: SorobanType.U64;
  redeemable_at: SorobanType.U64;
};

/** Indexed fields accepted by the RedemptionCommitted event filters. */
export type RedemptionCommittedTopics = {
  owner: SorobanType.Input.Address;
};

/** Fields emitted by RedemptionCompleted. */
export type RedemptionCompleted = {
  owner: SorobanType.Address;
  shares_burned: SorobanType.I128;
  strategy_redemptions: SorobanType.Vec<StrategyRedemption>;
  committed_at: SorobanType.U64;
  redeemable_at: SorobanType.U64;
  redeemed_at: SorobanType.U64;
};

/** Indexed fields accepted by the RedemptionCompleted event filters. */
export type RedemptionCompletedTopics = {
  owner: SorobanType.Input.Address;
};

/** Fields emitted by DefindexFeesReleased. */
export type DefindexFeesReleased = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  amount: SorobanType.I128;
};

/** Indexed fields accepted by the DefindexFeesReleased event filters. */
export type DefindexFeesReleasedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by StrategyPauseChanged. */
export type StrategyPauseChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  paused: SorobanType.Bool;
};

/** Indexed fields accepted by the StrategyPauseChanged event filters. */
export type StrategyPauseChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by ImplementationChanged. */
export type ImplementationChanged = {
  operator: SorobanType.Address;
  new_wasm_hash: SorobanType.BytesN<32>;
};

/** Indexed fields accepted by the ImplementationChanged event filters. */
export type ImplementationChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by StrategyKeeperClaimed. */
export type StrategyKeeperClaimed = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
};

/** Indexed fields accepted by the StrategyKeeperClaimed event filters. */
export type StrategyKeeperClaimedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by StrategyTvlCapChanged. */
export type StrategyTvlCapChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  amount: SorobanType.I128;
};

/** Indexed fields accepted by the StrategyTvlCapChanged event filters. */
export type StrategyTvlCapChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by StrategyPricingChanged. */
export type StrategyPricingChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  max_spread_bps: SorobanType.U32;
  quote_ttl_seconds: SorobanType.U64;
  slippage_bps: SorobanType.U32;
};

/** Indexed fields accepted by the StrategyPricingChanged event filters. */
export type StrategyPricingChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by DefindexFeesDistributed. */
export type DefindexFeesDistributed = {
  operator: SorobanType.Address;
};

/** Indexed fields accepted by the DefindexFeesDistributed event filters. */
export type DefindexFeesDistributedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by StrategyCodeHashChanged. */
export type StrategyCodeHashChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  hash: SorobanType.BytesN<32>;
  allowed: SorobanType.Bool;
};

/** Indexed fields accepted by the StrategyCodeHashChanged event filters. */
export type StrategyCodeHashChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by StrategyDepositorChanged. */
export type StrategyDepositorChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  depositor: SorobanType.Address;
  allowed: SorobanType.Bool;
};

/** Indexed fields accepted by the StrategyDepositorChanged event filters. */
export type StrategyDepositorChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by StrategyDepositCapChanged. */
export type StrategyDepositCapChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  amount: SorobanType.I128;
};

/** Indexed fields accepted by the StrategyDepositCapChanged event filters. */
export type StrategyDepositCapChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by DefindexFeeReceiverChanged. */
export type DefindexFeeReceiverChanged = {
  operator: SorobanType.Address;
  receiver: SorobanType.Address;
};

/** Indexed fields accepted by the DefindexFeeReceiverChanged event filters. */
export type DefindexFeeReceiverChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by StrategyAllocationsChanged. */
export type StrategyAllocationsChanged = {
  operator: SorobanType.Address;
  previous_allocations: SorobanType.Vec<StrategyAllocation>;
  new_allocations: SorobanType.Vec<StrategyAllocation>;
};

/** Indexed fields accepted by the StrategyAllocationsChanged event filters. */
export type StrategyAllocationsChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by StrategyDepositsPauseChanged. */
export type StrategyDepositsPauseChanged = {
  operator: SorobanType.Address;
  strategy: SorobanType.Address;
  paused: SorobanType.Bool;
};

/** Indexed fields accepted by the StrategyDepositsPauseChanged event filters. */
export type StrategyDepositsPauseChangedTopics = {
  operator: SorobanType.Input.Address;
  strategy: SorobanType.Input.Address;
};

/** Fields emitted by DefindexImplementationChanged. */
export type DefindexImplementationChanged = {
  operator: SorobanType.Address;
  new_wasm_hash: SorobanType.BytesN<32>;
};

/** Indexed fields accepted by the DefindexImplementationChanged event filters. */
export type DefindexImplementationChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Event emitted when the contract is paused. */
export type Paused = Record<string, never>;

/** Indexed fields accepted by the Paused event filters. */
export type PausedTopics = Record<string, never>;

/** Event emitted when the contract is unpaused. */
export type Unpaused = Record<string, never>;

/** Indexed fields accepted by the Unpaused event filters. */
export type UnpausedTopics = Record<string, never>;

/** Event definitions bound to this client, with typed decoding and filters. */
export type TreasuryEvents = ContractEventRegistry & {
  readonly Rebalanced: ContractEventDefinition<
    Rebalanced,
    RebalancedTopics
  >;
  readonly SharesBurned: ContractEventDefinition<
    SharesBurned,
    SharesBurnedTopics
  >;
  readonly SharesMinted: ContractEventDefinition<
    SharesMinted,
    SharesMintedTopics
  >;
  readonly VaultMigrated: ContractEventDefinition<
    VaultMigrated,
    VaultMigratedTopics
  >;
  readonly FeeSplitChanged: ContractEventDefinition<
    FeeSplitChanged,
    FeeSplitChangedTopics
  >;
  readonly StrategyRescued: ContractEventDefinition<
    StrategyRescued,
    StrategyRescuedTopics
  >;
  readonly DefindexReported: ContractEventDefinition<
    DefindexReported,
    DefindexReportedTopics
  >;
  readonly BeneficiaryChanged: ContractEventDefinition<
    BeneficiaryChanged,
    BeneficiaryChangedTopics
  >;
  readonly DefindexFeesLocked: ContractEventDefinition<
    DefindexFeesLocked,
    DefindexFeesLockedTopics
  >;
  readonly CollateralDeposited: ContractEventDefinition<
    CollateralDeposited,
    CollateralDepositedTopics
  >;
  readonly RedemptionCancelled: ContractEventDefinition<
    RedemptionCancelled,
    RedemptionCancelledTopics
  >;
  readonly RedemptionCommitted: ContractEventDefinition<
    RedemptionCommitted,
    RedemptionCommittedTopics
  >;
  readonly RedemptionCompleted: ContractEventDefinition<
    RedemptionCompleted,
    RedemptionCompletedTopics
  >;
  readonly DefindexFeesReleased: ContractEventDefinition<
    DefindexFeesReleased,
    DefindexFeesReleasedTopics
  >;
  readonly StrategyPauseChanged: ContractEventDefinition<
    StrategyPauseChanged,
    StrategyPauseChangedTopics
  >;
  readonly ImplementationChanged: ContractEventDefinition<
    ImplementationChanged,
    ImplementationChangedTopics
  >;
  readonly StrategyKeeperClaimed: ContractEventDefinition<
    StrategyKeeperClaimed,
    StrategyKeeperClaimedTopics
  >;
  readonly StrategyTvlCapChanged: ContractEventDefinition<
    StrategyTvlCapChanged,
    StrategyTvlCapChangedTopics
  >;
  readonly StrategyPricingChanged: ContractEventDefinition<
    StrategyPricingChanged,
    StrategyPricingChangedTopics
  >;
  readonly DefindexFeesDistributed: ContractEventDefinition<
    DefindexFeesDistributed,
    DefindexFeesDistributedTopics
  >;
  readonly StrategyCodeHashChanged: ContractEventDefinition<
    StrategyCodeHashChanged,
    StrategyCodeHashChangedTopics
  >;
  readonly StrategyDepositorChanged: ContractEventDefinition<
    StrategyDepositorChanged,
    StrategyDepositorChangedTopics
  >;
  readonly StrategyDepositCapChanged: ContractEventDefinition<
    StrategyDepositCapChanged,
    StrategyDepositCapChangedTopics
  >;
  readonly DefindexFeeReceiverChanged: ContractEventDefinition<
    DefindexFeeReceiverChanged,
    DefindexFeeReceiverChangedTopics
  >;
  readonly StrategyAllocationsChanged: ContractEventDefinition<
    StrategyAllocationsChanged,
    StrategyAllocationsChangedTopics
  >;
  readonly StrategyDepositsPauseChanged: ContractEventDefinition<
    StrategyDepositsPauseChanged,
    StrategyDepositsPauseChangedTopics
  >;
  readonly DefindexImplementationChanged: ContractEventDefinition<
    DefindexImplementationChanged,
    DefindexImplementationChangedTopics
  >;
  readonly Paused: ContractEventDefinition<
    Paused,
    PausedTopics
  >;
  readonly Unpaused: ContractEventDefinition<
    Unpaused,
    UnpausedTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type TreasuryConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
