// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Marketplace.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  MarketplaceErrors,
  MarketplaceSpec,
} from "@/contracts/marketplace/constants.ts";
import type {
  MarketplaceCall,
  MarketplaceConstructorArgs,
  MarketplaceEvents,
  MarketplaceInvocation,
  MarketplaceInvocationResult,
  MarketplaceMethod,
  MarketplaceMethodMap,
  MarketplaceOutputs,
} from "@/contracts/marketplace/types.ts";

export * from "@/contracts/marketplace/constants.ts";
export * from "@/contracts/marketplace/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Marketplace extends Contract {
  /**
   * Purchases a listed NFT using the marketplace settlement asset.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `buyer` - Address paying for and receiving the NFT.
   * * `contract_address` - Vanity contract address identifying the sale.
   * * `expected_price` - Price the buyer expects, protecting against stale
   * transaction data.
   *
   * # Errors
   *
   * * Fails when the marketplace is paused or `buyer` does not authorize the
   * invocation.
   * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
   * * Fails with `MarketplaceError::SelfPurchase` when the seller is the
   * buyer.
   * * Fails with `MarketplaceError::PriceChanged` when the listing price
   * differs.
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Fails with `MarketplaceError::SellerIndexNotFound` or
   * `MarketplaceError::SellerIndexCorrupted` when index storage is
   * inconsistent.
   * * Fails with `MarketplaceError::ArithmeticOverflow` when fee calculations
   * overflow.
   * * Propagates settlement-asset, treasury, strategy, cashback, and NFT
   * transfer
   */
  readonly buy: MarketplaceMethod<"buy"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Buy, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Buy,
      }),
  };

  /**
   * Pauses new sale placement and purchases while preserving cancellation.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `operator` - RBAC administrator authorizing the pause.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Propagates authorization and role errors from the RBAC contract.
   * * Propagates pausable errors when the requested state transition is
   * invalid.
   */
  readonly pause: MarketplaceMethod<"pause"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Pause, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Pause,
      }),
  };

  /**
   * Restores sale placement and purchases after a pause.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `operator` - RBAC administrator authorizing the unpause.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Propagates authorization and role errors from the RBAC contract.
   * * Propagates pausable errors when the requested state transition is
   * invalid.
   */
  readonly unpause: MarketplaceMethod<"unpause"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Unpause, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Unpause,
      }),
  };

  /**
   * Replaces the marketplace implementation with installed Wasm.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed Wasm hash selected as the new
   * implementation.
   * * `operator` - RBAC upgrader authorizing the upgrade.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Propagates role errors from the RBAC contract.
   * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
   */
  readonly upgrade: MarketplaceMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Returns the current marketplace configuration.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured contracts, settlement asset, treasury, and protocol fee.
   *
   * # Errors
   *
   * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   */
  readonly getConfig: MarketplaceMethod<"get_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetConfig,
      }),
  };

  /**
   * Returns whether sale placement and purchase are paused.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * `true` when the marketplace is paused; otherwise `false`.
   *
   * # Errors
   *
   * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   */
  readonly getPaused: MarketplaceMethod<"get_paused"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPaused, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPaused,
      }),
  };

  /**
   * Cancels a sale and returns the escrowed NFT to its seller.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Vanity contract address identifying the sale.
   * * `operator` - Seller authorizing cancellation.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
   * * Fails with `MarketplaceError::IncorrectSeller` when `operator` is not
   * the seller.
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Fails with `MarketplaceError::SellerIndexNotFound` or
   * `MarketplaceError::SellerIndexCorrupted` when index storage is
   * inconsistent.
   * * Propagates NFT transfer errors.
   */
  readonly cancelSale: MarketplaceMethod<"cancel_sale"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CancelSale, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CancelSale,
      }),
  };

  /**
   * Returns the active sale for a vanity contract address, if one exists.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Vanity contract address used as the listing key.
   *
   * # Returns
   *
   * The active listing, or `None` when the address is not for sale.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::SellerIndexNotFound` when an active
   * listing has
   * lost its seller index.
   * * Fails with `MarketplaceError::SaleNotFound` or
   * `MarketplaceError::SellerIndexCorrupted` when adjacent index records are
   * invalid.
   */
  readonly getListing: MarketplaceMethod<"get_listing"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetListing, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetListing,
      }),
  };

  /**
   * Changes the treasury that receives protocol fees from future purchases.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `treasury` - New protocol fee recipient.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setTreasury: MarketplaceMethod<"set_treasury"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetTreasury, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetTreasury,
      }),
  };

  /**
   * Purchases a listing using a fixed fee credit and bounded VNTY input.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `buyer` - Authorizes payment and receives the NFT.
   * * `contract_address` - Listed vanity address.
   * * `expected_price` - Expected fee-inclusive listing price.
   * * `payment` - Expected protocol fee, exact credit, maximum VNTY, and
   * exclusive Unix deadline.
   *
   * # Errors
   * Propagates all buy validation, escrow, settlement, and NFT transfer
   * errors;
   * Treasury additionally rejects expired payments, changed fees, exceeded
   * limits,
   * unavailable NAV, invalid shares, or failed maximum transfer/refund.
   * Failure is atomic.
   */
  readonly buyWithLimit: MarketplaceMethod<"buy_with_limit"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.BuyWithLimit, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.BuyWithLimit,
      }),
  };

  /**
   * Transfers an NFT into escrow and opens a sale at a fixed price.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `seller` - Current NFT owner opening the sale.
   * * `contract_address` - Vanity contract address represented by the NFT.
   * * `price` - Positive settlement-asset amount requested from a buyer.
   *
   * # Errors
   *
   * * Fails when the marketplace is paused or `seller` does not authorize the
   * invocation.
   * * Fails with `MarketplaceError::InvalidPrice` when `price` is not
   * positive.
   * * Fails with `MarketplaceError::SaleAlreadyExists` when the address is
   * already listed.
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Fails with `MarketplaceError::IncorrectOwner` when `seller` does not own
   * the NFT.
   * * Fails with `MarketplaceError::ClaimAddressMismatch` for an inconsistent
   * NFT claim.
   * * Fails with `MarketplaceError::InvalidSettlementRecipient` when the
   * seller is not
   * authorized to receive the settlement asset.
   * * Fails with `MarketplaceError::SaleNotFound` or
   * `MarketplaceError::SellerInde
   */
  readonly placeForSale: MarketplaceMethod<"place_for_sale"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.PlaceForSale, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.PlaceForSale,
      }),
  };

  /**
   * Purchases a listed NFT while covering part of the protocol fee with VNTY
   * shares.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `buyer` - Address paying for and receiving the NFT.
   * * `contract_address` - Vanity contract address identifying the sale.
   * * `expected_price` - Price the buyer expects, protecting against stale
   * transaction data.
   * * `fee_shares` - VNTY shares burned toward the protocol-fee portion of the
   * price.
   *
   * # Errors
   *
   * * Fails when the marketplace is paused or `buyer` does not authorize the
   * invocation.
   * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
   * * Fails with `MarketplaceError::SelfPurchase` when the seller is the
   * buyer.
   * * Fails with `MarketplaceError::PriceChanged` when the listing price
   * differs.
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Fails with `MarketplaceError::SellerIndexNotFound` or
   * `MarketplaceError::SellerIndexCorrupted` when index storage is
   * inconsistent.
   * * Fails with `MarketplaceError::ArithmeticOverflow` when fee c
   */
  readonly buyWithShares: MarketplaceMethod<"buy_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.BuyWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.BuyWithShares,
      }),
  };

  /**
   * Changes the fee snapshotted into subsequently opened sales.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `fee_bps` - New protocol fee in basis points.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
   * unavailable.
   * * Fails with `MarketplaceError::InvalidTreasury` when the treasury is not
   * a Wasm
   * contract configured for the marketplace settlement asset.
   * * Fails with `MarketplaceError::InvalidProtocolFee` when the fee exceeds
   * the maximum.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setProtocolFee: MarketplaceMethod<"set_protocol_fee"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetProtocolFee, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetProtocolFee,
      }),
  };

  /**
   * Returns one cursor-based page of active sales opened by a seller.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `seller` - Seller whose active sales are requested.
   * * `cursor` - Optional listing address from which traversal begins.
   * * `limit` - Number of sales requested, from 1 through the maximum page
   * size.
   *
   * # Returns
   *
   * The requested sales, next cursor, and seller's total active-sale count.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::InvalidPageLimit` for an unsupported
   * `limit`.
   * * Fails with `MarketplaceError::InvalidCursor` when the cursor is not
   * valid for `seller`.
   * * Fails with `MarketplaceError::SaleNotFound` or
   * `MarketplaceError::SellerIndexCorrupted` when index storage is
   * inconsistent.
   */
  readonly getSalesBySeller: MarketplaceMethod<"get_sales_by_seller"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetSalesBySeller, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetSalesBySeller,
      }),
  };

  /**
   * Returns the number of active sales opened by a seller.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `seller` - Seller whose active-sale count is requested.
   *
   * # Returns
   *
   * The seller's active-sale count, or zero when the seller has no sales.
   *
   * # Errors
   *
   * * Fails with `MarketplaceError::SaleNotFound` when the indexed head is
   * missing.
   * * Fails with `MarketplaceError::SellerIndexCorrupted` when seller index
   * storage is invalid.
   */
  readonly getSellerSaleCount: MarketplaceMethod<"get_seller_sale_count"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetSellerSaleCount, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetSellerSaleCount,
      }),
  };

  /**
   * Switches Testnet settlement after a matching Treasury migration.
   *
   * Requires Admin authorization, the Testnet network and a paused
   * marketplace.
   * Existing listings keep their prices, fees and escrow and settle in the new
   * currency without relisting. Rejects non-SAC or incompatible assets.
   *
   * # Arguments
   * * `e` - Contract environment.
   * * `asset` - New settlement Stellar Asset Contract matching the Treasury.
   * * `operator` - Authorized administrator.
   *
   * # Errors
   * Rejects other networks, missing authorization, unpaused state, or an
   * unchanged, incompatible or non-SAC settlement asset.
   */
  readonly migrateTestnetSettlement: MarketplaceMethod<
    "migrate_testnet_settlement"
  > = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.MigrateTestnetSettlement,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.MigrateTestnetSettlement,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor(
    { errors = MarketplaceErrors, ...args }: MarketplaceConstructorArgs,
  ) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(
          MarketplaceSpec.entries.map((entry) => entry.toXdr("base64")),
        ),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): MarketplaceEvents {
    return super.events as MarketplaceEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof MarketplaceMethodMap>(
    args: MarketplaceCall<Method>,
  ): Promise<MarketplaceOutputs[Method]> {
    return await super.read(args) as MarketplaceOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof MarketplaceMethodMap>(
    args: MarketplaceCall<Method> & MarketplaceInvocation,
  ): Promise<MarketplaceInvocationResult<MarketplaceOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<MarketplaceOutputs[Method]>(
      args.method,
      result,
    );
  }
}
