// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Marketplace contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { MarketplaceSpec } from "@/contracts/marketplace/constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Purchases a listed NFT using the marketplace settlement asset.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `buyer` - Address paying for and receiving the NFT.
 * * `contract_address` - Vanity contract address identifying the sale.
 * * `expected_price` - Price the buyer expects, protecting against stale
 * transaction data.
 *
 * # Errors
 *
 * * Fails when the marketplace is paused or `buyer` does not authorize the
 * invocation.
 * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
 * * Fails with `MarketplaceError::SelfPurchase` when the seller is the
 * buyer.
 * * Fails with `MarketplaceError::PriceChanged` when the listing price
 * differs.
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Fails with `MarketplaceError::SellerIndexNotFound` or
 * `MarketplaceError::SellerIndexCorrupted` when index storage is
 * inconsistent.
 * * Fails with `MarketplaceError::ArithmeticOverflow` when fee calculations
 * overflow.
 * * Propagates settlement-asset, treasury, strategy, cashback, and NFT
 * transfer
 */
export type BuyInput = {
  buyer: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  expected_price: SorobanType.Input.I128;
};

/** Decoded return value of buy. */
export type BuyOutput = null;

/**
 * Pauses new sale placement and purchases while preserving cancellation.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `operator` - RBAC administrator authorizing the pause.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Propagates authorization and role errors from the RBAC contract.
 * * Propagates pausable errors when the requested state transition is
 * invalid.
 */
export type PauseInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of pause. */
export type PauseOutput = null;

/**
 * Restores sale placement and purchases after a pause.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `operator` - RBAC administrator authorizing the unpause.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Propagates authorization and role errors from the RBAC contract.
 * * Propagates pausable errors when the requested state transition is
 * invalid.
 */
export type UnpauseInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of unpause. */
export type UnpauseOutput = null;

/**
 * Replaces the marketplace implementation with installed Wasm.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed Wasm hash selected as the new
 * implementation.
 * * `operator` - RBAC upgrader authorizing the upgrade.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Propagates role errors from the RBAC contract.
 * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Returns the current marketplace configuration.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured contracts, settlement asset, treasury, and protocol fee.
 *
 * # Errors
 *
 * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 */
export type GetConfigInput = Record<string, never>;

/** Decoded return value of get_config. */
export type GetConfigOutput = MarketplaceConfig;

/**
 * Returns whether sale placement and purchase are paused.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * `true` when the marketplace is paused; otherwise `false`.
 *
 * # Errors
 *
 * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 */
export type GetPausedInput = Record<string, never>;

/** Decoded return value of get_paused. */
export type GetPausedOutput = SorobanType.Bool;

/**
 * Cancels a sale and returns the escrowed NFT to its seller.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Vanity contract address identifying the sale.
 * * `operator` - Seller authorizing cancellation.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
 * * Fails with `MarketplaceError::IncorrectSeller` when `operator` is not
 * the seller.
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Fails with `MarketplaceError::SellerIndexNotFound` or
 * `MarketplaceError::SellerIndexCorrupted` when index storage is
 * inconsistent.
 * * Propagates NFT transfer errors.
 */
export type CancelSaleInput = {
  contract_address: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of cancel_sale. */
export type CancelSaleOutput = null;

/**
 * Returns the active sale for a vanity contract address, if one exists.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Vanity contract address used as the listing key.
 *
 * # Returns
 *
 * The active listing, or `None` when the address is not for sale.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::SellerIndexNotFound` when an active
 * listing has
 * lost its seller index.
 * * Fails with `MarketplaceError::SaleNotFound` or
 * `MarketplaceError::SellerIndexCorrupted` when adjacent index records are
 * invalid.
 */
export type GetListingInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_listing. */
export type GetListingOutput = SorobanType.Option<Listing>;

/**
 * Changes the treasury that receives protocol fees from future purchases.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `treasury` - New protocol fee recipient.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetTreasuryInput = {
  treasury: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_treasury. */
export type SetTreasuryOutput = null;

/**
 * Initializes a marketplace for one NFT collection and settlement asset.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `config` - RBAC, NFT, settlement asset, treasury, and protocol fee
 * configuration.
 * * `operator` - RBAC administrator authorizing construction.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::InvalidProtocolFee` when the fee exceeds
 * the maximum.
 * * Fails with `MarketplaceError::InvalidSettlementAsset` when settlement is
 * not a
 * deployed Stellar Asset Contract.
 * * Fails with `MarketplaceError::InvalidTreasury` when the treasury is not
 * a Wasm
 * contract configured for the marketplace settlement asset.
 * * Fails with `MarketplaceError::InvalidNft` when the NFT is not a Wasm
 * contract
 * governed by the configured RBAC contract.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type ConstructorInput = {
  config: MarketplaceConfigArgs;
  operator: SorobanType.Input.Address;
};

/**
 * Purchases a listing using a fixed fee credit and bounded VNTY input.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `buyer` - Authorizes payment and receives the NFT.
 * * `contract_address` - Listed vanity address.
 * * `expected_price` - Expected fee-inclusive listing price.
 * * `payment` - Expected protocol fee, exact credit, maximum VNTY, and
 * exclusive Unix deadline.
 *
 * # Errors
 * Propagates all buy validation, escrow, settlement, and NFT transfer
 * errors;
 * Treasury additionally rejects expired payments, changed fees, exceeded
 * limits,
 * unavailable NAV, invalid shares, or failed maximum transfer/refund.
 * Failure is atomic.
 */
export type BuyWithLimitInput = {
  buyer: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  expected_price: SorobanType.Input.I128;
  payment: VntyPaymentLimitArgs;
};

/** Decoded return value of buy_with_limit. */
export type BuyWithLimitOutput = null;

/**
 * Transfers an NFT into escrow and opens a sale at a fixed price.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `seller` - Current NFT owner opening the sale.
 * * `contract_address` - Vanity contract address represented by the NFT.
 * * `price` - Positive settlement-asset amount requested from a buyer.
 *
 * # Errors
 *
 * * Fails when the marketplace is paused or `seller` does not authorize the
 * invocation.
 * * Fails with `MarketplaceError::InvalidPrice` when `price` is not
 * positive.
 * * Fails with `MarketplaceError::SaleAlreadyExists` when the address is
 * already listed.
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Fails with `MarketplaceError::IncorrectOwner` when `seller` does not own
 * the NFT.
 * * Fails with `MarketplaceError::ClaimAddressMismatch` for an inconsistent
 * NFT claim.
 * * Fails with `MarketplaceError::InvalidSettlementRecipient` when the
 * seller is not
 * authorized to receive the settlement asset.
 * * Fails with `MarketplaceError::SaleNotFound` or
 * `MarketplaceError::SellerInde
 */
export type PlaceForSaleInput = {
  seller: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  price: SorobanType.Input.I128;
};

/** Decoded return value of place_for_sale. */
export type PlaceForSaleOutput = null;

/**
 * Purchases a listed NFT while covering part of the protocol fee with VNTY
 * shares.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `buyer` - Address paying for and receiving the NFT.
 * * `contract_address` - Vanity contract address identifying the sale.
 * * `expected_price` - Price the buyer expects, protecting against stale
 * transaction data.
 * * `fee_shares` - VNTY shares burned toward the protocol-fee portion of the
 * price.
 *
 * # Errors
 *
 * * Fails when the marketplace is paused or `buyer` does not authorize the
 * invocation.
 * * Fails with `MarketplaceError::SaleNotFound` when no sale exists.
 * * Fails with `MarketplaceError::SelfPurchase` when the seller is the
 * buyer.
 * * Fails with `MarketplaceError::PriceChanged` when the listing price
 * differs.
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Fails with `MarketplaceError::SellerIndexNotFound` or
 * `MarketplaceError::SellerIndexCorrupted` when index storage is
 * inconsistent.
 * * Fails with `MarketplaceError::ArithmeticOverflow` when fee c
 */
export type BuyWithSharesInput = {
  buyer: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  expected_price: SorobanType.Input.I128;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of buy_with_shares. */
export type BuyWithSharesOutput = null;

/**
 * Changes the fee snapshotted into subsequently opened sales.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `fee_bps` - New protocol fee in basis points.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::ConfigNotFound` when configuration is
 * unavailable.
 * * Fails with `MarketplaceError::InvalidTreasury` when the treasury is not
 * a Wasm
 * contract configured for the marketplace settlement asset.
 * * Fails with `MarketplaceError::InvalidProtocolFee` when the fee exceeds
 * the maximum.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetProtocolFeeInput = {
  fee_bps: SorobanType.Input.U32;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_protocol_fee. */
export type SetProtocolFeeOutput = null;

/**
 * Returns one cursor-based page of active sales opened by a seller.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `seller` - Seller whose active sales are requested.
 * * `cursor` - Optional listing address from which traversal begins.
 * * `limit` - Number of sales requested, from 1 through the maximum page
 * size.
 *
 * # Returns
 *
 * The requested sales, next cursor, and seller's total active-sale count.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::InvalidPageLimit` for an unsupported
 * `limit`.
 * * Fails with `MarketplaceError::InvalidCursor` when the cursor is not
 * valid for `seller`.
 * * Fails with `MarketplaceError::SaleNotFound` or
 * `MarketplaceError::SellerIndexCorrupted` when index storage is
 * inconsistent.
 */
export type GetSalesBySellerInput = {
  seller: SorobanType.Input.Address;
  cursor: SorobanType.Input.Option<
    SorobanType.Input.Address,
    SorobanType.Address
  >;
  limit: SorobanType.Input.U32;
};

/** Decoded return value of get_sales_by_seller. */
export type GetSalesBySellerOutput = SellerSalesPage;

/**
 * Returns the number of active sales opened by a seller.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `seller` - Seller whose active-sale count is requested.
 *
 * # Returns
 *
 * The seller's active-sale count, or zero when the seller has no sales.
 *
 * # Errors
 *
 * * Fails with `MarketplaceError::SaleNotFound` when the indexed head is
 * missing.
 * * Fails with `MarketplaceError::SellerIndexCorrupted` when seller index
 * storage is invalid.
 */
export type GetSellerSaleCountInput = {
  seller: SorobanType.Input.Address;
};

/** Decoded return value of get_seller_sale_count. */
export type GetSellerSaleCountOutput = SorobanType.U32;

/**
 * Switches Testnet settlement after a matching Treasury migration.
 *
 * Requires Admin authorization, the Testnet network and a paused
 * marketplace.
 * Existing listings keep their prices, fees and escrow and settle in the new
 * currency without relisting. Rejects non-SAC or incompatible assets.
 *
 * # Arguments
 * * `e` - Contract environment.
 * * `asset` - New settlement Stellar Asset Contract matching the Treasury.
 * * `operator` - Authorized administrator.
 *
 * # Errors
 * Rejects other networks, missing authorization, unpaused state, or an
 * unchanged, incompatible or non-SAC settlement asset.
 */
export type MigrateTestnetSettlementInput = {
  asset: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of migrate_testnet_settlement. */
export type MigrateTestnetSettlementOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type MarketplaceMethodMap = {
  buy: {
    input: BuyInput;
    output: BuyOutput;
  };
  pause: {
    input: PauseInput;
    output: PauseOutput;
  };
  unpause: {
    input: UnpauseInput;
    output: UnpauseOutput;
  };
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  get_config: {
    input: GetConfigInput;
    output: GetConfigOutput;
  };
  get_paused: {
    input: GetPausedInput;
    output: GetPausedOutput;
  };
  cancel_sale: {
    input: CancelSaleInput;
    output: CancelSaleOutput;
  };
  get_listing: {
    input: GetListingInput;
    output: GetListingOutput;
  };
  set_treasury: {
    input: SetTreasuryInput;
    output: SetTreasuryOutput;
  };
  buy_with_limit: {
    input: BuyWithLimitInput;
    output: BuyWithLimitOutput;
  };
  place_for_sale: {
    input: PlaceForSaleInput;
    output: PlaceForSaleOutput;
  };
  buy_with_shares: {
    input: BuyWithSharesInput;
    output: BuyWithSharesOutput;
  };
  set_protocol_fee: {
    input: SetProtocolFeeInput;
    output: SetProtocolFeeOutput;
  };
  get_sales_by_seller: {
    input: GetSalesBySellerInput;
    output: GetSalesBySellerOutput;
  };
  get_seller_sale_count: {
    input: GetSellerSaleCountInput;
    output: GetSellerSaleCountOutput;
  };
  migrate_testnet_settlement: {
    input: MigrateTestnetSettlementInput;
    output: MigrateTestnetSettlementOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type MarketplaceInputs = {
  [Method in keyof MarketplaceMethodMap]: MarketplaceMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type MarketplaceOutputs = {
  [Method in keyof MarketplaceMethodMap]:
    MarketplaceMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type MarketplaceCall<Method extends keyof MarketplaceMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      MarketplaceInputs[Name] extends Record<string, never>
        ? { methodArgs?: MarketplaceInputs[Name] }
        : { methodArgs: MarketplaceInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type MarketplaceInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type MarketplaceInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type MarketplaceMethod<Method extends keyof MarketplaceMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: MarketplaceInputs[Method] extends Record<string, never>
      ? [methodArgs?: MarketplaceInputs[Method]]
      : [methodArgs: MarketplaceInputs[Method]]
  ) => Promise<MarketplaceOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<MarketplaceCall<Method>, "method"> & MarketplaceInvocation,
  ) => Promise<MarketplaceInvocationResult<MarketplaceOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** The Listing type declared by the contract. */
export type Listing = SorobanType.Custom<{
  kind: "struct";
  fields: {
    contract_address: SorobanType.Address;
    fee_bps: SorobanType.U32;
    price: SorobanType.I128;
    seller: SorobanType.Address;
    token_id: SorobanType.U32;
    word: SorobanType.String;
  };
}>;

/** Raw or validated values accepted by the Listing factory. */
export type ListingArgs = SorobanType.Input.Custom<Listing>;

/** Validate, encode and decode Listing using its contract declaration. */
export const Listing: SorobanType.Factory<Listing> = SorobanType
  .Custom.fromSpec<Listing>(
    () => MarketplaceSpec,
    "Listing",
  );

/** The SellerSalesPage type declared by the contract. */
export type SellerSalesPage = SorobanType.Custom<{
  kind: "struct";
  fields: {
    next_cursor: SorobanType.Option<SorobanType.Address>;
    sales: SorobanType.Vec<Listing>;
    total_count: SorobanType.U32;
  };
}>;

/** Raw or validated values accepted by the SellerSalesPage factory. */
export type SellerSalesPageArgs = SorobanType.Input.Custom<SellerSalesPage>;

/** Validate, encode and decode SellerSalesPage using its contract declaration. */
export const SellerSalesPage: SorobanType.Factory<SellerSalesPage> = SorobanType
  .Custom.fromSpec<SellerSalesPage>(
    () => MarketplaceSpec,
    "SellerSalesPage",
  );

/** The MarketplaceConfig type declared by the contract. */
export type MarketplaceConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    nft: SorobanType.Address;
    protocol_fee_bps: SorobanType.U32;
    rbac: SorobanType.Address;
    settlement_asset: SorobanType.Address;
    treasury: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the MarketplaceConfig factory. */
export type MarketplaceConfigArgs = SorobanType.Input.Custom<MarketplaceConfig>;

/** Validate, encode and decode MarketplaceConfig using its contract declaration. */
export const MarketplaceConfig: SorobanType.Factory<MarketplaceConfig> =
  SorobanType
    .Custom.fromSpec<MarketplaceConfig>(
      () => MarketplaceSpec,
      "MarketplaceConfig",
    );

/**
 * Signed fee coverage intent. All amounts use their token's atomic units.
 */
export type VntyPaymentLimit = SorobanType.Custom<{
  kind: "struct";
  fields: {
    /** Exclusive execution deadline in Unix seconds. */
    deadline: SorobanType.U64;
    /** Expected complete protocol fee; prevents an unapproved cash increase. */
    fee_amount: SorobanType.I128;
    /** Exact fee-asset credit purchased by burning VNTY. */
    fee_credit: SorobanType.I128;
    /**
     * Maximum VNTY transferred temporarily, with unused shares refunded
     * atomically.
     */
    max_shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the VntyPaymentLimit factory. */
export type VntyPaymentLimitArgs = SorobanType.Input.Custom<VntyPaymentLimit>;

/** Validate, encode and decode VntyPaymentLimit using its contract declaration. */
export const VntyPaymentLimit: SorobanType.Factory<VntyPaymentLimit> =
  SorobanType
    .Custom.fromSpec<VntyPaymentLimit>(
      () => MarketplaceSpec,
      "VntyPaymentLimit",
    );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by SalePlaced. */
export type SalePlaced = {
  contract_address: SorobanType.Address;
  seller: SorobanType.Address;
  token_id: SorobanType.U32;
  word: SorobanType.String;
  price: SorobanType.I128;
  fee_bps: SorobanType.U32;
};

/** Indexed fields accepted by the SalePlaced event filters. */
export type SalePlacedTopics = {
  contract_address: SorobanType.Input.Address;
  seller: SorobanType.Input.Address;
};

/** Fields emitted by SaleCancelled. */
export type SaleCancelled = {
  contract_address: SorobanType.Address;
  seller: SorobanType.Address;
  token_id: SorobanType.U32;
  word: SorobanType.String;
  price: SorobanType.I128;
  fee_bps: SorobanType.U32;
};

/** Indexed fields accepted by the SaleCancelled event filters. */
export type SaleCancelledTopics = {
  contract_address: SorobanType.Input.Address;
  seller: SorobanType.Input.Address;
};

/** Fields emitted by SaleCompleted. */
export type SaleCompleted = {
  contract_address: SorobanType.Address;
  seller: SorobanType.Address;
  buyer: SorobanType.Address;
  token_id: SorobanType.U32;
  word: SorobanType.String;
  price: SorobanType.I128;
  fee_bps: SorobanType.U32;
  protocol_fee: SorobanType.I128;
  seller_proceeds: SorobanType.I128;
  fee_asset_collected: SorobanType.I128;
  fee_shares_burned: SorobanType.I128;
  fee_shares_value: SorobanType.I128;
};

/** Indexed fields accepted by the SaleCompleted event filters. */
export type SaleCompletedTopics = {
  contract_address: SorobanType.Input.Address;
  seller: SorobanType.Input.Address;
  buyer: SorobanType.Input.Address;
};

/** Fields emitted by TreasuryChanged. */
export type TreasuryChanged = {
  operator: SorobanType.Address;
  previous_treasury: SorobanType.Address;
  new_treasury: SorobanType.Address;
};

/** Indexed fields accepted by the TreasuryChanged event filters. */
export type TreasuryChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by ProtocolFeeChanged. */
export type ProtocolFeeChanged = {
  operator: SorobanType.Address;
  previous_fee_bps: SorobanType.U32;
  new_fee_bps: SorobanType.U32;
};

/** Indexed fields accepted by the ProtocolFeeChanged event filters. */
export type ProtocolFeeChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by ImplementationChanged. */
export type ImplementationChanged = {
  operator: SorobanType.Address;
  new_wasm_hash: SorobanType.BytesN<32>;
};

/** Indexed fields accepted by the ImplementationChanged event filters. */
export type ImplementationChangedTopics = {
  operator: SorobanType.Input.Address;
};

/**
 * Announces the Testnet settlement switch; historical listings retain their
 * original currency.
 */
export type TestnetSettlementChanged = {
  operator: SorobanType.Address;
  previous_asset: SorobanType.Address;
  new_asset: SorobanType.Address;
};

/** Indexed fields accepted by the TestnetSettlementChanged event filters. */
export type TestnetSettlementChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Event emitted when the contract is paused. */
export type Paused = Record<string, never>;

/** Indexed fields accepted by the Paused event filters. */
export type PausedTopics = Record<string, never>;

/** Event emitted when the contract is unpaused. */
export type Unpaused = Record<string, never>;

/** Indexed fields accepted by the Unpaused event filters. */
export type UnpausedTopics = Record<string, never>;

/** Event definitions bound to this client, with typed decoding and filters. */
export type MarketplaceEvents = ContractEventRegistry & {
  readonly SalePlaced: ContractEventDefinition<
    SalePlaced,
    SalePlacedTopics
  >;
  readonly SaleCancelled: ContractEventDefinition<
    SaleCancelled,
    SaleCancelledTopics
  >;
  readonly SaleCompleted: ContractEventDefinition<
    SaleCompleted,
    SaleCompletedTopics
  >;
  readonly TreasuryChanged: ContractEventDefinition<
    TreasuryChanged,
    TreasuryChangedTopics
  >;
  readonly ProtocolFeeChanged: ContractEventDefinition<
    ProtocolFeeChanged,
    ProtocolFeeChangedTopics
  >;
  readonly ImplementationChanged: ContractEventDefinition<
    ImplementationChanged,
    ImplementationChangedTopics
  >;
  readonly TestnetSettlementChanged: ContractEventDefinition<
    TestnetSettlementChanged,
    TestnetSettlementChangedTopics
  >;
  readonly Paused: ContractEventDefinition<
    Paused,
    PausedTopics
  >;
  readonly Unpaused: ContractEventDefinition<
    Unpaused,
    UnpausedTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type MarketplaceConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
