// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Deployer.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  DeployerErrors,
  DeployerSpec,
} from "@/contracts/deployer/constants.ts";
import type {
  DeployerCall,
  DeployerConstructorArgs,
  DeployerEvents,
  DeployerInvocation,
  DeployerInvocationResult,
  DeployerMethod,
  DeployerMethodMap,
  DeployerOutputs,
} from "@/contracts/deployer/types.ts";

export * from "@/contracts/deployer/constants.ts";
export * from "@/contracts/deployer/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Deployer extends Contract {
  /**
   * Burns a vanity plate NFT and deploys its claimed contract address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `token_id` - Vanity plate NFT proving control of the claimed address.
   * * `wasm_hash` - Installed Wasm hash used for the new contract.
   * * `constructor_args` - Arguments forwarded to the deployed contract
   * constructor.
   * * `operator` - NFT owner authorizing the redemption and deployment.
   *
   * # Returns
   *
   * The address of the deployed contract.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `VanityPlateDeployerError::NftNotFound` when no NFT is
   * linked.
   * * Fails with `VanityPlateDeployerError::NotTokenOwner` when `operator`
   * does not own it.
   * * Fails with `VanityPlateDeployerError::ClaimAddressMismatch` for an
   * invalid claim or index.
   * * Fails with `VanityPlateDeployerError::AddressAlreadyDeployed` when
   * occupied.
   * * Propagates NFT errors or deployment errors for invalid Wasm or
   * constructor arguments.
   */
  readonly deployMethod: DeployerMethod<"deploy"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Deploy, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Deploy,
      }),
  };

  /**
   * Returns the NFT contract linked to the deployer.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The linked vanity plate NFT contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateDeployerError::NftNotFound` when no NFT is linked.
   */
  readonly getNft: DeployerMethod<"get_nft"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetNft, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetNft,
      }),
  };

  /**
   * Links the single NFT contract whose claims may be redeemed through this
   * deployer.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `nft` - Vanity plate NFT contract to link.
   * * `operator` - RBAC administrator authorizing the link.
   *
   * # Errors
   *
   * * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
   * unavailable.
   * * Fails with `VanityPlateDeployerError::NftAlreadySet` after an NFT has
   * been linked.
   * * Fails with `VanityPlateDeployerError::InvalidNft` for a non-Wasm or
   * mismatched NFT.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setNft: DeployerMethod<"set_nft"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetNft, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetNft,
      }),
  };

  /**
   * Replaces the deployer implementation with installed Wasm.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed Wasm hash selected as the new
   * implementation.
   * * `operator` - RBAC upgrader authorizing the upgrade.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
   * unavailable.
   * * Propagates role errors from the RBAC contract.
   * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
   */
  readonly upgrade: DeployerMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Returns the RBAC contract used by the deployer.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured RBAC contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
   * unavailable.
   */
  readonly getRbac: DeployerMethod<"get_rbac"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetRbac, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetRbac,
      }),
  };

  /**
   * Derives the contract address this deployer would create from a salt.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `salt` - Deterministic 32-byte deployment salt.
   *
   * # Returns
   *
   * The contract address derived from this deployer and `salt`.
   *
   * # Errors
   *
   * This function emits no contract-defined errors.
   */
  readonly getPredictedAddress: DeployerMethod<"get_predicted_address"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPredictedAddress, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPredictedAddress,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = DeployerErrors, ...args }: DeployerConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(
          DeployerSpec.entries.map((entry) => entry.toXdr("base64")),
        ),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): DeployerEvents {
    return super.events as DeployerEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof DeployerMethodMap>(
    args: DeployerCall<Method>,
  ): Promise<DeployerOutputs[Method]> {
    return await super.read(args) as DeployerOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof DeployerMethodMap>(
    args: DeployerCall<Method> & DeployerInvocation,
  ): Promise<DeployerInvocationResult<DeployerOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<DeployerOutputs[Method]>(
      args.method,
      result,
    );
  }
}
