// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Deployer contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import type { SorobanType } from "@colibri/core";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Burns a vanity plate NFT and deploys its claimed contract address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `token_id` - Vanity plate NFT proving control of the claimed address.
 * * `wasm_hash` - Installed Wasm hash used for the new contract.
 * * `constructor_args` - Arguments forwarded to the deployed contract
 * constructor.
 * * `operator` - NFT owner authorizing the redemption and deployment.
 *
 * # Returns
 *
 * The address of the deployed contract.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `VanityPlateDeployerError::NftNotFound` when no NFT is
 * linked.
 * * Fails with `VanityPlateDeployerError::NotTokenOwner` when `operator`
 * does not own it.
 * * Fails with `VanityPlateDeployerError::ClaimAddressMismatch` for an
 * invalid claim or index.
 * * Fails with `VanityPlateDeployerError::AddressAlreadyDeployed` when
 * occupied.
 * * Propagates NFT errors or deployment errors for invalid Wasm or
 * constructor arguments.
 */
export type DeployInput = {
  token_id: SorobanType.Input.U32;
  wasm_hash: SorobanType.Input.BytesN<32>;
  constructor_args: SorobanType.Input.Vec<
    SorobanType.Input.Val,
    SorobanType.Val
  >;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of deploy. */
export type DeployOutput = SorobanType.Address;

/**
 * Returns the NFT contract linked to the deployer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The linked vanity plate NFT contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateDeployerError::NftNotFound` when no NFT is linked.
 */
export type GetNftInput = Record<string, never>;

/** Decoded return value of get_nft. */
export type GetNftOutput = SorobanType.Address;

/**
 * Links the single NFT contract whose claims may be redeemed through this
 * deployer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `nft` - Vanity plate NFT contract to link.
 * * `operator` - RBAC administrator authorizing the link.
 *
 * # Errors
 *
 * * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
 * unavailable.
 * * Fails with `VanityPlateDeployerError::NftAlreadySet` after an NFT has
 * been linked.
 * * Fails with `VanityPlateDeployerError::InvalidNft` for a non-Wasm or
 * mismatched NFT.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetNftInput = {
  nft: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_nft. */
export type SetNftOutput = null;

/**
 * Replaces the deployer implementation with installed Wasm.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed Wasm hash selected as the new
 * implementation.
 * * `operator` - RBAC upgrader authorizing the upgrade.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
 * unavailable.
 * * Propagates role errors from the RBAC contract.
 * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Returns the RBAC contract used by the deployer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured RBAC contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateDeployerError::RbacNotFound` when RBAC is
 * unavailable.
 */
export type GetRbacInput = Record<string, never>;

/** Decoded return value of get_rbac. */
export type GetRbacOutput = SorobanType.Address;

/**
 * Initializes the deployer with its shared RBAC contract.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `rbac` - RBAC contract used for administrative checks.
 * * `operator` - RBAC administrator authorizing construction.
 *
 * # Errors
 *
 * Propagates authorization and role errors from the RBAC contract.
 */
export type ConstructorInput = {
  rbac: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/**
 * Derives the contract address this deployer would create from a salt.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `salt` - Deterministic 32-byte deployment salt.
 *
 * # Returns
 *
 * The contract address derived from this deployer and `salt`.
 *
 * # Errors
 *
 * This function emits no contract-defined errors.
 */
export type GetPredictedAddressInput = {
  salt: SorobanType.Input.BytesN<32>;
};

/** Decoded return value of get_predicted_address. */
export type GetPredictedAddressOutput = SorobanType.Address;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type DeployerMethodMap = {
  deploy: {
    input: DeployInput;
    output: DeployOutput;
  };
  get_nft: {
    input: GetNftInput;
    output: GetNftOutput;
  };
  set_nft: {
    input: SetNftInput;
    output: SetNftOutput;
  };
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  get_rbac: {
    input: GetRbacInput;
    output: GetRbacOutput;
  };
  get_predicted_address: {
    input: GetPredictedAddressInput;
    output: GetPredictedAddressOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type DeployerInputs = {
  [Method in keyof DeployerMethodMap]: DeployerMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type DeployerOutputs = {
  [Method in keyof DeployerMethodMap]: DeployerMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type DeployerCall<Method extends keyof DeployerMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      DeployerInputs[Name] extends Record<string, never>
        ? { methodArgs?: DeployerInputs[Name] }
        : { methodArgs: DeployerInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type DeployerInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type DeployerInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type DeployerMethod<Method extends keyof DeployerMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: DeployerInputs[Method] extends Record<string, never>
      ? [methodArgs?: DeployerInputs[Method]]
      : [methodArgs: DeployerInputs[Method]]
  ) => Promise<DeployerOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<DeployerCall<Method>, "method"> & DeployerInvocation,
  ) => Promise<DeployerInvocationResult<DeployerOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by NftLinked. */
export type NftLinked = {
  operator: SorobanType.Address;
  nft: SorobanType.Address;
};

/** Indexed fields accepted by the NftLinked event filters. */
export type NftLinkedTopics = {
  operator: SorobanType.Input.Address;
  nft: SorobanType.Input.Address;
};

/** Fields emitted by ContractDeployed. */
export type ContractDeployed = {
  owner: SorobanType.Address;
  token_id: SorobanType.U32;
  contract_address: SorobanType.Address;
};

/** Indexed fields accepted by the ContractDeployed event filters. */
export type ContractDeployedTopics = {
  owner: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type DeployerEvents = ContractEventRegistry & {
  readonly NftLinked: ContractEventDefinition<
    NftLinked,
    NftLinkedTopics
  >;
  readonly ContractDeployed: ContractEventDefinition<
    ContractDeployed,
    ContractDeployedTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type DeployerConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
