// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Nft.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  NftErrors,
  NftSpec,
} from "@/contracts/nft/constants.ts";
import type {
  NftCall,
  NftConstructorArgs,
  NftEvents,
  NftInvocation,
  NftInvocationResult,
  NftMethod,
  NftMethodMap,
  NftOutputs,
} from "@/contracts/nft/types.ts";

export * from "@/contracts/nft/constants.ts";
export * from "@/contracts/nft/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Nft extends Contract {
  /**
   * Consumes a holder-authorized NFT only through the configured deployer or
   * when its represented contract is already deployed.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `from` - Address participating in this operation.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly burn: NftMethod<"burn"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Burn, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Burn,
      }),
  };

  /**
   * Consumes an active reservation and mints its vanity plate NFT.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `salt` - Salt deriving the reserved contract address from the configured
   * deployer.
   *
   * # Returns
   *
   * The full contract hash as a U256 token ID minted to the reservation
   * recipient.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   * * Fails with `VanityPlateNftError::ReservationNotFound` when no active
   * reservation matches.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when the stored suffix no longer
   * matches.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address became occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Propagates standard NFT minting errors.
   */
  readonly mint: NftMethod<"mint"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Mint, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Mint,
      }),
  };

  /**
   * Returns the collection name.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly name: NftMethod<"name"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Name, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Name,
      }),
  };

  /**
   * Returns the collection symbol.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly symbol: NftMethod<"symbol"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Symbol, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Symbol,
      }),
  };

  /**
   * Grants or revokes a token approval with owner or collection operator
   * authorization.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `approver` - Address participating in this operation.
   * * `approved` - Address participating in this operation.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   * * `live_until_ledger` - Inclusive expiry; zero revokes and larger than
   * network maximum is invalid.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly approve: NftMethod<"approve"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Approve, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Approve,
      }),
  };

  /**
   * Returns the number of live NFTs held by an address, or zero.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Address participating in this operation.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly balance: NftMethod<"balance"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Balance, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Balance,
      }),
  };

  /**
   * Reserves a vanity contract address for the paying recipient.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT after
   * minting.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   *
   * # Errors
   *
   * * Fails when `recipient` does not authorize the invocation or cannot pay
   * the fee.
   * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
   * account.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
   * match.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address is occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Fails with `VanityPlateNftError::AddressReserved` when an active
   * reservation exists.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is
   */
  readonly reserve: NftMethod<"reserve"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Reserve, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Reserve,
      }),
  };

  /**
   * Replaces the NFT implementation with installed Wasm.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed Wasm hash selected as the new
   * implementation.
   * * `operator` - RBAC upgrader authorizing the upgrade.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Propagates role errors from the RBAC contract.
   * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
   */
  readonly upgrade: NftMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Returns the RBAC contract used for administrative checks.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured RBAC contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   */
  readonly getRbac: NftMethod<"get_rbac"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetRbac, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetRbac,
      }),
  };

  /**
   * Returns the owner of a live NFT; consumed and unregistered IDs fail.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly ownerOf: NftMethod<"owner_of"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.OwnerOf, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.OwnerOf,
      }),
  };

  /**
   * Transfers a live NFT with owner authorization; its represented address
   * cannot receive it.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `from` - Address participating in this operation.
   * * `to` - Address participating in this operation.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly transfer: NftMethod<"transfer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Transfer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Transfer,
      }),
  };

  /**
   * Returns the single retained record for a contract address, even after
   * consumption.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `contract_address` - Address participating in this operation.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly getPlate: NftMethod<"get_plate"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPlate, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPlate,
      }),
  };

  /**
   * Returns the base URI plus contract address for a live NFT; fails after
   * consumption.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly tokenUri: NftMethod<"token_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.TokenUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.TokenUri,
      }),
  };

  /**
   * Reserves a vanity contract address for a recipient using a separate payer.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `payer` - Address authorizing and paying the reservation fee.
   * * `recipient` - Address that will receive the NFT after minting.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   *
   * # Errors
   *
   * * Fails when `payer` does not authorize the invocation or cannot pay the
   * fee.
   * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
   * account.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
   * match.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address is occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Fails with `VanityPlateNftError::AddressReserved` when an active
   * reservation exists.
   * * Fails with `
   */
  readonly reserveFor: NftMethod<"reserve_for"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveFor, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveFor,
      }),
  };

  /**
   * Returns a live token approval, or None; fails for absent or consumed NFTs.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly getApproved: NftMethod<"get_approved"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetApproved, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetApproved,
      }),
  };

  /**
   * Returns the base URI used to construct token metadata URIs.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The collection's current base URI.
   *
   * # Errors
   *
   * Propagates standard NFT metadata errors when metadata is unavailable.
   */
  readonly getBaseUri: NftMethod<"get_base_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetBaseUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetBaseUri,
      }),
  };

  /**
   * Returns the contract used to derive and deploy vanity addresses.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured deployer contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   */
  readonly getDeployer: NftMethod<"get_deployer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetDeployer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetDeployer,
      }),
  };

  /**
   * Replaces the base URI used by existing and future token metadata URIs.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `base_uri` - New collection-wide base URI.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Propagates authorization and role errors from the RBAC contract.
   * * Propagates standard NFT metadata validation errors.
   */
  readonly setBaseUri: NftMethod<"set_base_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetBaseUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetBaseUri,
      }),
  };

  /**
   * Changes the treasury that processes reservation fees and cashback.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `treasury` - New Wasm-backed treasury contract.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidTreasury` for a non-Wasm or
   * incompatible
   * replacement, existing treasury assets, shares, or redemptions, or a
   * replacement that
   * does not administer the shared reward asset.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setTreasury: NftMethod<"set_treasury"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetTreasury, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetTreasury,
      }),
  };

  /**
   * Transfers a live NFT with owner, token approval, or collection operator
   * authorization.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `spender` - Address participating in this operation.
   * * `from` - Address participating in this operation.
   * * `to` - Address participating in this operation.
   * * `token_id` - Full contract hash as an unsigned big-endian ID.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly transferFrom: NftMethod<"transfer_from"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.TransferFrom, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.TransferFrom,
      }),
  };

  /**
   * Grants or revokes collection-wide operator approval with owner
   * authorization.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Address participating in this operation.
   * * `operator` - Address participating in this operation.
   * * `live_until_ledger` - Inclusive expiry; zero revokes and larger than
   * network maximum is invalid.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly approveForAll: NftMethod<"approve_for_all"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ApproveForAll, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ApproveForAll,
      }),
  };

  /**
   * Returns the active reservation for a predicted contract address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Predicted vanity contract address used as the
   * reservation key.
   *
   * # Returns
   *
   * The active reservation, or `None` when absent or expired.
   *
   * # Errors
   *
   * This function emits no contract-defined errors.
   */
  readonly getReservation: NftMethod<"get_reservation"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetReservation, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetReservation,
      }),
  };

  /**
   * Reserves a pre-farmed catalog address at an administrator-approved price.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying both fees and receiving the NFT after
   * minting.
   * * `contract_address` - Predicted catalog contract address being reserved.
   * * `suffix` - Catalog suffix that must match `contract_address`.
   * * `catalog_price` - Positive catalog price approved for this reservation.
   * * `operator` - RBAC administrator authorizing the supplied catalog price.
   *
   * # Errors
   *
   * * Fails when `recipient` or `operator` does not authorize.
   * * Fails for an invalid suffix, occupied or minted address, or active
   * reservation.
   * * Fails with `VanityPlateNftError::InvalidCatalogPrice` when the supplied
   * price is invalid.
   * * Propagates treasury fee collection and fee-asset transfer errors.
   */
  readonly reserveCatalog: NftMethod<"reserve_catalog"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveCatalog, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveCatalog,
      }),
  };

  /**
   * Returns the beneficiary receiving administrator-approved catalog prices.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The active catalog configuration.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::CatalogConfigNotFound` when unavailable.
   */
  readonly getCatalogConfig: NftMethod<"get_catalog_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetCatalogConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetCatalogConfig,
      }),
  };

  /**
   * Reserves a vanity address using a fixed fee credit and bounded VNTY
   * payment.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `recipient` - Receives the reserved NFT and pays unless a payer is
   * specified.
   * * `contract_address` - Undeployed vanity address to reserve.
   * * `suffix` - Validated plate ending.
   * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
   * deadline.
   *
   * # Errors
   * Propagates reservation validation, occupied-address, authorization, and
   * catalog errors.
   * Treasury rejects expired payments, changed fees, exceeded limits,
   * unavailable NAV,
   * invalid shares, or failed maximum transfer/refund. Failure is atomic.
   */
  readonly reserveWithLimit: NftMethod<"reserve_with_limit"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveWithLimit, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveWithLimit,
      }),
  };

  /**
   * Returns whether the operator permission remains valid through the current
   * ledger.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `owner` - Address participating in this operation.
   * * `operator` - Address participating in this operation.
   *
   * # Returns
   * The requested value.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly isApprovedForAll: NftMethod<"is_approved_for_all"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.IsApprovedForAll, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.IsApprovedForAll,
      }),
  };

  /**
   * Reserves an address while burning reward shares toward the reservation
   * fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   * * `fee_shares` - Treasury reward shares to burn toward the fee.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates reservation validation and treasury share-payment errors.
   */
  readonly reserveWithShares: NftMethod<"reserve_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveWithShares,
      }),
  };

  /**
   * Sets 1..=56 highlighted characters with controller authorization; deployed
   * unregistered contracts can self-register.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `contract_address` - Address participating in this operation.
   * * `character_count` - Number of trailing characters, from one through 56.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails on missing required state, invalid input, or missing required
   * authorization.
   */
  readonly setCharacterCount: NftMethod<"set_character_count"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetCharacterCount, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetCharacterCount,
      }),
  };

  /**
   * Changes the fee charged when creating a reservation.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `fee` - New non-negative reservation fee in fee-asset stroops.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidReservationFee` when `fee` is
   * negative.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setReservationFee: NftMethod<"set_reservation_fee"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetReservationFee, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetReservationFee,
      }),
  };

  /**
   * Derives a vanity contract address from the configured deployer and a salt.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `salt` - Deterministic 32-byte deployment salt.
   *
   * # Returns
   *
   * The contract address derived from the configured deployer and `salt`.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   */
  readonly getPredictedAddress: NftMethod<"get_predicted_address"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPredictedAddress, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPredictedAddress,
      }),
  };

  /**
   * Returns the current reservation fee and duration configuration.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The active reservation configuration.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config is
   * unavailable.
   */
  readonly getReservationConfig: NftMethod<"get_reservation_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetReservationConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetReservationConfig,
      }),
  };

  /**
   * Reserves a vanity address using a fixed fee credit and bounded VNTY
   * payment.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `payer` - Authorizes and pays the fee.
   * * `recipient` - Receives the reserved NFT and pays unless a payer is
   * specified.
   * * `contract_address` - Undeployed vanity address to reserve.
   * * `suffix` - Validated plate ending.
   * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
   * deadline.
   *
   * # Errors
   * Propagates reservation validation, occupied-address, authorization, and
   * catalog errors.
   * Treasury rejects expired payments, changed fees, exceeded limits,
   * unavailable NAV,
   * invalid shares, or failed maximum transfer/refund. Failure is atomic.
   */
  readonly reserveForWithLimit: NftMethod<"reserve_for_with_limit"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveForWithLimit, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveForWithLimit,
      }),
  };

  /**
   * Reserves for another recipient while burning the payer's reward shares
   * toward the fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `payer` - Address authorizing both payment sources.
   * * `recipient` - Address that will receive the NFT.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   * * `fee_shares` - Treasury reward shares to burn toward the fee.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates reservation validation and treasury share-payment errors.
   */
  readonly reserveForWithShares: NftMethod<"reserve_for_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveForWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveForWithShares,
      }),
  };

  /**
   * Changes the account receiving catalog prices.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `beneficiary` - New catalog-price beneficiary.
   * * `operator` - RBAC administrator authorizing the change.
   *
   * # Errors
   *
   * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setCatalogBeneficiary: NftMethod<"set_catalog_beneficiary"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetCatalogBeneficiary, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetCatalogBeneficiary,
      }),
  };

  /**
   * Changes how many ledgers a reservation remains valid.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `duration_ledgers` - Positive reservation lifetime not exceeding the
   * network maximum TTL.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
   * invalid duration.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setReservationDuration: NftMethod<"set_reservation_duration"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetReservationDuration, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetReservationDuration,
      }),
  };

  /**
   * Reserves a vanity address using a fixed fee credit and bounded VNTY
   * payment.
   *
   * # Arguments
   * * `e` - Execution environment.
   * * `recipient` - Receives the reserved NFT and pays unless a payer is
   * specified.
   * * `contract_address` - Undeployed vanity address to reserve.
   * * `suffix` - Validated plate ending.
   * * `catalog_price` - Administrator-approved premium, paid separately in the
   * fee asset.
   * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
   * deadline.
   * * `operator` - RBAC administrator coauthorizing the catalog price.
   *
   * # Errors
   * Propagates reservation validation, occupied-address, authorization, and
   * catalog errors.
   * Treasury rejects expired payments, changed fees, exceeded limits,
   * unavailable NAV,
   * invalid shares, or failed maximum transfer/refund. Failure is atomic.
   */
  readonly reserveCatalogWithLimit: NftMethod<"reserve_catalog_with_limit"> = {
    read: (methodArgs) =>
      this.read({
        method: ContractMethods.ReserveCatalogWithLimit,
        methodArgs,
      }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveCatalogWithLimit,
      }),
  };

  /**
   * Reserves a catalog address while burning reward shares toward the protocol
   * fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT.
   * * `contract_address` - Predicted catalog contract address being reserved.
   * * `suffix` - Catalog suffix that must match `contract_address`.
   * * `catalog_price` - Positive catalog price approved for this reservation.
   * * `fee_shares` - Treasury reward shares to burn toward the protocol fee.
   * * `operator` - RBAC administrator authorizing the supplied catalog price.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates catalog reservation and treasury share-payment errors. The
   * catalog price
   * remains payable in the configured fee asset.
   */
  readonly reserveCatalogWithShares: NftMethod<"reserve_catalog_with_shares"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.ReserveCatalogWithShares,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.ReserveCatalogWithShares,
        }),
    };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = NftErrors, ...args }: NftConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(NftSpec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): NftEvents {
    return super.events as NftEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof NftMethodMap>(
    args: NftCall<Method>,
  ): Promise<NftOutputs[Method]> {
    return await super.read(args) as NftOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof NftMethodMap>(
    args: NftCall<Method> & NftInvocation,
  ): Promise<NftInvocationResult<NftOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<NftOutputs[Method]>(
      args.method,
      result,
    );
  }
}
