// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Nft.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  NftErrors,
  NftSpec,
} from "@/contracts/nft/constants.ts";
import type {
  NftCall,
  NftConstructorArgs,
  NftEvents,
  NftInvocation,
  NftInvocationResult,
  NftMethod,
  NftMethodMap,
  NftOutputs,
} from "@/contracts/nft/types.ts";

export * from "@/contracts/nft/constants.ts";
export * from "@/contracts/nft/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Nft extends Contract {
  /**
   * Burns an owned vanity plate NFT and releases its address for future
   * minting.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `from` - Current owner authorizing the burn.
   * * `token_id` - Token being burned.
   *
   * # Errors
   *
   * * Fails when `from` does not authorize the invocation.
   * * Propagates standard NFT errors when the token does not exist or `from`
   * is not its owner.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly burn: NftMethod<"burn"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Burn, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Burn,
      }),
  };

  /**
   * Consumes an active reservation and mints its vanity plate NFT.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `salt` - Salt deriving the reserved contract address from the configured
   * deployer.
   *
   * # Returns
   *
   * The sequential token ID minted to the reservation recipient.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   * * Fails with `VanityPlateNftError::ReservationNotFound` when no active
   * reservation matches.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when the stored suffix no longer
   * matches.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address became occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Propagates standard NFT minting errors.
   */
  readonly mint: NftMethod<"mint"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Mint, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Mint,
      }),
  };

  /**
   * Returns the token collection name.
   *
   * # Arguments
   *
   * * `e` - Access to the Soroban environment.
   */
  readonly name: NftMethod<"name"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Name, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Name,
      }),
  };

  /**
   * Returns the token collection symbol.
   *
   * # Arguments
   *
   * * `e` - Access to the Soroban environment.
   */
  readonly symbol: NftMethod<"symbol"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Symbol, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Symbol,
      }),
  };

  /**
   * Approves a token spender while renewing its vanity claim and address
   * index.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `approver` - Owner or authorized operator approving the spender.
   * * `approved` - Address receiving approval.
   * * `token_id` - Token covered by the approval.
   * * `live_until_ledger` - Approval expiration ledger, or zero to revoke
   * approval.
   *
   * # Errors
   *
   * * Fails when `approver` does not authorize the invocation.
   * * Propagates standard NFT ownership, approval, and expiration errors.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly approve: NftMethod<"approve"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Approve, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Approve,
      }),
  };

  /**
   * Returns the number of tokens owned by `account`.
   *
   * # Arguments
   *
   * * `e` - Access to the Soroban environment.
   * * `account` - The address for which the balance is being queried.
   */
  readonly balance: NftMethod<"balance"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Balance, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Balance,
      }),
  };

  /**
   * Reserves a vanity contract address for the paying recipient.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT after
   * minting.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   *
   * # Errors
   *
   * * Fails when `recipient` does not authorize the invocation or cannot pay
   * the fee.
   * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
   * account.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
   * match.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address is occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Fails with `VanityPlateNftError::AddressReserved` when an active
   * reservation exists.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is
   */
  readonly reserve: NftMethod<"reserve"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Reserve, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Reserve,
      }),
  };

  /**
   * Replaces the NFT implementation with installed Wasm.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed Wasm hash selected as the new
   * implementation.
   * * `operator` - RBAC upgrader authorizing the upgrade.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Propagates role errors from the RBAC contract.
   * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
   */
  readonly upgrade: NftMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Returns the RBAC contract used for administrative checks.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured RBAC contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   */
  readonly getRbac: NftMethod<"get_rbac"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetRbac, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetRbac,
      }),
  };

  /**
   * Returns a token owner while renewing its vanity claim and address index.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `token_id` - Token whose owner is requested.
   *
   * # Returns
   *
   * The current owner of `token_id`.
   *
   * # Errors
   *
   * * Propagates standard NFT errors when `token_id` does not exist.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly ownerOf: NftMethod<"owner_of"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.OwnerOf, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.OwnerOf,
      }),
  };

  /**
   * Changes the descriptive suffix associated with a claimed address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Claimed vanity contract address being updated.
   * * `word` - New suffix that must match `contract_address`.
   * * `operator` - Current NFT owner authorizing the update.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `VanityPlateNftError::TokenForAddressNotFound` when it is not
   * claimed.
   * * Fails with `VanityPlateNftError::IncorrectOwner` when `operator` is not
   * the owner.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when `word` is invalid or does not
   * match.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly setWord: NftMethod<"set_word"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetWord, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetWord,
      }),
  };

  /**
   * Transfers an owned token while renewing its vanity claim and address
   * index.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `from` - Current owner authorizing the transfer.
   * * `to` - Address receiving the token.
   * * `token_id` - Token being transferred.
   *
   * # Errors
   *
   * * Fails when `from` does not authorize the invocation.
   * * Propagates standard NFT ownership and balance errors.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly transfer: NftMethod<"transfer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Transfer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Transfer,
      }),
  };

  /**
   * Burns a vanity plate NFT through an approved spender and releases its
   * address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `spender` - Approved address authorizing the burn.
   * * `from` - Current token owner.
   * * `token_id` - Token being burned.
   *
   * # Errors
   *
   * * Fails when `spender` does not authorize the invocation.
   * * Propagates standard NFT errors when the token does not exist, `from` is
   * not its owner,
   * or `spender` lacks sufficient approval.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly burnFrom: NftMethod<"burn_from"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.BurnFrom, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.BurnFrom,
      }),
  };

  /**
   * Returns the immutable address and salt plus the latest descriptive suffix
   * for a token.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `token_id` - Token whose vanity claim is requested.
   *
   * # Returns
   *
   * The vanity claim associated with `token_id`, including after the NFT is
   * burned.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::ClaimNotFound` when the token was never
   * minted or its
   * persistent history expired.
   */
  readonly getClaim: NftMethod<"get_claim"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetClaim, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetClaim,
      }),
  };

  /**
   * Returns the metadata URI for an existing vanity plate NFT.
   *
   * The URI is the collection base URI followed by the claimed contract
   * address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `token_id` - Token whose metadata URI is requested.
   *
   * # Returns
   *
   * The token URI, or an empty string when the collection base URI is empty.
   *
   * # Errors
   *
   * * Propagates standard NFT errors when `token_id` does not exist.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly tokenUri: NftMethod<"token_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.TokenUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.TokenUri,
      }),
  };

  /**
   * Reserves a vanity contract address for a recipient using a separate payer.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `payer` - Address authorizing and paying the reservation fee.
   * * `recipient` - Address that will receive the NFT after minting.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   *
   * # Errors
   *
   * * Fails when `payer` does not authorize the invocation or cannot pay the
   * fee.
   * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
   * account.
   * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
   * `VanityPlateNftError::InvalidSuffixCharacter`, or
   * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
   * match.
   * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
   * address is occupied.
   * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
   * claimed.
   * * Fails with `VanityPlateNftError::AddressReserved` when an active
   * reservation exists.
   * * Fails with `
   */
  readonly reserveFor: NftMethod<"reserve_for"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveFor, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveFor,
      }),
  };

  /**
   * Returns the account approved for the token with `token_id`.
   *
   * # Arguments
   *
   * * `e` - Access to the Soroban environment.
   * * `token_id` - Token ID as a number.
   *
   * # Errors
   *
   * * [`NonFungibleTokenError::NonExistentToken`] - If the token does not
   * exist.
   */
  readonly getApproved: NftMethod<"get_approved"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetApproved, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetApproved,
      }),
  };

  /**
   * Returns the base URI used to construct token metadata URIs.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The collection's current base URI.
   *
   * # Errors
   *
   * Propagates standard NFT metadata errors when metadata is unavailable.
   */
  readonly getBaseUri: NftMethod<"get_base_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetBaseUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetBaseUri,
      }),
  };

  /**
   * Returns the contract used to derive and deploy vanity addresses.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The configured deployer contract address.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   */
  readonly getDeployer: NftMethod<"get_deployer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetDeployer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetDeployer,
      }),
  };

  /**
   * Returns the token ID representing a vanity contract address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Claimed vanity contract address.
   *
   * # Returns
   *
   * The token ID associated with `contract_address`.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::TokenForAddressNotFound` when it is not
   * claimed.
   * * Propagates the NFT owner error when ownership storage is unavailable.
   */
  readonly getTokenId: NftMethod<"get_token_id"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetTokenId, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetTokenId,
      }),
  };

  /**
   * Replaces the base URI used by existing and future token metadata URIs.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `base_uri` - New collection-wide base URI.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Propagates authorization and role errors from the RBAC contract.
   * * Propagates standard NFT metadata validation errors.
   */
  readonly setBaseUri: NftMethod<"set_base_uri"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetBaseUri, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetBaseUri,
      }),
  };

  /**
   * Changes the treasury that processes reservation fees and cashback.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `treasury` - New Wasm-backed treasury contract.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidTreasury` for a non-Wasm or
   * incompatible
   * replacement, existing treasury assets, shares, or redemptions, or a
   * replacement that
   * does not administer the shared reward asset.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setTreasury: NftMethod<"set_treasury"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetTreasury, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetTreasury,
      }),
  };

  /**
   * Transfers an approved token while renewing its vanity claim and address
   * index.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `spender` - Approved address authorizing the transfer.
   * * `from` - Current token owner.
   * * `to` - Address receiving the token.
   * * `token_id` - Token being transferred.
   *
   * # Errors
   *
   * * Fails when `spender` does not authorize the invocation.
   * * Propagates standard NFT approval, ownership, and balance errors.
   * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
   * inconsistent.
   */
  readonly transferFrom: NftMethod<"transfer_from"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.TransferFrom, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.TransferFrom,
      }),
  };

  /**
   * Approve or remove `operator` as an operator for the owner.
   *
   * Operators can call `transfer_from()` for any token held by `owner`,
   * and call `approve()` on behalf of `owner`.
   *
   * # Arguments
   *
   * * `e` - Access to Soroban environment.
   * * `owner` - The address holding the tokens.
   * * `operator` - Account to add to the set of authorized operators.
   * * `live_until_ledger` - The ledger number at which the allowance
   * expires. If `live_until_ledger` is `0`, the approval is revoked.
   *
   * # Errors
   *
   * * [`NonFungibleTokenError::InvalidLiveUntilLedger`] - If the ledger
   * number is less than the current ledger number.
   *
   * # Events
   *
   * * topics - `["approve_for_all", from: Address]`
   * * data - `[operator: Address, live_until_ledger: u32]`
   */
  readonly approveForAll: NftMethod<"approve_for_all"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ApproveForAll, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ApproveForAll,
      }),
  };

  /**
   * Returns the active reservation for a predicted contract address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Predicted vanity contract address used as the
   * reservation key.
   *
   * # Returns
   *
   * The active reservation, or `None` when absent or expired.
   *
   * # Errors
   *
   * This function emits no contract-defined errors.
   */
  readonly getReservation: NftMethod<"get_reservation"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetReservation, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetReservation,
      }),
  };

  /**
   * Reserves a pre-farmed catalog address at an administrator-approved price.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying both fees and receiving the NFT after
   * minting.
   * * `contract_address` - Predicted catalog contract address being reserved.
   * * `suffix` - Catalog suffix that must match `contract_address`.
   * * `catalog_price` - Positive catalog price approved for this reservation.
   * * `operator` - RBAC administrator authorizing the supplied catalog price.
   *
   * # Errors
   *
   * * Fails when `recipient` or `operator` does not authorize.
   * * Fails for an invalid suffix, occupied or minted address, or active
   * reservation.
   * * Fails with `VanityPlateNftError::InvalidCatalogPrice` when the supplied
   * price is invalid.
   * * Propagates treasury fee collection and fee-asset transfer errors.
   */
  readonly reserveCatalog: NftMethod<"reserve_catalog"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveCatalog, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveCatalog,
      }),
  };

  /**
   * Returns a durable vanity claim together with its active or burned status.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `token_id` - Token whose current lifecycle status is requested.
   *
   * # Returns
   *
   * The immutable claim data and whether the NFT remains active or has been
   * burned.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::ClaimNotFound` when the token was never
   * minted or its
   * persistent history expired.
   */
  readonly getClaimRecord: NftMethod<"get_claim_record"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetClaimRecord, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetClaimRecord,
      }),
  };

  /**
   * Returns the beneficiary receiving administrator-approved catalog prices.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The active catalog configuration.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::CatalogConfigNotFound` when unavailable.
   */
  readonly getCatalogConfig: NftMethod<"get_catalog_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetCatalogConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetCatalogConfig,
      }),
  };

  /**
   * Returns the newest token ever minted for a vanity contract address.
   *
   * Unlike `get_token_id`, this historical lookup also succeeds when the
   * newest NFT was
   * burned. If the same undeployed address is minted again, it returns that
   * replacement token.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `contract_address` - Vanity contract address to inspect.
   *
   * # Returns
   *
   * The most recently minted token ID for the address.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::TokenForAddressNotFound` when no retained
   * history exists.
   */
  readonly getLatestTokenId: NftMethod<"get_latest_token_id"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetLatestTokenId, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetLatestTokenId,
      }),
  };

  /**
   * Returns whether the `operator` is allowed to manage all the assets of
   * `owner`.
   *
   * # Arguments
   *
   * * `e` - Access to the Soroban environment.
   * * `owner` - Account of the token's owner.
   * * `operator` - Account to be checked.
   */
  readonly isApprovedForAll: NftMethod<"is_approved_for_all"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.IsApprovedForAll, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.IsApprovedForAll,
      }),
  };

  /**
   * Reserves an address while burning reward shares toward the reservation
   * fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   * * `fee_shares` - Treasury reward shares to burn toward the fee.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates reservation validation and treasury share-payment errors.
   */
  readonly reserveWithShares: NftMethod<"reserve_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveWithShares,
      }),
  };

  /**
   * Changes the fee charged when creating a reservation.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `fee` - New non-negative reservation fee in fee-asset stroops.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidReservationFee` when `fee` is
   * negative.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setReservationFee: NftMethod<"set_reservation_fee"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetReservationFee, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetReservationFee,
      }),
  };

  /**
   * Derives a vanity contract address from the configured deployer and a salt.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `salt` - Deterministic 32-byte deployment salt.
   *
   * # Returns
   *
   * The contract address derived from the configured deployer and `salt`.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
   * configured.
   */
  readonly getPredictedAddress: NftMethod<"get_predicted_address"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetPredictedAddress, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetPredictedAddress,
      }),
  };

  /**
   * Initializes reservation and catalog configuration after upgrading
   * compatible legacy state.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `reservation_config` - Treasury, reservation fee, and duration to
   * initialize.
   * * `catalog_config` - Beneficiary receiving administrator-approved catalog
   * prices.
   * * `operator` - RBAC administrator authorizing the one-time migration.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::ReservationConfigAlreadySet` if
   * reservations exist.
   * * Fails with `VanityPlateNftError::CatalogConfigAlreadySet` if catalog
   * settings exist.
   * * Fails with `VanityPlateNftError::InvalidTreasury` for incompatible
   * treasury governance.
   * * Fails with `VanityPlateNftError::InvalidReservationFee` for a negative
   * fee.
   * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
   * invalid duration.
   * * Propagates authorization, RBAC, and treasury-interface errors.
   */
  readonly migrateConfiguration: NftMethod<"migrate_configuration"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.MigrateConfiguration, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.MigrateConfiguration,
      }),
  };

  /**
   * Returns the current reservation fee and duration configuration.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   *
   * # Returns
   *
   * The active reservation configuration.
   *
   * # Errors
   *
   * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config is
   * unavailable.
   */
  readonly getReservationConfig: NftMethod<"get_reservation_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetReservationConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetReservationConfig,
      }),
  };

  /**
   * Initializes catalog configuration after upgrading a pre-catalog
   * deployment.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `catalog_config` - Beneficiary receiving administrator-approved catalog
   * prices.
   * * `operator` - RBAC administrator authorizing the migration.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::CatalogConfigAlreadySet` after
   * initialization.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when
   * reservations were not
   * initialized and the complete configuration migration is required instead.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly migrateCatalogConfig: NftMethod<"migrate_catalog_config"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.MigrateCatalogConfig, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.MigrateCatalogConfig,
      }),
  };

  /**
   * Reserves for another recipient while burning the payer's reward shares
   * toward the fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `payer` - Address authorizing both payment sources.
   * * `recipient` - Address that will receive the NFT.
   * * `contract_address` - Predicted vanity contract address being reserved.
   * * `suffix` - Claimed suffix that must match `contract_address`.
   * * `fee_shares` - Treasury reward shares to burn toward the fee.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates reservation validation and treasury share-payment errors.
   */
  readonly reserveForWithShares: NftMethod<"reserve_for_with_shares"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ReserveForWithShares, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ReserveForWithShares,
      }),
  };

  /**
   * Changes the account receiving catalog prices.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `beneficiary` - New catalog-price beneficiary.
   * * `operator` - RBAC administrator authorizing the change.
   *
   * # Errors
   *
   * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setCatalogBeneficiary: NftMethod<"set_catalog_beneficiary"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetCatalogBeneficiary, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetCatalogBeneficiary,
      }),
  };

  /**
   * Changes how many ledgers a reservation remains valid.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `duration_ledgers` - Positive reservation lifetime not exceeding the
   * network maximum TTL.
   * * `operator` - RBAC administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
   * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
   * is unavailable.
   * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
   * invalid duration.
   * * Propagates authorization and role errors from the RBAC contract.
   */
  readonly setReservationDuration: NftMethod<"set_reservation_duration"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetReservationDuration, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetReservationDuration,
      }),
  };

  /**
   * Reserves a catalog address while burning reward shares toward the protocol
   * fee.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `recipient` - Address paying the fee and receiving the NFT.
   * * `contract_address` - Predicted catalog contract address being reserved.
   * * `suffix` - Catalog suffix that must match `contract_address`.
   * * `catalog_price` - Positive catalog price approved for this reservation.
   * * `fee_shares` - Treasury reward shares to burn toward the protocol fee.
   * * `operator` - RBAC administrator authorizing the supplied catalog price.
   *
   * # Errors
   *
   * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
   * shares or shares
   * supplied when the reservation fee is zero.
   * * Propagates catalog reservation and treasury share-payment errors. The
   * catalog price
   * remains payable in the configured fee asset.
   */
  readonly reserveCatalogWithShares: NftMethod<"reserve_catalog_with_shares"> =
    {
      read: (methodArgs) =>
        this.read({
          method: ContractMethods.ReserveCatalogWithShares,
          methodArgs,
        }),
      invoke: (args) =>
        this.invoke({
          ...args,
          method: ContractMethods.ReserveCatalogWithShares,
        }),
    };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = NftErrors, ...args }: NftConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(NftSpec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): NftEvents {
    return super.events as NftEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof NftMethodMap>(
    args: NftCall<Method>,
  ): Promise<NftOutputs[Method]> {
    return await super.read(args) as NftOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof NftMethodMap>(
    args: NftCall<Method> & NftInvocation,
  ): Promise<NftInvocationResult<NftOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<NftOutputs[Method]>(
      args.method,
      result,
    );
  }
}
