// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Nft contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { NftSpec } from "@/contracts/nft/constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Burns an owned vanity plate NFT and releases its address for future
 * minting.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `from` - Current owner authorizing the burn.
 * * `token_id` - Token being burned.
 *
 * # Errors
 *
 * * Fails when `from` does not authorize the invocation.
 * * Propagates standard NFT errors when the token does not exist or `from`
 * is not its owner.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type BurnInput = {
  from: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of burn. */
export type BurnOutput = null;

/**
 * Consumes an active reservation and mints its vanity plate NFT.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `salt` - Salt deriving the reserved contract address from the configured
 * deployer.
 *
 * # Returns
 *
 * The sequential token ID minted to the reservation recipient.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 * * Fails with `VanityPlateNftError::ReservationNotFound` when no active
 * reservation matches.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when the stored suffix no longer
 * matches.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address became occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Propagates standard NFT minting errors.
 */
export type MintInput = {
  salt: SorobanType.Input.BytesN<32>;
};

/** Decoded return value of mint. */
export type MintOutput = SorobanType.U32;

/**
 * Returns the token collection name.
 *
 * # Arguments
 *
 * * `e` - Access to the Soroban environment.
 */
export type NameInput = Record<string, never>;

/** Decoded return value of name. */
export type NameOutput = SorobanType.String;

/**
 * Returns the token collection symbol.
 *
 * # Arguments
 *
 * * `e` - Access to the Soroban environment.
 */
export type SymbolInput = Record<string, never>;

/** Decoded return value of symbol. */
export type SymbolOutput = SorobanType.String;

/**
 * Approves a token spender while renewing its vanity claim and address
 * index.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `approver` - Owner or authorized operator approving the spender.
 * * `approved` - Address receiving approval.
 * * `token_id` - Token covered by the approval.
 * * `live_until_ledger` - Approval expiration ledger, or zero to revoke
 * approval.
 *
 * # Errors
 *
 * * Fails when `approver` does not authorize the invocation.
 * * Propagates standard NFT ownership, approval, and expiration errors.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type ApproveInput = {
  approver: SorobanType.Input.Address;
  approved: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
  live_until_ledger: SorobanType.Input.U32;
};

/** Decoded return value of approve. */
export type ApproveOutput = null;

/**
 * Returns the number of tokens owned by `account`.
 *
 * # Arguments
 *
 * * `e` - Access to the Soroban environment.
 * * `account` - The address for which the balance is being queried.
 */
export type BalanceInput = {
  account: SorobanType.Input.Address;
};

/** Decoded return value of balance. */
export type BalanceOutput = SorobanType.U32;

/**
 * Reserves a vanity contract address for the paying recipient.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT after
 * minting.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 *
 * # Errors
 *
 * * Fails when `recipient` does not authorize the invocation or cannot pay
 * the fee.
 * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
 * account.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
 * match.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address is occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Fails with `VanityPlateNftError::AddressReserved` when an active
 * reservation exists.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is
 */
export type ReserveInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
};

/** Decoded return value of reserve. */
export type ReserveOutput = null;

/**
 * Replaces the NFT implementation with installed Wasm.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed Wasm hash selected as the new
 * implementation.
 * * `operator` - RBAC upgrader authorizing the upgrade.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Propagates role errors from the RBAC contract.
 * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Returns the RBAC contract used for administrative checks.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured RBAC contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 */
export type GetRbacInput = Record<string, never>;

/** Decoded return value of get_rbac. */
export type GetRbacOutput = SorobanType.Address;

/**
 * Returns a token owner while renewing its vanity claim and address index.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `token_id` - Token whose owner is requested.
 *
 * # Returns
 *
 * The current owner of `token_id`.
 *
 * # Errors
 *
 * * Propagates standard NFT errors when `token_id` does not exist.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type OwnerOfInput = {
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of owner_of. */
export type OwnerOfOutput = SorobanType.Address;

/**
 * Changes the descriptive suffix associated with a claimed address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Claimed vanity contract address being updated.
 * * `word` - New suffix that must match `contract_address`.
 * * `operator` - Current NFT owner authorizing the update.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `VanityPlateNftError::TokenForAddressNotFound` when it is not
 * claimed.
 * * Fails with `VanityPlateNftError::IncorrectOwner` when `operator` is not
 * the owner.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when `word` is invalid or does not
 * match.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type SetWordInput = {
  contract_address: SorobanType.Input.Address;
  word: SorobanType.Input.String;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_word. */
export type SetWordOutput = null;

/**
 * Transfers an owned token while renewing its vanity claim and address
 * index.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `from` - Current owner authorizing the transfer.
 * * `to` - Address receiving the token.
 * * `token_id` - Token being transferred.
 *
 * # Errors
 *
 * * Fails when `from` does not authorize the invocation.
 * * Propagates standard NFT ownership and balance errors.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type TransferInput = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of transfer. */
export type TransferOutput = null;

/**
 * Burns a vanity plate NFT through an approved spender and releases its
 * address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `spender` - Approved address authorizing the burn.
 * * `from` - Current token owner.
 * * `token_id` - Token being burned.
 *
 * # Errors
 *
 * * Fails when `spender` does not authorize the invocation.
 * * Propagates standard NFT errors when the token does not exist, `from` is
 * not its owner,
 * or `spender` lacks sufficient approval.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type BurnFromInput = {
  spender: SorobanType.Input.Address;
  from: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of burn_from. */
export type BurnFromOutput = null;

/**
 * Returns the immutable address and salt plus the latest descriptive suffix
 * for a token.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `token_id` - Token whose vanity claim is requested.
 *
 * # Returns
 *
 * The vanity claim associated with `token_id`, including after the NFT is
 * burned.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::ClaimNotFound` when the token was never
 * minted or its
 * persistent history expired.
 */
export type GetClaimInput = {
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of get_claim. */
export type GetClaimOutput = VanityClaim;

/**
 * Returns the metadata URI for an existing vanity plate NFT.
 *
 * The URI is the collection base URI followed by the claimed contract
 * address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `token_id` - Token whose metadata URI is requested.
 *
 * # Returns
 *
 * The token URI, or an empty string when the collection base URI is empty.
 *
 * # Errors
 *
 * * Propagates standard NFT errors when `token_id` does not exist.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type TokenUriInput = {
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of token_uri. */
export type TokenUriOutput = SorobanType.String;

/**
 * Reserves a vanity contract address for a recipient using a separate payer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `payer` - Address authorizing and paying the reservation fee.
 * * `recipient` - Address that will receive the NFT after minting.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 *
 * # Errors
 *
 * * Fails when `payer` does not authorize the invocation or cannot pay the
 * fee.
 * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
 * account.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
 * match.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address is occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Fails with `VanityPlateNftError::AddressReserved` when an active
 * reservation exists.
 * * Fails with `
 */
export type ReserveForInput = {
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
};

/** Decoded return value of reserve_for. */
export type ReserveForOutput = null;

/**
 * Returns the account approved for the token with `token_id`.
 *
 * # Arguments
 *
 * * `e` - Access to the Soroban environment.
 * * `token_id` - Token ID as a number.
 *
 * # Errors
 *
 * * [`NonFungibleTokenError::NonExistentToken`] - If the token does not
 * exist.
 */
export type GetApprovedInput = {
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of get_approved. */
export type GetApprovedOutput = SorobanType.Option<SorobanType.Address>;

/**
 * Returns the base URI used to construct token metadata URIs.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The collection's current base URI.
 *
 * # Errors
 *
 * Propagates standard NFT metadata errors when metadata is unavailable.
 */
export type GetBaseUriInput = Record<string, never>;

/** Decoded return value of get_base_uri. */
export type GetBaseUriOutput = SorobanType.String;

/**
 * Returns the contract used to derive and deploy vanity addresses.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured deployer contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 */
export type GetDeployerInput = Record<string, never>;

/** Decoded return value of get_deployer. */
export type GetDeployerOutput = SorobanType.Address;

/**
 * Returns the token ID representing a vanity contract address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Claimed vanity contract address.
 *
 * # Returns
 *
 * The token ID associated with `contract_address`.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::TokenForAddressNotFound` when it is not
 * claimed.
 * * Propagates the NFT owner error when ownership storage is unavailable.
 */
export type GetTokenIdInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_token_id. */
export type GetTokenIdOutput = SorobanType.U32;

/**
 * Replaces the base URI used by existing and future token metadata URIs.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `base_uri` - New collection-wide base URI.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Propagates authorization and role errors from the RBAC contract.
 * * Propagates standard NFT metadata validation errors.
 */
export type SetBaseUriInput = {
  base_uri: SorobanType.Input.String;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_base_uri. */
export type SetBaseUriOutput = null;

/**
 * Changes the treasury that processes reservation fees and cashback.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `treasury` - New Wasm-backed treasury contract.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidTreasury` for a non-Wasm or
 * incompatible
 * replacement, existing treasury assets, shares, or redemptions, or a
 * replacement that
 * does not administer the shared reward asset.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetTreasuryInput = {
  treasury: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_treasury. */
export type SetTreasuryOutput = null;

/**
 * Initializes the vanity plate NFT collection and reservation policy.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `rbac` - RBAC contract used for administrative checks.
 * * `deployer` - Wasm contract whose address and salts derive vanity
 * contract addresses.
 * * `base_uri` - Base URI prepended to each claimed contract address.
 * * `reservation_config` - Treasury, fee, and reservation duration.
 * * `catalog_config` - Beneficiary receiving administrator-approved catalog
 * prices.
 * * `operator` - RBAC administrator authorizing construction.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidDeployer` for a non-Wasm
 * deployer, incompatible
 * deployer interface or governance, or an existing link to another NFT
 * collection.
 * * Fails with `VanityPlateNftError::InvalidTreasury` for incompatible
 * treasury governance,
 * an undeployed fee or reward asset, or a non-Wasm treasury.
 * * Fails with `VanityPlateNftError::InvalidReservationFee` for a negative
 * fee.
 * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an inv
 */
export type ConstructorInput = {
  rbac: SorobanType.Input.Address;
  deployer: SorobanType.Input.Address;
  base_uri: SorobanType.Input.String;
  reservation_config: ReservationConfigArgs;
  catalog_config: CatalogConfigArgs;
  operator: SorobanType.Input.Address;
};

/**
 * Transfers an approved token while renewing its vanity claim and address
 * index.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `spender` - Approved address authorizing the transfer.
 * * `from` - Current token owner.
 * * `to` - Address receiving the token.
 * * `token_id` - Token being transferred.
 *
 * # Errors
 *
 * * Fails when `spender` does not authorize the invocation.
 * * Propagates standard NFT approval, ownership, and balance errors.
 * * Fails with `VanityPlateNftError::ClaimNotFound` when claim storage is
 * inconsistent.
 */
export type TransferFromInput = {
  spender: SorobanType.Input.Address;
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of transfer_from. */
export type TransferFromOutput = null;

/**
 * Approve or remove `operator` as an operator for the owner.
 *
 * Operators can call `transfer_from()` for any token held by `owner`,
 * and call `approve()` on behalf of `owner`.
 *
 * # Arguments
 *
 * * `e` - Access to Soroban environment.
 * * `owner` - The address holding the tokens.
 * * `operator` - Account to add to the set of authorized operators.
 * * `live_until_ledger` - The ledger number at which the allowance
 * expires. If `live_until_ledger` is `0`, the approval is revoked.
 *
 * # Errors
 *
 * * [`NonFungibleTokenError::InvalidLiveUntilLedger`] - If the ledger
 * number is less than the current ledger number.
 *
 * # Events
 *
 * * topics - `["approve_for_all", from: Address]`
 * * data - `[operator: Address, live_until_ledger: u32]`
 */
export type ApproveForAllInput = {
  owner: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
  live_until_ledger: SorobanType.Input.U32;
};

/** Decoded return value of approve_for_all. */
export type ApproveForAllOutput = null;

/**
 * Returns the active reservation for a predicted contract address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Predicted vanity contract address used as the
 * reservation key.
 *
 * # Returns
 *
 * The active reservation, or `None` when absent or expired.
 *
 * # Errors
 *
 * This function emits no contract-defined errors.
 */
export type GetReservationInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_reservation. */
export type GetReservationOutput = SorobanType.Option<MintReservation>;

/**
 * Reserves a pre-farmed catalog address at an administrator-approved price.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying both fees and receiving the NFT after
 * minting.
 * * `contract_address` - Predicted catalog contract address being reserved.
 * * `suffix` - Catalog suffix that must match `contract_address`.
 * * `catalog_price` - Positive catalog price approved for this reservation.
 * * `operator` - RBAC administrator authorizing the supplied catalog price.
 *
 * # Errors
 *
 * * Fails when `recipient` or `operator` does not authorize.
 * * Fails for an invalid suffix, occupied or minted address, or active
 * reservation.
 * * Fails with `VanityPlateNftError::InvalidCatalogPrice` when the supplied
 * price is invalid.
 * * Propagates treasury fee collection and fee-asset transfer errors.
 */
export type ReserveCatalogInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  catalog_price: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of reserve_catalog. */
export type ReserveCatalogOutput = null;

/**
 * Returns a durable vanity claim together with its active or burned status.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `token_id` - Token whose current lifecycle status is requested.
 *
 * # Returns
 *
 * The immutable claim data and whether the NFT remains active or has been
 * burned.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::ClaimNotFound` when the token was never
 * minted or its
 * persistent history expired.
 */
export type GetClaimRecordInput = {
  token_id: SorobanType.Input.U32;
};

/** Decoded return value of get_claim_record. */
export type GetClaimRecordOutput = VanityClaimRecord;

/**
 * Returns the beneficiary receiving administrator-approved catalog prices.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The active catalog configuration.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::CatalogConfigNotFound` when unavailable.
 */
export type GetCatalogConfigInput = Record<string, never>;

/** Decoded return value of get_catalog_config. */
export type GetCatalogConfigOutput = CatalogConfig;

/**
 * Returns the newest token ever minted for a vanity contract address.
 *
 * Unlike `get_token_id`, this historical lookup also succeeds when the
 * newest NFT was
 * burned. If the same undeployed address is minted again, it returns that
 * replacement token.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Vanity contract address to inspect.
 *
 * # Returns
 *
 * The most recently minted token ID for the address.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::TokenForAddressNotFound` when no retained
 * history exists.
 */
export type GetLatestTokenIdInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_latest_token_id. */
export type GetLatestTokenIdOutput = SorobanType.U32;

/**
 * Returns whether the `operator` is allowed to manage all the assets of
 * `owner`.
 *
 * # Arguments
 *
 * * `e` - Access to the Soroban environment.
 * * `owner` - Account of the token's owner.
 * * `operator` - Account to be checked.
 */
export type IsApprovedForAllInput = {
  owner: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of is_approved_for_all. */
export type IsApprovedForAllOutput = SorobanType.Bool;

/**
 * Reserves an address while burning reward shares toward the reservation
 * fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 * * `fee_shares` - Treasury reward shares to burn toward the fee.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates reservation validation and treasury share-payment errors.
 */
export type ReserveWithSharesInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of reserve_with_shares. */
export type ReserveWithSharesOutput = null;

/**
 * Changes the fee charged when creating a reservation.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `fee` - New non-negative reservation fee in fee-asset stroops.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidReservationFee` when `fee` is
 * negative.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetReservationFeeInput = {
  fee: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_reservation_fee. */
export type SetReservationFeeOutput = null;

/**
 * Derives a vanity contract address from the configured deployer and a salt.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `salt` - Deterministic 32-byte deployment salt.
 *
 * # Returns
 *
 * The contract address derived from the configured deployer and `salt`.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 */
export type GetPredictedAddressInput = {
  salt: SorobanType.Input.BytesN<32>;
};

/** Decoded return value of get_predicted_address. */
export type GetPredictedAddressOutput = SorobanType.Address;

/**
 * Initializes reservation and catalog configuration after upgrading
 * compatible legacy state.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `reservation_config` - Treasury, reservation fee, and duration to
 * initialize.
 * * `catalog_config` - Beneficiary receiving administrator-approved catalog
 * prices.
 * * `operator` - RBAC administrator authorizing the one-time migration.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::ReservationConfigAlreadySet` if
 * reservations exist.
 * * Fails with `VanityPlateNftError::CatalogConfigAlreadySet` if catalog
 * settings exist.
 * * Fails with `VanityPlateNftError::InvalidTreasury` for incompatible
 * treasury governance.
 * * Fails with `VanityPlateNftError::InvalidReservationFee` for a negative
 * fee.
 * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
 * invalid duration.
 * * Propagates authorization, RBAC, and treasury-interface errors.
 */
export type MigrateConfigurationInput = {
  reservation_config: ReservationConfigArgs;
  catalog_config: CatalogConfigArgs;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of migrate_configuration. */
export type MigrateConfigurationOutput = null;

/**
 * Returns the current reservation fee and duration configuration.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The active reservation configuration.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config is
 * unavailable.
 */
export type GetReservationConfigInput = Record<string, never>;

/** Decoded return value of get_reservation_config. */
export type GetReservationConfigOutput = ReservationConfig;

/**
 * Initializes catalog configuration after upgrading a pre-catalog
 * deployment.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `catalog_config` - Beneficiary receiving administrator-approved catalog
 * prices.
 * * `operator` - RBAC administrator authorizing the migration.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::CatalogConfigAlreadySet` after
 * initialization.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when
 * reservations were not
 * initialized and the complete configuration migration is required instead.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type MigrateCatalogConfigInput = {
  catalog_config: CatalogConfigArgs;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of migrate_catalog_config. */
export type MigrateCatalogConfigOutput = null;

/**
 * Reserves for another recipient while burning the payer's reward shares
 * toward the fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `payer` - Address authorizing both payment sources.
 * * `recipient` - Address that will receive the NFT.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 * * `fee_shares` - Treasury reward shares to burn toward the fee.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates reservation validation and treasury share-payment errors.
 */
export type ReserveForWithSharesInput = {
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of reserve_for_with_shares. */
export type ReserveForWithSharesOutput = null;

/**
 * Changes the account receiving catalog prices.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `beneficiary` - New catalog-price beneficiary.
 * * `operator` - RBAC administrator authorizing the change.
 *
 * # Errors
 *
 * Propagates authorization and role errors from the RBAC contract.
 */
export type SetCatalogBeneficiaryInput = {
  beneficiary: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_catalog_beneficiary. */
export type SetCatalogBeneficiaryOutput = null;

/**
 * Changes how many ledgers a reservation remains valid.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `duration_ledgers` - Positive reservation lifetime not exceeding the
 * network maximum TTL.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
 * invalid duration.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetReservationDurationInput = {
  duration_ledgers: SorobanType.Input.U32;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_reservation_duration. */
export type SetReservationDurationOutput = null;

/**
 * Reserves a catalog address while burning reward shares toward the protocol
 * fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT.
 * * `contract_address` - Predicted catalog contract address being reserved.
 * * `suffix` - Catalog suffix that must match `contract_address`.
 * * `catalog_price` - Positive catalog price approved for this reservation.
 * * `fee_shares` - Treasury reward shares to burn toward the protocol fee.
 * * `operator` - RBAC administrator authorizing the supplied catalog price.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates catalog reservation and treasury share-payment errors. The
 * catalog price
 * remains payable in the configured fee asset.
 */
export type ReserveCatalogWithSharesInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  catalog_price: SorobanType.Input.I128;
  fee_shares: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of reserve_catalog_with_shares. */
export type ReserveCatalogWithSharesOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type NftMethodMap = {
  burn: {
    input: BurnInput;
    output: BurnOutput;
  };
  mint: {
    input: MintInput;
    output: MintOutput;
  };
  name: {
    input: NameInput;
    output: NameOutput;
  };
  symbol: {
    input: SymbolInput;
    output: SymbolOutput;
  };
  approve: {
    input: ApproveInput;
    output: ApproveOutput;
  };
  balance: {
    input: BalanceInput;
    output: BalanceOutput;
  };
  reserve: {
    input: ReserveInput;
    output: ReserveOutput;
  };
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  get_rbac: {
    input: GetRbacInput;
    output: GetRbacOutput;
  };
  owner_of: {
    input: OwnerOfInput;
    output: OwnerOfOutput;
  };
  set_word: {
    input: SetWordInput;
    output: SetWordOutput;
  };
  transfer: {
    input: TransferInput;
    output: TransferOutput;
  };
  burn_from: {
    input: BurnFromInput;
    output: BurnFromOutput;
  };
  get_claim: {
    input: GetClaimInput;
    output: GetClaimOutput;
  };
  token_uri: {
    input: TokenUriInput;
    output: TokenUriOutput;
  };
  reserve_for: {
    input: ReserveForInput;
    output: ReserveForOutput;
  };
  get_approved: {
    input: GetApprovedInput;
    output: GetApprovedOutput;
  };
  get_base_uri: {
    input: GetBaseUriInput;
    output: GetBaseUriOutput;
  };
  get_deployer: {
    input: GetDeployerInput;
    output: GetDeployerOutput;
  };
  get_token_id: {
    input: GetTokenIdInput;
    output: GetTokenIdOutput;
  };
  set_base_uri: {
    input: SetBaseUriInput;
    output: SetBaseUriOutput;
  };
  set_treasury: {
    input: SetTreasuryInput;
    output: SetTreasuryOutput;
  };
  transfer_from: {
    input: TransferFromInput;
    output: TransferFromOutput;
  };
  approve_for_all: {
    input: ApproveForAllInput;
    output: ApproveForAllOutput;
  };
  get_reservation: {
    input: GetReservationInput;
    output: GetReservationOutput;
  };
  reserve_catalog: {
    input: ReserveCatalogInput;
    output: ReserveCatalogOutput;
  };
  get_claim_record: {
    input: GetClaimRecordInput;
    output: GetClaimRecordOutput;
  };
  get_catalog_config: {
    input: GetCatalogConfigInput;
    output: GetCatalogConfigOutput;
  };
  get_latest_token_id: {
    input: GetLatestTokenIdInput;
    output: GetLatestTokenIdOutput;
  };
  is_approved_for_all: {
    input: IsApprovedForAllInput;
    output: IsApprovedForAllOutput;
  };
  reserve_with_shares: {
    input: ReserveWithSharesInput;
    output: ReserveWithSharesOutput;
  };
  set_reservation_fee: {
    input: SetReservationFeeInput;
    output: SetReservationFeeOutput;
  };
  get_predicted_address: {
    input: GetPredictedAddressInput;
    output: GetPredictedAddressOutput;
  };
  migrate_configuration: {
    input: MigrateConfigurationInput;
    output: MigrateConfigurationOutput;
  };
  get_reservation_config: {
    input: GetReservationConfigInput;
    output: GetReservationConfigOutput;
  };
  migrate_catalog_config: {
    input: MigrateCatalogConfigInput;
    output: MigrateCatalogConfigOutput;
  };
  reserve_for_with_shares: {
    input: ReserveForWithSharesInput;
    output: ReserveForWithSharesOutput;
  };
  set_catalog_beneficiary: {
    input: SetCatalogBeneficiaryInput;
    output: SetCatalogBeneficiaryOutput;
  };
  set_reservation_duration: {
    input: SetReservationDurationInput;
    output: SetReservationDurationOutput;
  };
  reserve_catalog_with_shares: {
    input: ReserveCatalogWithSharesInput;
    output: ReserveCatalogWithSharesOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type NftInputs = {
  [Method in keyof NftMethodMap]: NftMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type NftOutputs = {
  [Method in keyof NftMethodMap]: NftMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type NftCall<Method extends keyof NftMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      NftInputs[Name] extends Record<string, never>
        ? { methodArgs?: NftInputs[Name] }
        : { methodArgs: NftInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type NftInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type NftInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type NftMethod<Method extends keyof NftMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: NftInputs[Method] extends Record<string, never>
      ? [methodArgs?: NftInputs[Method]]
      : [methodArgs: NftInputs[Method]]
  ) => Promise<NftOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<NftCall<Method>, "method"> & NftInvocation,
  ) => Promise<NftInvocationResult<NftOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** The VanityClaim type declared by the contract. */
export type VanityClaim = SorobanType.Custom<{
  kind: "struct";
  fields: {
    contract_address: SorobanType.Address;
    salt: SorobanType.BytesN<32>;
    suffix: SorobanType.String;
  };
}>;

/** Raw or validated values accepted by the VanityClaim factory. */
export type VanityClaimArgs = SorobanType.Input.Custom<VanityClaim>;

/** Validate, encode and decode VanityClaim using its contract declaration. */
export const VanityClaim: SorobanType.Factory<VanityClaim> = SorobanType
  .Custom.fromSpec<VanityClaim>(
    () => NftSpec,
    "VanityClaim",
  );

/** The CatalogConfig type declared by the contract. */
export type CatalogConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    beneficiary: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the CatalogConfig factory. */
export type CatalogConfigArgs = SorobanType.Input.Custom<CatalogConfig>;

/** Validate, encode and decode CatalogConfig using its contract declaration. */
export const CatalogConfig: SorobanType.Factory<CatalogConfig> = SorobanType
  .Custom.fromSpec<CatalogConfig>(
    () => NftSpec,
    "CatalogConfig",
  );

/** The MintReservation type declared by the contract. */
export type MintReservation = SorobanType.Custom<{
  kind: "struct";
  fields: {
    catalog_price: SorobanType.I128;
    contract_address: SorobanType.Address;
    expires_at_ledger: SorobanType.U32;
    payer: SorobanType.Address;
    recipient: SorobanType.Address;
    suffix: SorobanType.String;
  };
}>;

/** Raw or validated values accepted by the MintReservation factory. */
export type MintReservationArgs = SorobanType.Input.Custom<MintReservation>;

/** Validate, encode and decode MintReservation using its contract declaration. */
export const MintReservation: SorobanType.Factory<MintReservation> = SorobanType
  .Custom.fromSpec<MintReservation>(
    () => NftSpec,
    "MintReservation",
  );

/** The ReservationConfig type declared by the contract. */
export type ReservationConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    duration_ledgers: SorobanType.U32;
    fee: SorobanType.I128;
    treasury: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the ReservationConfig factory. */
export type ReservationConfigArgs = SorobanType.Input.Custom<ReservationConfig>;

/** Validate, encode and decode ReservationConfig using its contract declaration. */
export const ReservationConfig: SorobanType.Factory<ReservationConfig> =
  SorobanType
    .Custom.fromSpec<ReservationConfig>(
      () => NftSpec,
      "ReservationConfig",
    );

/** The VanityClaimRecord type declared by the contract. */
export type VanityClaimRecord = SorobanType.Custom<{
  kind: "struct";
  fields: {
    claim: VanityClaim;
    status: VanityClaimStatus;
  };
}>;

/** Raw or validated values accepted by the VanityClaimRecord factory. */
export type VanityClaimRecordArgs = SorobanType.Input.Custom<VanityClaimRecord>;

/** Validate, encode and decode VanityClaimRecord using its contract declaration. */
export const VanityClaimRecord: SorobanType.Factory<VanityClaimRecord> =
  SorobanType
    .Custom.fromSpec<VanityClaimRecord>(
      () => NftSpec,
      "VanityClaimRecord",
    );

/** The VanityClaimStatus type declared by the contract. */
export type VanityClaimStatus = SorobanType.Custom<{
  kind: "enum";
  encoding: "tagged";
  variants: {
    Active: SorobanType.Void;
    Burned: SorobanType.Void;
  };
}>;

/** Raw or validated values accepted by the VanityClaimStatus factory. */
export type VanityClaimStatusArgs = SorobanType.Input.Custom<VanityClaimStatus>;

/** Validate, encode and decode VanityClaimStatus using its contract declaration. */
export const VanityClaimStatus: SorobanType.Factory<VanityClaimStatus> =
  SorobanType
    .Custom.fromSpec<VanityClaimStatus>(
      () => NftSpec,
      "VanityClaimStatus",
    );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by TreasuryChanged. */
export type TreasuryChanged = {
  operator: SorobanType.Address;
  previous_treasury: SorobanType.Address;
  new_treasury: SorobanType.Address;
};

/** Indexed fields accepted by the TreasuryChanged event filters. */
export type TreasuryChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by ClaimWordChanged. */
export type ClaimWordChanged = {
  contract_address: SorobanType.Address;
  token_id: SorobanType.U32;
  owner: SorobanType.Address;
  previous_word: SorobanType.String;
  new_word: SorobanType.String;
};

/** Indexed fields accepted by the ClaimWordChanged event filters. */
export type ClaimWordChangedTopics = {
  contract_address: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
  owner: SorobanType.Input.Address;
};

/** Fields emitted by ReservationCreated. */
export type ReservationCreated = {
  contract_address: SorobanType.Address;
  payer: SorobanType.Address;
  recipient: SorobanType.Address;
  suffix: SorobanType.String;
  protocol_fee: SorobanType.I128;
  catalog_price: SorobanType.I128;
  expires_at_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the ReservationCreated event filters. */
export type ReservationCreatedTopics = {
  contract_address: SorobanType.Input.Address;
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
};

/** Fields emitted by CatalogReservationCreated. */
export type CatalogReservationCreated = {
  contract_address: SorobanType.Address;
  recipient: SorobanType.Address;
  suffix: SorobanType.String;
  protocol_fee: SorobanType.I128;
  catalog_price: SorobanType.I128;
  expires_at_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the CatalogReservationCreated event filters. */
export type CatalogReservationCreatedTopics = {
  contract_address: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
};

/** Event emitted when a token is burned. */
export type Burn = {
  from: SorobanType.Address;
  token_id: SorobanType.U32;
};

/** Indexed fields accepted by the Burn event filters. */
export type BurnTopics = {
  from: SorobanType.Input.Address;
};

/** Event emitted when a token is minted. */
export type Mint = {
  to: SorobanType.Address;
  token_id: SorobanType.U32;
};

/** Indexed fields accepted by the Mint event filters. */
export type MintTopics = {
  to: SorobanType.Input.Address;
};

/** Event emitted when an approval is granted. */
export type Approve = {
  approver: SorobanType.Address;
  token_id: SorobanType.U32;
  approved: SorobanType.Address;
  live_until_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the Approve event filters. */
export type ApproveTopics = {
  approver: SorobanType.Input.Address;
  token_id: SorobanType.Input.U32;
};

/** Event emitted when a token is transferred. */
export type Transfer = {
  from: SorobanType.Address;
  to: SorobanType.Address;
  token_id: SorobanType.U32;
};

/** Indexed fields accepted by the Transfer event filters. */
export type TransferTopics = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
};

/** Event emitted when approval for all tokens is granted. */
export type ApproveForAll = {
  owner: SorobanType.Address;
  operator: SorobanType.Address;
  live_until_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the ApproveForAll event filters. */
export type ApproveForAllTopics = {
  owner: SorobanType.Input.Address;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type NftEvents = ContractEventRegistry & {
  readonly TreasuryChanged: ContractEventDefinition<
    TreasuryChanged,
    TreasuryChangedTopics
  >;
  readonly ClaimWordChanged: ContractEventDefinition<
    ClaimWordChanged,
    ClaimWordChangedTopics
  >;
  readonly ReservationCreated: ContractEventDefinition<
    ReservationCreated,
    ReservationCreatedTopics
  >;
  readonly CatalogReservationCreated: ContractEventDefinition<
    CatalogReservationCreated,
    CatalogReservationCreatedTopics
  >;
  readonly Burn: ContractEventDefinition<
    Burn,
    BurnTopics
  >;
  readonly Mint: ContractEventDefinition<
    Mint,
    MintTopics
  >;
  readonly Approve: ContractEventDefinition<
    Approve,
    ApproveTopics
  >;
  readonly Transfer: ContractEventDefinition<
    Transfer,
    TransferTopics
  >;
  readonly ApproveForAll: ContractEventDefinition<
    ApproveForAll,
    ApproveForAllTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type NftConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
