// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Nft contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { NftSpec } from "@/contracts/nft/constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Consumes a holder-authorized NFT only through the configured deployer or
 * when its represented contract is already deployed.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `from` - Address participating in this operation.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type BurnInput = {
  from: SorobanType.Input.Address;
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of burn. */
export type BurnOutput = null;

/**
 * Consumes an active reservation and mints its vanity plate NFT.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `salt` - Salt deriving the reserved contract address from the configured
 * deployer.
 *
 * # Returns
 *
 * The full contract hash as a U256 token ID minted to the reservation
 * recipient.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 * * Fails with `VanityPlateNftError::ReservationNotFound` when no active
 * reservation matches.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when the stored suffix no longer
 * matches.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address became occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Propagates standard NFT minting errors.
 */
export type MintInput = {
  salt: SorobanType.Input.BytesN<32>;
};

/** Decoded return value of mint. */
export type MintOutput = SorobanType.U256;

/**
 * Returns the collection name.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type NameInput = Record<string, never>;

/** Decoded return value of name. */
export type NameOutput = SorobanType.String;

/**
 * Returns the collection symbol.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type SymbolInput = Record<string, never>;

/** Decoded return value of symbol. */
export type SymbolOutput = SorobanType.String;

/**
 * Grants or revokes a token approval with owner or collection operator
 * authorization.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `approver` - Address participating in this operation.
 * * `approved` - Address participating in this operation.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 * * `live_until_ledger` - Inclusive expiry; zero revokes and larger than
 * network maximum is invalid.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type ApproveInput = {
  approver: SorobanType.Input.Address;
  approved: SorobanType.Input.Address;
  token_id: SorobanType.Input.U256;
  live_until_ledger: SorobanType.Input.U32;
};

/** Decoded return value of approve. */
export type ApproveOutput = null;

/**
 * Returns the number of live NFTs held by an address, or zero.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Address participating in this operation.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type BalanceInput = {
  owner: SorobanType.Input.Address;
};

/** Decoded return value of balance. */
export type BalanceOutput = SorobanType.U256;

/**
 * Reserves a vanity contract address for the paying recipient.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT after
 * minting.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 *
 * # Errors
 *
 * * Fails when `recipient` does not authorize the invocation or cannot pay
 * the fee.
 * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
 * account.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
 * match.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address is occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Fails with `VanityPlateNftError::AddressReserved` when an active
 * reservation exists.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is
 */
export type ReserveInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
};

/** Decoded return value of reserve. */
export type ReserveOutput = null;

/**
 * Replaces the NFT implementation with installed Wasm.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed Wasm hash selected as the new
 * implementation.
 * * `operator` - RBAC upgrader authorizing the upgrade.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Propagates role errors from the RBAC contract.
 * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Returns the RBAC contract used for administrative checks.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured RBAC contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 */
export type GetRbacInput = Record<string, never>;

/** Decoded return value of get_rbac. */
export type GetRbacOutput = SorobanType.Address;

/**
 * Returns the owner of a live NFT; consumed and unregistered IDs fail.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type OwnerOfInput = {
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of owner_of. */
export type OwnerOfOutput = SorobanType.Address;

/**
 * Transfers a live NFT with owner authorization; its represented address
 * cannot receive it.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `from` - Address participating in this operation.
 * * `to` - Address participating in this operation.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type TransferInput = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of transfer. */
export type TransferOutput = null;

/**
 * Returns the single retained record for a contract address, even after
 * consumption.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `contract_address` - Address participating in this operation.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type GetPlateInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_plate. */
export type GetPlateOutput = Plate;

/**
 * Returns the base URI plus contract address for a live NFT; fails after
 * consumption.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type TokenUriInput = {
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of token_uri. */
export type TokenUriOutput = SorobanType.String;

/**
 * Reserves a vanity contract address for a recipient using a separate payer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `payer` - Address authorizing and paying the reservation fee.
 * * `recipient` - Address that will receive the NFT after minting.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 *
 * # Errors
 *
 * * Fails when `payer` does not authorize the invocation or cannot pay the
 * fee.
 * * Fails with `VanityPlateNftError::InvalidContractAddress` for a classic
 * account.
 * * Fails with `VanityPlateNftError::InvalidSuffixLength`,
 * `VanityPlateNftError::InvalidSuffixCharacter`, or
 * `VanityPlateNftError::SuffixMismatch` when `suffix` is invalid or does not
 * match.
 * * Fails with `VanityPlateNftError::AddressAlreadyDeployed` when the
 * address is occupied.
 * * Fails with `VanityPlateNftError::AddressAlreadyMinted` when already
 * claimed.
 * * Fails with `VanityPlateNftError::AddressReserved` when an active
 * reservation exists.
 * * Fails with `
 */
export type ReserveForInput = {
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
};

/** Decoded return value of reserve_for. */
export type ReserveForOutput = null;

/**
 * Returns a live token approval, or None; fails for absent or consumed NFTs.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type GetApprovedInput = {
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of get_approved. */
export type GetApprovedOutput = SorobanType.Option<SorobanType.Address>;

/**
 * Returns the base URI used to construct token metadata URIs.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The collection's current base URI.
 *
 * # Errors
 *
 * Propagates standard NFT metadata errors when metadata is unavailable.
 */
export type GetBaseUriInput = Record<string, never>;

/** Decoded return value of get_base_uri. */
export type GetBaseUriOutput = SorobanType.String;

/**
 * Returns the contract used to derive and deploy vanity addresses.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The configured deployer contract address.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 */
export type GetDeployerInput = Record<string, never>;

/** Decoded return value of get_deployer. */
export type GetDeployerOutput = SorobanType.Address;

/**
 * Replaces the base URI used by existing and future token metadata URIs.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `base_uri` - New collection-wide base URI.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Propagates authorization and role errors from the RBAC contract.
 * * Propagates standard NFT metadata validation errors.
 */
export type SetBaseUriInput = {
  base_uri: SorobanType.Input.String;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_base_uri. */
export type SetBaseUriOutput = null;

/**
 * Changes the treasury that processes reservation fees and cashback.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `treasury` - New Wasm-backed treasury contract.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidTreasury` for a non-Wasm or
 * incompatible
 * replacement, existing treasury assets, shares, or redemptions, or a
 * replacement that
 * does not administer the shared reward asset.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetTreasuryInput = {
  treasury: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_treasury. */
export type SetTreasuryOutput = null;

/**
 * Initializes the vanity plate NFT collection and reservation policy.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `rbac` - RBAC contract used for administrative checks.
 * * `deployer` - Wasm contract whose address and salts derive vanity
 * contract addresses.
 * * `base_uri` - Base URI prepended to each claimed contract address.
 * * `reservation_config` - Treasury, fee, and reservation duration.
 * * `catalog_config` - Beneficiary receiving administrator-approved catalog
 * prices.
 * * `operator` - RBAC administrator authorizing construction.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidDeployer` for a non-Wasm
 * deployer, incompatible
 * deployer interface or governance, or an existing link to another NFT
 * collection.
 * * Fails with `VanityPlateNftError::InvalidTreasury` for incompatible
 * treasury governance,
 * an undeployed fee or reward asset, or a non-Wasm treasury.
 * * Fails with `VanityPlateNftError::InvalidReservationFee` for a negative
 * fee.
 * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an inv
 */
export type ConstructorInput = {
  rbac: SorobanType.Input.Address;
  deployer: SorobanType.Input.Address;
  base_uri: SorobanType.Input.String;
  reservation_config: ReservationConfigArgs;
  catalog_config: CatalogConfigArgs;
  operator: SorobanType.Input.Address;
};

/**
 * Transfers a live NFT with owner, token approval, or collection operator
 * authorization.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `spender` - Address participating in this operation.
 * * `from` - Address participating in this operation.
 * * `to` - Address participating in this operation.
 * * `token_id` - Full contract hash as an unsigned big-endian ID.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type TransferFromInput = {
  spender: SorobanType.Input.Address;
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
  token_id: SorobanType.Input.U256;
};

/** Decoded return value of transfer_from. */
export type TransferFromOutput = null;

/**
 * Grants or revokes collection-wide operator approval with owner
 * authorization.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Address participating in this operation.
 * * `operator` - Address participating in this operation.
 * * `live_until_ledger` - Inclusive expiry; zero revokes and larger than
 * network maximum is invalid.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type ApproveForAllInput = {
  owner: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
  live_until_ledger: SorobanType.Input.U32;
};

/** Decoded return value of approve_for_all. */
export type ApproveForAllOutput = null;

/**
 * Returns the active reservation for a predicted contract address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `contract_address` - Predicted vanity contract address used as the
 * reservation key.
 *
 * # Returns
 *
 * The active reservation, or `None` when absent or expired.
 *
 * # Errors
 *
 * This function emits no contract-defined errors.
 */
export type GetReservationInput = {
  contract_address: SorobanType.Input.Address;
};

/** Decoded return value of get_reservation. */
export type GetReservationOutput = SorobanType.Option<MintReservation>;

/**
 * Reserves a pre-farmed catalog address at an administrator-approved price.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying both fees and receiving the NFT after
 * minting.
 * * `contract_address` - Predicted catalog contract address being reserved.
 * * `suffix` - Catalog suffix that must match `contract_address`.
 * * `catalog_price` - Positive catalog price approved for this reservation.
 * * `operator` - RBAC administrator authorizing the supplied catalog price.
 *
 * # Errors
 *
 * * Fails when `recipient` or `operator` does not authorize.
 * * Fails for an invalid suffix, occupied or minted address, or active
 * reservation.
 * * Fails with `VanityPlateNftError::InvalidCatalogPrice` when the supplied
 * price is invalid.
 * * Propagates treasury fee collection and fee-asset transfer errors.
 */
export type ReserveCatalogInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  catalog_price: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of reserve_catalog. */
export type ReserveCatalogOutput = null;

/**
 * Returns the beneficiary receiving administrator-approved catalog prices.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The active catalog configuration.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::CatalogConfigNotFound` when unavailable.
 */
export type GetCatalogConfigInput = Record<string, never>;

/** Decoded return value of get_catalog_config. */
export type GetCatalogConfigOutput = CatalogConfig;

/**
 * Reserves a vanity address using a fixed fee credit and bounded VNTY
 * payment.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `recipient` - Receives the reserved NFT and pays unless a payer is
 * specified.
 * * `contract_address` - Undeployed vanity address to reserve.
 * * `suffix` - Validated plate ending.
 * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
 * deadline.
 *
 * # Errors
 * Propagates reservation validation, occupied-address, authorization, and
 * catalog errors.
 * Treasury rejects expired payments, changed fees, exceeded limits,
 * unavailable NAV,
 * invalid shares, or failed maximum transfer/refund. Failure is atomic.
 */
export type ReserveWithLimitInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  payment: VntyPaymentLimitArgs;
};

/** Decoded return value of reserve_with_limit. */
export type ReserveWithLimitOutput = null;

/**
 * Returns whether the operator permission remains valid through the current
 * ledger.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `owner` - Address participating in this operation.
 * * `operator` - Address participating in this operation.
 *
 * # Returns
 * The requested value.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type IsApprovedForAllInput = {
  owner: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of is_approved_for_all. */
export type IsApprovedForAllOutput = SorobanType.Bool;

/**
 * Reserves an address while burning reward shares toward the reservation
 * fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 * * `fee_shares` - Treasury reward shares to burn toward the fee.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates reservation validation and treasury share-payment errors.
 */
export type ReserveWithSharesInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of reserve_with_shares. */
export type ReserveWithSharesOutput = null;

/**
 * Sets 1..=56 highlighted characters with controller authorization; deployed
 * unregistered contracts can self-register.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `contract_address` - Address participating in this operation.
 * * `character_count` - Number of trailing characters, from one through 56.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails on missing required state, invalid input, or missing required
 * authorization.
 */
export type SetCharacterCountInput = {
  contract_address: SorobanType.Input.Address;
  character_count: SorobanType.Input.U32;
};

/** Decoded return value of set_character_count. */
export type SetCharacterCountOutput = null;

/**
 * Changes the fee charged when creating a reservation.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `fee` - New non-negative reservation fee in fee-asset stroops.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidReservationFee` when `fee` is
 * negative.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetReservationFeeInput = {
  fee: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_reservation_fee. */
export type SetReservationFeeOutput = null;

/**
 * Derives a vanity contract address from the configured deployer and a salt.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `salt` - Deterministic 32-byte deployment salt.
 *
 * # Returns
 *
 * The contract address derived from the configured deployer and `salt`.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::DeployerNotFound` when no deployer is
 * configured.
 */
export type GetPredictedAddressInput = {
  salt: SorobanType.Input.BytesN<32>;
};

/** Decoded return value of get_predicted_address. */
export type GetPredictedAddressOutput = SorobanType.Address;

/**
 * Returns the current reservation fee and duration configuration.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 *
 * # Returns
 *
 * The active reservation configuration.
 *
 * # Errors
 *
 * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config is
 * unavailable.
 */
export type GetReservationConfigInput = Record<string, never>;

/** Decoded return value of get_reservation_config. */
export type GetReservationConfigOutput = ReservationConfig;

/**
 * Reserves a vanity address using a fixed fee credit and bounded VNTY
 * payment.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `payer` - Authorizes and pays the fee.
 * * `recipient` - Receives the reserved NFT and pays unless a payer is
 * specified.
 * * `contract_address` - Undeployed vanity address to reserve.
 * * `suffix` - Validated plate ending.
 * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
 * deadline.
 *
 * # Errors
 * Propagates reservation validation, occupied-address, authorization, and
 * catalog errors.
 * Treasury rejects expired payments, changed fees, exceeded limits,
 * unavailable NAV,
 * invalid shares, or failed maximum transfer/refund. Failure is atomic.
 */
export type ReserveForWithLimitInput = {
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  payment: VntyPaymentLimitArgs;
};

/** Decoded return value of reserve_for_with_limit. */
export type ReserveForWithLimitOutput = null;

/**
 * Reserves for another recipient while burning the payer's reward shares
 * toward the fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `payer` - Address authorizing both payment sources.
 * * `recipient` - Address that will receive the NFT.
 * * `contract_address` - Predicted vanity contract address being reserved.
 * * `suffix` - Claimed suffix that must match `contract_address`.
 * * `fee_shares` - Treasury reward shares to burn toward the fee.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates reservation validation and treasury share-payment errors.
 */
export type ReserveForWithSharesInput = {
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  fee_shares: SorobanType.Input.I128;
};

/** Decoded return value of reserve_for_with_shares. */
export type ReserveForWithSharesOutput = null;

/**
 * Changes the account receiving catalog prices.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `beneficiary` - New catalog-price beneficiary.
 * * `operator` - RBAC administrator authorizing the change.
 *
 * # Errors
 *
 * Propagates authorization and role errors from the RBAC contract.
 */
export type SetCatalogBeneficiaryInput = {
  beneficiary: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_catalog_beneficiary. */
export type SetCatalogBeneficiaryOutput = null;

/**
 * Changes how many ledgers a reservation remains valid.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `duration_ledgers` - Positive reservation lifetime not exceeding the
 * network maximum TTL.
 * * `operator` - RBAC administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::RbacNotFound` when RBAC is unavailable.
 * * Fails with `VanityPlateNftError::ReservationConfigNotFound` when config
 * is unavailable.
 * * Fails with `VanityPlateNftError::InvalidReservationDuration` for an
 * invalid duration.
 * * Propagates authorization and role errors from the RBAC contract.
 */
export type SetReservationDurationInput = {
  duration_ledgers: SorobanType.Input.U32;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_reservation_duration. */
export type SetReservationDurationOutput = null;

/**
 * Reserves a vanity address using a fixed fee credit and bounded VNTY
 * payment.
 *
 * # Arguments
 * * `e` - Execution environment.
 * * `recipient` - Receives the reserved NFT and pays unless a payer is
 * specified.
 * * `contract_address` - Undeployed vanity address to reserve.
 * * `suffix` - Validated plate ending.
 * * `catalog_price` - Administrator-approved premium, paid separately in the
 * fee asset.
 * * `payment` - Expected fee, exact credit, maximum VNTY, and exclusive Unix
 * deadline.
 * * `operator` - RBAC administrator coauthorizing the catalog price.
 *
 * # Errors
 * Propagates reservation validation, occupied-address, authorization, and
 * catalog errors.
 * Treasury rejects expired payments, changed fees, exceeded limits,
 * unavailable NAV,
 * invalid shares, or failed maximum transfer/refund. Failure is atomic.
 */
export type ReserveCatalogWithLimitInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  catalog_price: SorobanType.Input.I128;
  payment: VntyPaymentLimitArgs;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of reserve_catalog_with_limit. */
export type ReserveCatalogWithLimitOutput = null;

/**
 * Reserves a catalog address while burning reward shares toward the protocol
 * fee.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `recipient` - Address paying the fee and receiving the NFT.
 * * `contract_address` - Predicted catalog contract address being reserved.
 * * `suffix` - Catalog suffix that must match `contract_address`.
 * * `catalog_price` - Positive catalog price approved for this reservation.
 * * `fee_shares` - Treasury reward shares to burn toward the protocol fee.
 * * `operator` - RBAC administrator authorizing the supplied catalog price.
 *
 * # Errors
 *
 * * Fails with `VanityPlateNftError::InvalidSharePayment` for negative
 * shares or shares
 * supplied when the reservation fee is zero.
 * * Propagates catalog reservation and treasury share-payment errors. The
 * catalog price
 * remains payable in the configured fee asset.
 */
export type ReserveCatalogWithSharesInput = {
  recipient: SorobanType.Input.Address;
  contract_address: SorobanType.Input.Address;
  suffix: SorobanType.Input.String;
  catalog_price: SorobanType.Input.I128;
  fee_shares: SorobanType.Input.I128;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of reserve_catalog_with_shares. */
export type ReserveCatalogWithSharesOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type NftMethodMap = {
  burn: {
    input: BurnInput;
    output: BurnOutput;
  };
  mint: {
    input: MintInput;
    output: MintOutput;
  };
  name: {
    input: NameInput;
    output: NameOutput;
  };
  symbol: {
    input: SymbolInput;
    output: SymbolOutput;
  };
  approve: {
    input: ApproveInput;
    output: ApproveOutput;
  };
  balance: {
    input: BalanceInput;
    output: BalanceOutput;
  };
  reserve: {
    input: ReserveInput;
    output: ReserveOutput;
  };
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  get_rbac: {
    input: GetRbacInput;
    output: GetRbacOutput;
  };
  owner_of: {
    input: OwnerOfInput;
    output: OwnerOfOutput;
  };
  transfer: {
    input: TransferInput;
    output: TransferOutput;
  };
  get_plate: {
    input: GetPlateInput;
    output: GetPlateOutput;
  };
  token_uri: {
    input: TokenUriInput;
    output: TokenUriOutput;
  };
  reserve_for: {
    input: ReserveForInput;
    output: ReserveForOutput;
  };
  get_approved: {
    input: GetApprovedInput;
    output: GetApprovedOutput;
  };
  get_base_uri: {
    input: GetBaseUriInput;
    output: GetBaseUriOutput;
  };
  get_deployer: {
    input: GetDeployerInput;
    output: GetDeployerOutput;
  };
  set_base_uri: {
    input: SetBaseUriInput;
    output: SetBaseUriOutput;
  };
  set_treasury: {
    input: SetTreasuryInput;
    output: SetTreasuryOutput;
  };
  transfer_from: {
    input: TransferFromInput;
    output: TransferFromOutput;
  };
  approve_for_all: {
    input: ApproveForAllInput;
    output: ApproveForAllOutput;
  };
  get_reservation: {
    input: GetReservationInput;
    output: GetReservationOutput;
  };
  reserve_catalog: {
    input: ReserveCatalogInput;
    output: ReserveCatalogOutput;
  };
  get_catalog_config: {
    input: GetCatalogConfigInput;
    output: GetCatalogConfigOutput;
  };
  reserve_with_limit: {
    input: ReserveWithLimitInput;
    output: ReserveWithLimitOutput;
  };
  is_approved_for_all: {
    input: IsApprovedForAllInput;
    output: IsApprovedForAllOutput;
  };
  reserve_with_shares: {
    input: ReserveWithSharesInput;
    output: ReserveWithSharesOutput;
  };
  set_character_count: {
    input: SetCharacterCountInput;
    output: SetCharacterCountOutput;
  };
  set_reservation_fee: {
    input: SetReservationFeeInput;
    output: SetReservationFeeOutput;
  };
  get_predicted_address: {
    input: GetPredictedAddressInput;
    output: GetPredictedAddressOutput;
  };
  get_reservation_config: {
    input: GetReservationConfigInput;
    output: GetReservationConfigOutput;
  };
  reserve_for_with_limit: {
    input: ReserveForWithLimitInput;
    output: ReserveForWithLimitOutput;
  };
  reserve_for_with_shares: {
    input: ReserveForWithSharesInput;
    output: ReserveForWithSharesOutput;
  };
  set_catalog_beneficiary: {
    input: SetCatalogBeneficiaryInput;
    output: SetCatalogBeneficiaryOutput;
  };
  set_reservation_duration: {
    input: SetReservationDurationInput;
    output: SetReservationDurationOutput;
  };
  reserve_catalog_with_limit: {
    input: ReserveCatalogWithLimitInput;
    output: ReserveCatalogWithLimitOutput;
  };
  reserve_catalog_with_shares: {
    input: ReserveCatalogWithSharesInput;
    output: ReserveCatalogWithSharesOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type NftInputs = {
  [Method in keyof NftMethodMap]: NftMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type NftOutputs = {
  [Method in keyof NftMethodMap]: NftMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type NftCall<Method extends keyof NftMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      NftInputs[Name] extends Record<string, never>
        ? { methodArgs?: NftInputs[Name] }
        : { methodArgs: NftInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type NftInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type NftInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type NftMethod<Method extends keyof NftMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: NftInputs[Method] extends Record<string, never>
      ? [methodArgs?: NftInputs[Method]]
      : [methodArgs: NftInputs[Method]]
  ) => Promise<NftOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<NftCall<Method>, "method"> & NftInvocation,
  ) => Promise<NftInvocationResult<NftOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/**
 * Signed fee coverage intent. All amounts use their token's atomic units.
 */
export type VntyPaymentLimit = SorobanType.Custom<{
  kind: "struct";
  fields: {
    /** Exclusive execution deadline in Unix seconds. */
    deadline: SorobanType.U64;
    /** Expected complete protocol fee; prevents an unapproved cash increase. */
    fee_amount: SorobanType.I128;
    /** Exact fee-asset credit purchased by burning VNTY. */
    fee_credit: SorobanType.I128;
    /**
     * Maximum VNTY transferred temporarily, with unused shares refunded
     * atomically.
     */
    max_shares: SorobanType.I128;
  };
}>;

/** Raw or validated values accepted by the VntyPaymentLimit factory. */
export type VntyPaymentLimitArgs = SorobanType.Input.Custom<VntyPaymentLimit>;

/** Validate, encode and decode VntyPaymentLimit using its contract declaration. */
export const VntyPaymentLimit: SorobanType.Factory<VntyPaymentLimit> =
  SorobanType
    .Custom.fromSpec<VntyPaymentLimit>(
      () => NftSpec,
      "VntyPaymentLimit",
    );

/**
 * One permanent record per represented contract address.
 * `controller == address` means consumed or self-registered; there is no
 * live NFT.
 */
export type Plate = SorobanType.Custom<{
  kind: "struct";
  fields: {
    character_count: SorobanType.U32;
    controller: SorobanType.Address;
    salt: SorobanType.Option<SorobanType.BytesN<32>>;
  };
}>;

/** Raw or validated values accepted by the Plate factory. */
export type PlateArgs = SorobanType.Input.Custom<Plate>;

/** Validate, encode and decode Plate using its contract declaration. */
export const Plate: SorobanType.Factory<Plate> = SorobanType
  .Custom.fromSpec<Plate>(
    () => NftSpec,
    "Plate",
  );

/** The CatalogConfig type declared by the contract. */
export type CatalogConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    beneficiary: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the CatalogConfig factory. */
export type CatalogConfigArgs = SorobanType.Input.Custom<CatalogConfig>;

/** Validate, encode and decode CatalogConfig using its contract declaration. */
export const CatalogConfig: SorobanType.Factory<CatalogConfig> = SorobanType
  .Custom.fromSpec<CatalogConfig>(
    () => NftSpec,
    "CatalogConfig",
  );

/** The MintReservation type declared by the contract. */
export type MintReservation = SorobanType.Custom<{
  kind: "struct";
  fields: {
    catalog_price: SorobanType.I128;
    contract_address: SorobanType.Address;
    expires_at_ledger: SorobanType.U32;
    payer: SorobanType.Address;
    recipient: SorobanType.Address;
    suffix: SorobanType.String;
  };
}>;

/** Raw or validated values accepted by the MintReservation factory. */
export type MintReservationArgs = SorobanType.Input.Custom<MintReservation>;

/** Validate, encode and decode MintReservation using its contract declaration. */
export const MintReservation: SorobanType.Factory<MintReservation> = SorobanType
  .Custom.fromSpec<MintReservation>(
    () => NftSpec,
    "MintReservation",
  );

/** The ReservationConfig type declared by the contract. */
export type ReservationConfig = SorobanType.Custom<{
  kind: "struct";
  fields: {
    duration_ledgers: SorobanType.U32;
    fee: SorobanType.I128;
    treasury: SorobanType.Address;
  };
}>;

/** Raw or validated values accepted by the ReservationConfig factory. */
export type ReservationConfigArgs = SorobanType.Input.Custom<ReservationConfig>;

/** Validate, encode and decode ReservationConfig using its contract declaration. */
export const ReservationConfig: SorobanType.Factory<ReservationConfig> =
  SorobanType
    .Custom.fromSpec<ReservationConfig>(
      () => NftSpec,
      "ReservationConfig",
    );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by Burn. */
export type Burn = {
  from: SorobanType.Address;
  token_id: SorobanType.U256;
};

/** Indexed fields accepted by the Burn event filters. */
export type BurnTopics = {
  from: SorobanType.Input.Address;
};

/** Fields emitted by Mint. */
export type Mint = {
  to: SorobanType.Address;
  token_id: SorobanType.U256;
};

/** Indexed fields accepted by the Mint event filters. */
export type MintTopics = {
  to: SorobanType.Input.Address;
};

/** Fields emitted by Approve. */
export type Approve = {
  owner: SorobanType.Address;
  token_id: SorobanType.U256;
  approved: SorobanType.Address;
  live_until_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the Approve event filters. */
export type ApproveTopics = {
  owner: SorobanType.Input.Address;
  token_id: SorobanType.Input.U256;
};

/** Fields emitted by Transfer. */
export type Transfer = {
  from: SorobanType.Address;
  to: SorobanType.Address;
  token_id: SorobanType.U256;
};

/** Indexed fields accepted by the Transfer event filters. */
export type TransferTopics = {
  from: SorobanType.Input.Address;
  to: SorobanType.Input.Address;
};

/** Fields emitted by ApproveForAll. */
export type ApproveForAll = {
  owner: SorobanType.Address;
  operator: SorobanType.Address;
  live_until_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the ApproveForAll event filters. */
export type ApproveForAllTopics = {
  owner: SorobanType.Input.Address;
};

/** Fields emitted by TreasuryChanged. */
export type TreasuryChanged = {
  operator: SorobanType.Address;
  previous_treasury: SorobanType.Address;
  new_treasury: SorobanType.Address;
};

/** Indexed fields accepted by the TreasuryChanged event filters. */
export type TreasuryChangedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by ReservationCreated. */
export type ReservationCreated = {
  contract_address: SorobanType.Address;
  payer: SorobanType.Address;
  recipient: SorobanType.Address;
  suffix: SorobanType.String;
  protocol_fee: SorobanType.I128;
  catalog_price: SorobanType.I128;
  expires_at_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the ReservationCreated event filters. */
export type ReservationCreatedTopics = {
  contract_address: SorobanType.Input.Address;
  payer: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
};

/** Fields emitted by CharacterCountChanged. */
export type CharacterCountChanged = {
  contract_address: SorobanType.Address;
  controller: SorobanType.Address;
  character_count: SorobanType.U32;
};

/** Indexed fields accepted by the CharacterCountChanged event filters. */
export type CharacterCountChangedTopics = {
  contract_address: SorobanType.Input.Address;
  controller: SorobanType.Input.Address;
};

/** Fields emitted by CatalogReservationCreated. */
export type CatalogReservationCreated = {
  contract_address: SorobanType.Address;
  recipient: SorobanType.Address;
  suffix: SorobanType.String;
  protocol_fee: SorobanType.I128;
  catalog_price: SorobanType.I128;
  expires_at_ledger: SorobanType.U32;
};

/** Indexed fields accepted by the CatalogReservationCreated event filters. */
export type CatalogReservationCreatedTopics = {
  contract_address: SorobanType.Input.Address;
  recipient: SorobanType.Input.Address;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type NftEvents = ContractEventRegistry & {
  readonly Burn: ContractEventDefinition<
    Burn,
    BurnTopics
  >;
  readonly Mint: ContractEventDefinition<
    Mint,
    MintTopics
  >;
  readonly Approve: ContractEventDefinition<
    Approve,
    ApproveTopics
  >;
  readonly Transfer: ContractEventDefinition<
    Transfer,
    TransferTopics
  >;
  readonly ApproveForAll: ContractEventDefinition<
    ApproveForAll,
    ApproveForAllTopics
  >;
  readonly TreasuryChanged: ContractEventDefinition<
    TreasuryChanged,
    TreasuryChangedTopics
  >;
  readonly ReservationCreated: ContractEventDefinition<
    ReservationCreated,
    ReservationCreatedTopics
  >;
  readonly CharacterCountChanged: ContractEventDefinition<
    CharacterCountChanged,
    CharacterCountChangedTopics
  >;
  readonly CatalogReservationCreated: ContractEventDefinition<
    CatalogReservationCreated,
    CatalogReservationCreatedTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type NftConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
