/** Compatibility names derived from the canonical Colibri method maps. @module */
import type { MethodMap } from "@/contracts/client.ts";
import type { NftMethodMap } from "@/contracts/nft/types.ts";
/** Exact nft arguments and decoded results generated by Colibri. */
export type NftMethods = MethodMap<NftMethodMap>;
export {
  CatalogConfig,
  MintReservation,
  ReservationConfig,
  VanityClaim,
  VanityClaimRecord,
  VanityClaimStatus,
  VntyPaymentLimit,
} from "@/contracts/nft/types.ts";
import type { DeployerMethodMap } from "@/contracts/deployer/types.ts";
/** Exact deployer arguments and decoded results generated by Colibri. */
export type DeployerMethods = MethodMap<DeployerMethodMap>;
import type { MarketplaceMethodMap } from "@/contracts/marketplace/types.ts";
/** Exact marketplace arguments and decoded results generated by Colibri. */
export type MarketplaceMethods = MethodMap<MarketplaceMethodMap>;
export {
  Listing,
  MarketplaceConfig,
  SellerSalesPage,
} from "@/contracts/marketplace/types.ts";
import type { TreasuryMethodMap } from "@/contracts/treasury/types.ts";
/** Exact treasury arguments and decoded results generated by Colibri. */
export type TreasuryMethods = MethodMap<TreasuryMethodMap>;
export {
  AccountingParameters,
  FeeReceipt,
  MarketHealth,
  MarketHealthStatus,
  RebalanceInvestment,
  RebalanceReceipt,
  RedemptionReceipt,
  RedemptionRequest,
  RouteHealth,
  StrategyAllocation,
  StrategyInvestment,
  StrategyPosition,
  StrategyRedemption,
  TreasuryConfig,
  TreasurySnapshot,
  VaultMigrationReceipt,
} from "@/contracts/treasury/types.ts";
import type { RbacMethodMap } from "@/contracts/rbac/types.ts";
/** Exact rbac arguments and decoded results generated by Colibri. */
export type RbacMethods = MethodMap<RbacMethodMap>;
export { Role } from "@/contracts/rbac/types.ts";
