// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Typed Colibri client for Rbac.
 * @module
 */
import {
  Contract,
  type ContractId,
  createContractErrorMatcherPlugin,
} from "@colibri/core";
import { Spec } from "@colibri/core";
import {
  ContractMethods,
  RbacErrors,
  RbacSpec,
} from "@/contracts/rbac/constants.ts";
import type {
  RbacCall,
  RbacConstructorArgs,
  RbacEvents,
  RbacInvocation,
  RbacInvocationResult,
  RbacMethod,
  RbacMethodMap,
  RbacOutputs,
} from "@/contracts/rbac/types.ts";

export * from "@/contracts/rbac/constants.ts";
export * from "@/contracts/rbac/types.ts";

/** Simulate or invoke callable functions declared in the embedded contract spec. */
export class Rbac extends Contract {
  /**
   * Replaces the RBAC implementation with installed Wasm.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_wasm_hash` - Installed Wasm hash selected as the new
   * implementation.
   * * `operator` - RBAC upgrader authorizing the upgrade.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the upgrader role is
   * unavailable.
   * * Fails with `RbacError::Unauthorized` when `operator` is not the
   * upgrader.
   * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
   */
  readonly upgrade: RbacMethod<"upgrade"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.Upgrade, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.Upgrade,
      }),
  };

  /**
   * Returns the address currently assigned to a role.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `role` - Role whose assigned address is requested.
   *
   * # Returns
   *
   * The address assigned to `role`.
   *
   * # Errors
   *
   * Fails with `RbacError::RoleNotFound` when the role has no assignment.
   */
  readonly getRole: RbacMethod<"get_role"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.GetRole, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.GetRole,
      }),
  };

  /**
   * Checks whether an operator is assigned to a role without requiring
   * authorization.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `role` - Role to check.
   * * `operator` - Address compared with the current role assignment.
   *
   * # Returns
   *
   * `true` when `operator` is assigned to `role`; otherwise `false`.
   *
   * # Errors
   *
   * Fails with `RbacError::RoleNotFound` when the role has no assignment.
   */
  readonly hasRole: RbacMethod<"has_role"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.HasRole, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.HasRole,
      }),
  };

  /**
   * Accepts an active administrator proposal for the proposed address.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `operator` - Proposed administrator accepting the role.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::PendingAdminNotFound` when no proposal exists.
   * * Fails with `RbacError::PendingAdminMismatch` when `operator` was not
   * proposed.
   */
  readonly acceptAdmin: RbacMethod<"accept_admin"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.AcceptAdmin, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.AcceptAdmin,
      }),
  };

  /**
   * Cancels the active administrator proposal.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `operator` - Current administrator authorizing cancellation.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the administrator role is
   * unavailable.
   * * Fails with `RbacError::Unauthorized` when `operator` is not the
   * administrator.
   * * Fails with `RbacError::PendingAdminNotFound` when no proposal exists.
   */
  readonly cancelAdmin: RbacMethod<"cancel_admin"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.CancelAdmin, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.CancelAdmin,
      }),
  };

  /**
   * Requires an operator to authorize the invocation and hold the requested
   * role.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `role` - Required role.
   * * `operator` - Address that must authorize and hold `role`.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the role has no assignment.
   * * Fails with `RbacError::Unauthorized` when `operator` does not hold
   * `role`.
   */
  readonly requireRole: RbacMethod<"require_role"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.RequireRole, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.RequireRole,
      }),
  };

  /**
   * Replaces the address assigned to the upgrader role.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_upgrader` - Address assigned as the new upgrader.
   * * `operator` - Current administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the administrator role is
   * unavailable.
   * * Fails with `RbacError::Unauthorized` when `operator` is not the
   * administrator.
   */
  readonly setUpgrader: RbacMethod<"set_upgrader"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetUpgrader, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetUpgrader,
      }),
  };

  /**
   * Proposes an address as the next administrator.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_admin` - Address proposed as the next administrator.
   * * `operator` - Current administrator authorizing the proposal.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the administrator role is
   * unavailable.
   * * Fails with `RbacError::Unauthorized` when `operator` is not the
   * administrator.
   * * Fails with `RbacError::PendingAdminAlreadyExists` when a proposal is
   * already active.
   */
  readonly proposeAdmin: RbacMethod<"propose_admin"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.ProposeAdmin, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.ProposeAdmin,
      }),
  };

  /**
   * Replaces the address assigned to the treasurer role.
   *
   * # Arguments
   *
   * * `e` - Contract execution environment.
   * * `new_treasurer` - Address assigned as the new treasurer.
   * * `operator` - Current administrator authorizing the update.
   *
   * # Errors
   *
   * * Fails when `operator` does not authorize the invocation.
   * * Fails with `RbacError::RoleNotFound` when the administrator role is
   * unavailable.
   * * Fails with `RbacError::Unauthorized` when `operator` is not the
   * administrator.
   */
  readonly setTreasurer: RbacMethod<"set_treasurer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetTreasurer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetTreasurer,
      }),
  };

  /**
   * Assigns the dedicated rebalance operator.
   *
   * # Arguments
   * * `e` - Contract execution environment.
   * * `new_rebalancer` - Account or contract allowed to execute treasury
   * rebalances.
   * * `operator` - Current administrator, which must authorize the change.
   *
   * # Returns
   * Nothing on success.
   *
   * # Errors
   * Fails if the operator is not the authorized administrator.
   */
  readonly setRebalancer: RbacMethod<"set_rebalancer"> = {
    read: (methodArgs) =>
      this.read({ method: ContractMethods.SetRebalancer, methodArgs }),
    invoke: (args) =>
      this.invoke({
        ...args,
        method: ContractMethods.SetRebalancer,
      }),
  };

  /** Install a fresh spec and the prepared error map alongside existing plugins. */
  constructor({ errors = RbacErrors, ...args }: RbacConstructorArgs) {
    const contractId = args.contractConfig.contractId as ContractId | undefined;
    const matcher = errors === false || Object.keys(errors).length === 0
      ? undefined
      : createContractErrorMatcherPlugin(
        contractId ? [{ strategy: "contract-id", contractId, errors }] : [{
          strategy: "issued-from",
          issuedFrom: "root-invocation",
          errors,
        }],
      );
    const plugins = args.contractConfig.plugins;

    super({
      ...args,
      contractConfig: {
        ...args.contractConfig,
        spec: new Spec(RbacSpec.entries.map((entry) => entry.toXdr("base64"))),
        plugins: {
          invokePipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.invokePipe ?? []),
          ],
          readPipe: [
            ...(matcher ? [matcher] : []),
            ...(plugins?.readPipe ?? []),
          ],
        },
      },
    });
  }

  /** Access event definitions bound to the current contract ID. */
  override get events(): RbacEvents {
    return super.events as RbacEvents;
  }

  /** Simulate a function and decode its result without submitting a transaction. */
  override async read<Method extends keyof RbacMethodMap>(
    args: RbacCall<Method>,
  ): Promise<RbacOutputs[Method]> {
    return await super.read(args) as RbacOutputs[Method];
  }

  /** Submit through Colibri and retain both the decoded value and raw result. */
  override async invoke<Method extends keyof RbacMethodMap>(
    args: RbacCall<Method> & RbacInvocation,
  ): Promise<RbacInvocationResult<RbacOutputs[Method]>> {
    const result = await super.invoke(args);
    return this.decodeInvocationResult<RbacOutputs[Method]>(
      args.method,
      result,
    );
  }
}
