// Generated by @colibri/contract-bindings. Replaceable: keep custom code outside this file.
/**
 * Rbac contract types, function arguments, results, and events.
 * @module
 */
import type {
  Contract,
  ContractConstructorArgs,
  ContractErrorMap,
  ContractEventDefinition,
  ContractEventRegistry,
} from "@colibri/core";
import { SorobanType } from "@colibri/core";
import { RbacSpec } from "@/contracts/rbac/constants.ts";

// -----------------------------------------------------------------------------
// Methods
// -----------------------------------------------------------------------------

/**
 * Replaces the RBAC implementation with installed Wasm.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_wasm_hash` - Installed Wasm hash selected as the new
 * implementation.
 * * `operator` - RBAC upgrader authorizing the upgrade.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the upgrader role is
 * unavailable.
 * * Fails with `RbacError::Unauthorized` when `operator` is not the
 * upgrader.
 * * Fails when `new_wasm_hash` does not reference installed contract Wasm.
 */
export type UpgradeInput = {
  new_wasm_hash: SorobanType.Input.BytesN<32>;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of upgrade. */
export type UpgradeOutput = null;

/**
 * Returns the address currently assigned to a role.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `role` - Role whose assigned address is requested.
 *
 * # Returns
 *
 * The address assigned to `role`.
 *
 * # Errors
 *
 * Fails with `RbacError::RoleNotFound` when the role has no assignment.
 */
export type GetRoleInput = {
  role: RoleArgs;
};

/** Decoded return value of get_role. */
export type GetRoleOutput = SorobanType.Address;

/**
 * Checks whether an operator is assigned to a role without requiring
 * authorization.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `role` - Role to check.
 * * `operator` - Address compared with the current role assignment.
 *
 * # Returns
 *
 * `true` when `operator` is assigned to `role`; otherwise `false`.
 *
 * # Errors
 *
 * Fails with `RbacError::RoleNotFound` when the role has no assignment.
 */
export type HasRoleInput = {
  role: RoleArgs;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of has_role. */
export type HasRoleOutput = SorobanType.Bool;

/**
 * Accepts an active administrator proposal for the proposed address.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `operator` - Proposed administrator accepting the role.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::PendingAdminNotFound` when no proposal exists.
 * * Fails with `RbacError::PendingAdminMismatch` when `operator` was not
 * proposed.
 */
export type AcceptAdminInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of accept_admin. */
export type AcceptAdminOutput = null;

/**
 * Cancels the active administrator proposal.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `operator` - Current administrator authorizing cancellation.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the administrator role is
 * unavailable.
 * * Fails with `RbacError::Unauthorized` when `operator` is not the
 * administrator.
 * * Fails with `RbacError::PendingAdminNotFound` when no proposal exists.
 */
export type CancelAdminInput = {
  operator: SorobanType.Input.Address;
};

/** Decoded return value of cancel_admin. */
export type CancelAdminOutput = null;

/**
 * Requires an operator to authorize the invocation and hold the requested
 * role.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `role` - Required role.
 * * `operator` - Address that must authorize and hold `role`.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the role has no assignment.
 * * Fails with `RbacError::Unauthorized` when `operator` does not hold
 * `role`.
 */
export type RequireRoleInput = {
  role: RoleArgs;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of require_role. */
export type RequireRoleOutput = null;

/**
 * Replaces the address assigned to the upgrader role.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_upgrader` - Address assigned as the new upgrader.
 * * `operator` - Current administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the administrator role is
 * unavailable.
 * * Fails with `RbacError::Unauthorized` when `operator` is not the
 * administrator.
 */
export type SetUpgraderInput = {
  new_upgrader: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_upgrader. */
export type SetUpgraderOutput = null;

/**
 * Initializes Admin, Treasurer and Upgrader, with Treasurer also holding
 * Rebalancer.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `admin` - Highest authority, allowed to reassign every operational role.
 * * `treasurer` - Address assigned to the treasurer role.
 * * `upgrader` - Address assigned to the upgrader role.
 *
 * # Errors
 *
 * Fails when `admin` does not authorize construction.
 */
export type ConstructorInput = {
  admin: SorobanType.Input.Address;
  treasurer: SorobanType.Input.Address;
  upgrader: SorobanType.Input.Address;
};

/**
 * Proposes an address as the next administrator.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_admin` - Address proposed as the next administrator.
 * * `operator` - Current administrator authorizing the proposal.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the administrator role is
 * unavailable.
 * * Fails with `RbacError::Unauthorized` when `operator` is not the
 * administrator.
 * * Fails with `RbacError::PendingAdminAlreadyExists` when a proposal is
 * already active.
 */
export type ProposeAdminInput = {
  new_admin: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of propose_admin. */
export type ProposeAdminOutput = null;

/**
 * Replaces the address assigned to the treasurer role.
 *
 * # Arguments
 *
 * * `e` - Contract execution environment.
 * * `new_treasurer` - Address assigned as the new treasurer.
 * * `operator` - Current administrator authorizing the update.
 *
 * # Errors
 *
 * * Fails when `operator` does not authorize the invocation.
 * * Fails with `RbacError::RoleNotFound` when the administrator role is
 * unavailable.
 * * Fails with `RbacError::Unauthorized` when `operator` is not the
 * administrator.
 */
export type SetTreasurerInput = {
  new_treasurer: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_treasurer. */
export type SetTreasurerOutput = null;

/**
 * Assigns the dedicated rebalance operator.
 *
 * # Arguments
 * * `e` - Contract execution environment.
 * * `new_rebalancer` - Account or contract allowed to execute treasury
 * rebalances.
 * * `operator` - Current administrator, which must authorize the change.
 *
 * # Returns
 * Nothing on success.
 *
 * # Errors
 * Fails if the operator is not the authorized administrator.
 */
export type SetRebalancerInput = {
  new_rebalancer: SorobanType.Input.Address;
  operator: SorobanType.Input.Address;
};

/** Decoded return value of set_rebalancer. */
export type SetRebalancerOutput = null;

/** Callable ABI methods available through read and invoke; excludes __constructor. */
export type RbacMethodMap = {
  upgrade: {
    input: UpgradeInput;
    output: UpgradeOutput;
  };
  get_role: {
    input: GetRoleInput;
    output: GetRoleOutput;
  };
  has_role: {
    input: HasRoleInput;
    output: HasRoleOutput;
  };
  accept_admin: {
    input: AcceptAdminInput;
    output: AcceptAdminOutput;
  };
  cancel_admin: {
    input: CancelAdminInput;
    output: CancelAdminOutput;
  };
  require_role: {
    input: RequireRoleInput;
    output: RequireRoleOutput;
  };
  set_upgrader: {
    input: SetUpgraderInput;
    output: SetUpgraderOutput;
  };
  propose_admin: {
    input: ProposeAdminInput;
    output: ProposeAdminOutput;
  };
  set_treasurer: {
    input: SetTreasurerInput;
    output: SetTreasurerOutput;
  };
  set_rebalancer: {
    input: SetRebalancerInput;
    output: SetRebalancerOutput;
  };
};

/** Method names mapped to their accepted arguments. */
export type RbacInputs = {
  [Method in keyof RbacMethodMap]: RbacMethodMap[Method]["input"];
};

/** Method names mapped to their decoded return values. */
export type RbacOutputs = {
  [Method in keyof RbacMethodMap]: RbacMethodMap[Method]["output"];
};

/** A method and its matching arguments; argument-free calls may omit methodArgs. */
export type RbacCall<Method extends keyof RbacMethodMap> = {
  [Name in Method]:
    & { method: Name }
    & (
      RbacInputs[Name] extends Record<string, never>
        ? { methodArgs?: RbacInputs[Name] }
        : { methodArgs: RbacInputs[Name] }
    );
}[Method];

/** Transaction settings and authorization passed to Colibri. */
export type RbacInvocation = Pick<
  Parameters<Contract["invoke"]>[0],
  "config" | "auth"
>;

/** Core transaction metadata and the decoded contract result. */
export type RbacInvocationResult<Value> =
  & Awaited<ReturnType<Contract["invoke"]>>
  & { value: Value | undefined };

/** Bound read/invoke helpers for one ABI method, with its exact input and output. */
export type RbacMethod<Method extends keyof RbacMethodMap> = {
  /** Simulate without submitting; argument-free methods can omit the input. */
  readonly read: (
    ...args: RbacInputs[Method] extends Record<string, never>
      ? [methodArgs?: RbacInputs[Method]]
      : [methodArgs: RbacInputs[Method]]
  ) => Promise<RbacOutputs[Method]>;
  /** Submit with the generic invocation object, omitting only the fixed method. */
  readonly invoke: (
    args: Omit<RbacCall<Method>, "method"> & RbacInvocation,
  ) => Promise<RbacInvocationResult<RbacOutputs[Method]>>;
};

// -----------------------------------------------------------------------------
// Contract types
// -----------------------------------------------------------------------------

/** The Role type declared by the contract. */
export type Role = SorobanType.Custom<{
  kind: "enum";
  encoding: "tagged";
  variants: {
    /** Highest authority; may reassign all operational roles. */
    Admin: SorobanType.Void;
    Treasurer: SorobanType.Void;
    Rebalancer: SorobanType.Void;
    Upgrader: SorobanType.Void;
  };
}>;

/** Raw or validated values accepted by the Role factory. */
export type RoleArgs = SorobanType.Input.Custom<Role>;

/** Validate, encode and decode Role using its contract declaration. */
export const Role: SorobanType.Factory<Role> = SorobanType
  .Custom.fromSpec<Role>(
    () => RbacSpec,
    "Role",
  );

// -----------------------------------------------------------------------------
// Events
// -----------------------------------------------------------------------------

/** Fields emitted by RoleChanged. */
export type RoleChanged = {
  role: Role;
  operator: SorobanType.Address;
  previous: SorobanType.Option<SorobanType.Address>;
  current: SorobanType.Address;
};

/** Indexed fields accepted by the RoleChanged event filters. */
export type RoleChangedTopics = {
  role: RoleArgs;
  operator: SorobanType.Input.Address;
};

/** Fields emitted by AdminTransferProposed. */
export type AdminTransferProposed = {
  operator: SorobanType.Address;
  proposed: SorobanType.Address;
};

/** Indexed fields accepted by the AdminTransferProposed event filters. */
export type AdminTransferProposedTopics = {
  operator: SorobanType.Input.Address;
};

/** Fields emitted by AdminTransferCancelled. */
export type AdminTransferCancelled = {
  operator: SorobanType.Address;
  proposed: SorobanType.Address;
};

/** Indexed fields accepted by the AdminTransferCancelled event filters. */
export type AdminTransferCancelledTopics = {
  operator: SorobanType.Input.Address;
};

/** Event definitions bound to this client, with typed decoding and filters. */
export type RbacEvents = ContractEventRegistry & {
  readonly RoleChanged: ContractEventDefinition<
    RoleChanged,
    RoleChangedTopics
  >;
  readonly AdminTransferProposed: ContractEventDefinition<
    AdminTransferProposed,
    AdminTransferProposedTopics
  >;
  readonly AdminTransferCancelled: ContractEventDefinition<
    AdminTransferCancelled,
    AdminTransferCancelledTopics
  >;
};

// -----------------------------------------------------------------------------
// Client configuration
// -----------------------------------------------------------------------------

/** Configure the contract and prepare error messages before construction. */
export type RbacConstructorArgs = ContractConstructorArgs & {
  errors?: ContractErrorMap | false;
};
